fields:
- name: id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: old_subscription_id
- name: valid_from
  type: TIMESTAMP
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: valid_from
- name: valid_to
  type: TIMESTAMP
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: valid_to
- name: google_subscriptions_revised_changelog_id
  type: STRING
  mode: NULLABLE
  description: |-
    ID of the `google_subscriptions_revised_changelog_v1` record this history record was derived from.
- name: original_subscription_purchase_token
  type: STRING
  mode: NULLABLE
  description: |-
    The subscription's original purchase token.
    This can differ from `subscription.metadata.purchase_token` if the subscription has had a series of purchases (e.g. upgrades/downgrades).
- !include-field
  table: moz-fx-data-shared-prod.subscription_platform_derived.google_subscriptions_revised_changelog_v1
  field: subscription
  new_description: |-
    Google subscription as it ostensibly was during the time range this history record is considered valid for.
