-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.regrets_reporter.events`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.regrets_reporter_ucs.events`
