SELECT date,
  entity_type,
  attributes.id AS attributes_id,
  attributes.reason AS attributes_reason,
  attributes.locale AS attributes_locale,
  attributes.message AS attributesvmessage,
  attributes.created AS  attributes_created,
  attributes.considers_illegal AS attributes_considers_illegal,
  attributes.illegal_category AS attributesvillegal_category,
  attributes.illegal_subcategory AS attributes_illegal_subcategory,
  json_value(related_entity_attributes, "$.body") AS rel_attr_body,
  json_value(related_entity_attributes, "$.comments") AS rel_attr_comments,
  json_value(related_entity_attributes, "$.created")AS rel_attr_created,
  json_value(related_entity_attributes, "$.description") AS rel_attr_description,
  json_value(related_entity_attributes, "$.guid") AS rel_attr_guid,
  json_value(related_entity_attributes, "$.homepage") AS rel_attr_homepage,
  json_value(related_entity_attributes, "$.icon.value") AS rel_attr_icon_value,
  json_value(related_entity_attributes, "$.icon.mime_type") AS rel_attr_icon_mime_type,
  json_value(related_entity_attributes, "$.id") AS rel_attr_id,
  json_value(related_entity_attributes, "$.last_updated") AS rel_attr_last_updated,
  json_value(related_entity_attributes, "$.name") AS rel_attr_name,
  json_value(related_entity_attributes, "$.previews ") AS rel_attr_previews ,
  json_value(related_entity_attributes, "$.privacy_policy") AS rel_attr_privacy_policy,
  json_value(related_entity_attributes, "$.promoted_badge") AS rel_attr_promoted_badge,
  json_value(related_entity_attributes, "$.release_notes") AS rel_attr_release_notes,
  json_value(related_entity_attributes, "$.slug") AS rel_attr_slug,
  json_value(related_entity_attributes, "$.summary") AS rel_attr_summary,
  json_value(related_entity_attributes, "$.support_email") AS rel_attr_support_email,
  json_value(related_entity_attributes, "$.support_url") AS rel_attr_support_url,
  json_value(related_entity_attributes, "$.version") AS rel_attr_version,
FROM `moz-fx-data-shared-prod.analysis.mh_cinder_reports_raw_v1c`
