fields:
- name: flow_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: flow_id
- name: flow_started_at
  type: TIMESTAMP
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: flow_started_at
- name: impression_at
  type: TIMESTAMP
  mode: NULLABLE
  description: Timestamp of the specific impression event within the flow, such as when a subscription product
    page or signup form was viewed.
- name: event_type
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: event_type
- name: entrypoint
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: entrypoint
- name: entrypoint_experiment
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: entrypoint_experiment
- name: entrypoint_variation
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: entrypoint_variation
- name: utm_campaign
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: utm_campaign
- name: utm_content
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: utm_content
- name: utm_medium
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: utm_medium
- name: utm_source
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: utm_source
- name: utm_term
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: utm_term
- name: mozilla_account_ids_sha256
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: mozilla_account_ids_sha256
- name: oauth_client_ids
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: oauth_client_ids
- name: oauth_client_names
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: oauth_client_names
- name: product_ids
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: product_ids
- name: plan_ids
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: plan_ids
- name: service_ids
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: service_ids
