CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.activity_stream.spoc_fills`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.activity_stream_stable.spoc_fills_v1`
