CREATE OR REPLACE FUNCTION norm.get_country_code(
    str STRING
) AS (
CASE
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("af", "afghanistan", "the islamic republic of afghanistan") THEN 'AF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ax", "åland", "aland", "åland islands", "aland islands") THEN 'AX'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("al", "albania", "the republic albania") THEN 'AL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("dz", "algeria", "the people's democratic republic of algeria") THEN 'DZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("as", "american samoa", "the territory of american samoa") THEN 'AS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ad", "andorra", "the principality of andorra") THEN 'AD'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ao", "angola", "the republic of angola") THEN 'AO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ai", "anguilla") THEN 'AI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("aq", "antarctica") THEN 'AQ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ag", "antigua and barbuda") THEN 'AG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ar", "argentina", "the argentine republic") THEN 'AR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("am", "armenia", "the republic of armenia") THEN 'AM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("aw", "aruba") THEN 'AW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("au", "australia", "the commonwealth of australia") THEN 'AU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("at", "austria", "the republic of austria") THEN 'AT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("az", "azerbaijan", "the republic of azerbaijan") THEN 'AZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bs", "bahamas", "the bahamas", "the commonwealth of the bahamas") THEN 'BS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bh", "bahrain", "the kingdom of bahrain") THEN 'BH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bd", "bangladesh", "the people's republic of bangladesh") THEN 'BD'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bb", "barbados") THEN 'BB'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("by", "belarus", "the republic of belarus") THEN 'BY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("be", "belgium", "the kingdom of belgium") THEN 'BE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bz", "belize") THEN 'BZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bj", "benin", "the republic of benin") THEN 'BJ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bm", "bermuda") THEN 'BM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bt", "bhutan", "the kingdom of bhutan") THEN 'BT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bo", "bolivia", "the plurinational state of bolivia") THEN 'BO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bq", "saba", "bonaire", "sint eustatius", "bonaire, sint eustatius and saba") THEN 'BQ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ba", "bosnia and herzegovina") THEN 'BA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bw", "botswana", "the republic of botswana") THEN 'BW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bv", "bouvet island") THEN 'BV'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("br", "brazil", "the federative republic of brazil") THEN 'BR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("io", "the british indian ocean territory") THEN 'IO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bn", "brunei", "brunei darussalam", "the nation of brunei, the abode of peace") THEN 'BN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bg", "bulgaria", "the republic of bulgaria") THEN 'BG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bf", "burkina faso") THEN 'BF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bi", "burundi", "the republic of burundi") THEN 'BI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cv", "cape verde", "cabo verde", "the republic of cabo verde") THEN 'CV'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("kh", "cambodia", "the kingdom of cambodia") THEN 'KH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cm", "cameroon", "the republic of cameroon") THEN 'CM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ca", "canada") THEN 'CA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ky", "cayman islands", "the cayman islands") THEN 'KY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cf", "central african republic", "the central african republic") THEN 'CF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("td", "chad", "the republic of chad") THEN 'TD'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cl", "chile", "the republic of chile") THEN 'CL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cn", "china", "the people's republic of china") THEN 'CN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cx", "christmas island", "the territory of christmas island") THEN 'CX'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cc", "cocos (keeling) islands", "the territory of cocos (keeling) islands") THEN 'CC'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("co", "colombia", "the republic of colombia") THEN 'CO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("km", "comoros", "the union of the comoros") THEN 'KM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cd", "congo (drc)", "democratic republic of the congo", "the democratic republic of the congo") THEN 'CD'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cg", "congo", "republic of the congo", "the republic of the congo") THEN 'CG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ck", "cook islands", "the cook islands") THEN 'CK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cr", "costa rica", "the republic of costa rica") THEN 'CR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ci", "ivory coast", "côte d’ivoire", "côte d'ivoire", "cã´te dâ€™ivoire", "the republic of côte d'ivoire") THEN 'CI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("hr", "croatia", "the republic of croatia") THEN 'HR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cu", "cuba", "the republic of cuba") THEN 'CU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cw", "curacao", "curaçao", "curaã§ao", "the country of curaçao") THEN 'CW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cy", "cyprus", "the republic of cyprus") THEN 'CY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("cz", "czech republic", "czechia", "the czech republic") THEN 'CZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("dk", "denmark", "the kingdom of denmark") THEN 'DK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("dj", "djibouti", "the republic of djibouti") THEN 'DJ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("dm", "dominica", "the commonwealth of dominica") THEN 'DM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("do", "dominican republic", "the dominican republic") THEN 'DO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ec", "ecuador", "the republic of ecuador") THEN 'EC'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("eg", "egypt", "the arab republic of egypt") THEN 'EG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sv", "el salvador", "the republic of el salvador") THEN 'SV'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gq", "equatorial guinea", "the republic of equatorial guinea") THEN 'GQ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("er", "eritrea", "the state of eritrea") THEN 'ER'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ee", "estonia", "the republic of estonia") THEN 'EE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sz", "eswatini", "the kingdom of eswatini", "swaziland") THEN 'SZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("et", "ethiopia", "the federal democratic republic of ethiopia") THEN 'ET'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("fk", "falkland islands", "islas malvinas", "the falkland islands") THEN 'FK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("fo", "faroe islands", "the faroe islands") THEN 'FO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("fj", "fiji", "the republic of fiji") THEN 'FJ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("fi", "finland", "the republic of finland") THEN 'FI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("fr", "france", "the french republic") THEN 'FR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gf", "french guiana", "guyane") THEN 'GF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pf", "french polynesia") THEN 'PF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tf", "french southern and antarctic lands", "the french southern and antarctic lands") THEN 'TF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ga", "gabon", "the gabonese republic") THEN 'GA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gm", "gambia", "the gambia", "the republic of the gambia") THEN 'GM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ge", "georgia (country)", "georgia") THEN 'GE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("de", "germany", "the federal republic of germany") THEN 'DE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gh", "ghana", "the republic of ghana") THEN 'GH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gi", "gibraltar") THEN 'GI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gr", "greece", "the hellenic republic") THEN 'GR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gl", "greenland", "kalaallit nunaat") THEN 'GL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gd", "grenada") THEN 'GD'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gp", "guadeloupe") THEN 'GP'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gu", "guam", "the territory of guam") THEN 'GU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gt", "guatemala", "the republic of guatemala") THEN 'GT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gg", "bailiwick of guernsey", "guernsey", "the bailiwick of guernsey") THEN 'GG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gn", "guinea", "the republic of guinea") THEN 'GN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gw", "guinea-bissau", "the republic of guinea-bissau") THEN 'GW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gy", "guyana", "the co-operative republic of guyana") THEN 'GY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ht", "haiti", "the republic of haiti") THEN 'HT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("hm", "heard island and mcdonald islands", "the territory of heard island and mcdonald islands") THEN 'HM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("va", "vatican city", "holy see", "the holy see") THEN 'VA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("hn", "honduras", "the republic of honduras") THEN 'HN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("hk", "hong kong sar", "hong kong", "the hong kong special administrative region of china") THEN 'HK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("hu", "hungary") THEN 'HU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("is", "iceland") THEN 'IS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("in", "india", "the republic of india") THEN 'IN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("id", "indonesia", "the republic of indonesia") THEN 'ID'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ir", "iran", "iran (islamic republic of)", "the islamic republic of iran") THEN 'IR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("iq", "iraq", "the republic of iraq") THEN 'IQ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ie", "ireland", "republic of ireland") THEN 'IE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("im", "the isle of man") THEN 'IM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("il", "israel", "the state of israel") THEN 'IL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("it", "italy", "the italian republic") THEN 'IT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("jm", "jamaica") THEN 'JM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("jp", "japan") THEN 'JP'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("je", "jersey", "the bailiwick of jersey") THEN 'JE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("jo", "jordan", "the hashemite kingdom of jordan") THEN 'JO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("kz", "kazakhstan", "the republic of kazakhstan") THEN 'KZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ke", "kenya", "the republic of kenya") THEN 'KE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ki", "kiribati", "the republic of kiribati") THEN 'KI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("kp", "north korea", "the democratic people's republic of korea") THEN 'KP'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("kr", "korea", "south korea", "the republic of korea") THEN 'KR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("kw", "kuwait", "the state of kuwait") THEN 'KW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("kg", "kyrgyzstan", "the kyrgyz republic") THEN 'KG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("la", "laos", "the lao people's democratic republic") THEN 'LA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("lv", "latvia", "the republic of latvia") THEN 'LV'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("lb", "lebanon", "the lebanese republic") THEN 'LB'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ls", "lesotho", "the kingdom of lesotho") THEN 'LS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("lr", "liberia", "the republic of liberia") THEN 'LR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ly", "libya", "the state of libya") THEN 'LY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("li", "liechtenstein", "the principality of liechtenstein") THEN 'LI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("lt", "lithuania", "the republic of lithuania") THEN 'LT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("lu", "luxembourg", "the grand duchy of luxembourg") THEN 'LU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mo", "macau", "macao", "macao sar", "the macao special administrative region of china") THEN 'MO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mk", "north macedonia", "the republic of north macedonia") THEN 'MK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mg", "madagascar", "the republic of madagascar") THEN 'MG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mw", "malawi", "the republic of malawi") THEN 'MW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("my", "malaysia") THEN 'MY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mv", "maldives", "the republic of maldives") THEN 'MV'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ml", "mali", "the republic of mali") THEN 'ML'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mt", "malta", "the republic of malta") THEN 'MT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mh", "marshall islands", "the republic of the marshall islands") THEN 'MH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mq", "martinique") THEN 'MQ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mr", "mauritania", "the islamic republic of mauritania") THEN 'MR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mu", "mauritius", "the republic of mauritius") THEN 'MU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("yt", "mayotte", "the department of mayotte") THEN 'YT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mx", "mexico", "the united mexican states") THEN 'MX'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("fm", "micronesia", "federated states of micronesia", "the federated states of micronesia") THEN 'FM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("md", "moldova", "the republic of moldova") THEN 'MD'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mc", "monaco", "the principality of monaco") THEN 'MC'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mn", "mongolia") THEN 'MN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("me", "montenegro") THEN 'ME'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ms", "montserrat") THEN 'MS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ma", "morocco", "the kingdom of morocco") THEN 'MA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mz", "mozambique", "the republic of mozambique") THEN 'MZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mm", "myanmar", "the republic of the union of myanmar") THEN 'MM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("na", "namibia", "the republic of namibia") THEN 'NA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("nr", "nauru", "the republic of nauru") THEN 'NR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("np", "nepal", "the federal democratic republic of nepal") THEN 'NP'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("nl", "netherlands", "the kingdom of the netherlands") THEN 'NL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("nc", "new caledonia") THEN 'NC'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("nz", "new zealand") THEN 'NZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ni", "nicaragua", "the republic of nicaragua") THEN 'NI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ne", "niger", "the republic of the niger") THEN 'NE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ng", "nigeria", "the federal republic of nigeria") THEN 'NG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("nu", "niue") THEN 'NU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("nf", "norfolk island", "the territory of norfolk island") THEN 'NF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mp", "northern mariana islands", "the commonwealth of the northern mariana islands") THEN 'MP'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("false", "norway", "the kingdom of norway") THEN 'False'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("om", "oman", "the sultanate of oman") THEN 'OM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pk", "pakistan", "the islamic republic of pakistan") THEN 'PK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pw", "palau", "the republic of palau") THEN 'PW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ps", "state of palestine", "palestinian authority", "the state of palestine") THEN 'PS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pa", "panama", "the republic of panamá") THEN 'PA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pg", "papua new guinea", "the independent state of papua new guinea") THEN 'PG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("py", "paraguay", "the republic of paraguay") THEN 'PY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pe", "peru", "the republic of perú") THEN 'PE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ph", "philippines", "the republic of the philippines") THEN 'PH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pn", "pitcairn islands", "pitcairn", "the pitcairn, henderson, ducie and oeno islands") THEN 'PN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pl", "poland", "the republic of poland") THEN 'PL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pt", "portugal", "the portuguese republic") THEN 'PT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pr", "puerto rico", "the commonwealth of puerto rico") THEN 'PR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("qa", "qatar", "the state of qatar") THEN 'QA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("re", "reunion", "réunion", "rã©union") THEN 'RE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ro", "romania") THEN 'RO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ru", "russia", "the russian federation") THEN 'RU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("rw", "rwanda", "the republic of rwanda") THEN 'RW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("bl", "saint barthélemy", "saint barthã©lemy", "the collectivity of saint-barthélemy") THEN 'BL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sh", "st helena, ascension, tristan da cunha", "saint helena, ascension and tristan da cunha") THEN 'SH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("kn", "saint kitts and nevis") THEN 'KN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("lc", "saint lucia") THEN 'LC'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("mf", "saint martin", "collectivity of saint martin saint martin (french part)", "the collectivity of saint-martin") THEN 'MF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("pm", "saint pierre and miquelon", "the overseas collectivity of saint-pierre and miquelon") THEN 'PM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("vc", "saint vincent and the grenadines") THEN 'VC'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ws", "samoa", "the independent state of samoa") THEN 'WS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sm", "san marino", "the republic of san marino") THEN 'SM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("st", "são tomé and príncipe", "sao tome and principe", "sã£o tomã© and prã­ncipe", "the democratic republic of são tomé and príncipe") THEN 'ST'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sa", "saudi arabia", "the kingdom of saudi arabia") THEN 'SA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sn", "senegal", "the republic of senegal") THEN 'SN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("rs", "serbia", "the republic of serbia") THEN 'RS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sc", "seychelles", "the republic of seychelles") THEN 'SC'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sl", "sierra leone", "the republic of sierra leone") THEN 'SL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sg", "singapore", "the republic of singapore") THEN 'SG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sx", "sint maarten") THEN 'SX'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sk", "slovakia", "the slovak republic") THEN 'SK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("si", "slovenia", "the republic of slovenia") THEN 'SI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sb", "solomon islands", "the solomon islands") THEN 'SB'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("so", "somalia", "the federal republic of somalia") THEN 'SO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("za", "south africa", "the republic of south africa") THEN 'ZA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gs", "south georgia and the south sandwich islands") THEN 'GS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ss", "south sudan", "the republic of south sudan") THEN 'SS'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("es", "spain", "the kingdom of spain") THEN 'ES'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("lk", "sri lanka", "the democratic socialist republic of sri lanka") THEN 'LK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sd", "sudan", "the republic of the sudan") THEN 'SD'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sr", "suriname", "the republic of suriname") THEN 'SR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sj", "svalbard", "jan mayen jan mayen", "svalbard and jan mayen") THEN 'SJ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("se", "sweden", "the kingdom of sweden") THEN 'SE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ch", "switzerland", "the swiss confederation") THEN 'CH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("sy", "syria", "the syrian arab republic") THEN 'SY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tw", "taiwan", "taiwan (province of china)", "the republic of china") THEN 'TW'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tj", "tajikistan", "the republic of tajikistan") THEN 'TJ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tz", "tanzania", "the united republic of tanzania") THEN 'TZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("th", "thailand", "the kingdom of thailand") THEN 'TH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tl", "east timor", "timor-leste", "the democratic republic of timor-leste") THEN 'TL'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tg", "togo", "the togolese republic") THEN 'TG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tk", "tokelau") THEN 'TK'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("to", "tonga", "the kingdom of tonga") THEN 'TO'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tt", "trinidad and tobago", "the republic of trinidad and tobago") THEN 'TT'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tn", "tunisia", "the republic of tunisia") THEN 'TN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tr", "turkey", "the republic of turkey") THEN 'TR'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tm", "turkmenistan") THEN 'TM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tc", "turks and caicos", "turks and caicos islands", "the turks and caicos islands") THEN 'TC'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("tv", "tuvalu") THEN 'TV'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ug", "uganda", "the republic of uganda") THEN 'UG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ua", "ukraine") THEN 'UA'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ae", "united arab emirates", "the united arab emirates") THEN 'AE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("gb", "united kingdom", "uk", "the united kingdom of great britain and northern ireland") THEN 'GB'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("um", "the united states minor outlying islands", "baker island, howland island, jarvis island, johnston atoll, kingman reef, midway atoll, navassa island, palmyra atoll, and wake island") THEN 'UM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("us", "united states", "usa", "the united states of america") THEN 'US'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("uy", "uruguay", "the oriental republic of uruguay") THEN 'UY'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("uz", "uzbekistan", "the republic of uzbekistan") THEN 'UZ'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("vu", "vanuatu", "the republic of vanuatu") THEN 'VU'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ve", "venezuela", "the bolivarian republic of venezuela") THEN 'VE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("vn", "vietnam", "the socialist republic of vietnam") THEN 'VN'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("vg", "british virgin islands", "virgin islands (british)", "the virgin islands") THEN 'VG'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("vi", "united states virgin islands", "u.s. virgin islands", "virgin islands (u.s.)", "the virgin islands of the united states") THEN 'VI'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("wf", "wallis and futuna", "the territory of the wallis and futuna islands") THEN 'WF'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("eh", "western sahara", "the sahrawi arab democratic republic") THEN 'EH'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("ye", "yemen", "the republic of yemen") THEN 'YE'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("zm", "zambia", "the republic of zambia") THEN 'ZM'
        WHEN LOWER(REGEXP_REPLACE(str, "CTY_", "")) IN ("zw", "zimbabwe", "the republic of zimbabwe") THEN 'ZW'
    ELSE str
END
);