fields:
- mode: NULLABLE
  name: customer_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: customer_id
- mode: NULLABLE
  name: subscription_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_id
- mode: NULLABLE
  name: original_subscription_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: original_subscription_id
- mode: NULLABLE
  name: plan_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: plan_id
- mode: NULLABLE
  name: status
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_status
- mode: NULLABLE
  name: event_timestamp
  type: TIMESTAMP
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: event_timestamp
- mode: NULLABLE
  name: subscription_start_date
  type: TIMESTAMP
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_start_date
- mode: NULLABLE
  name: created
  type: TIMESTAMP
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: created
- mode: NULLABLE
  name: trial_start
  type: TIMESTAMP
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: trial_start
- mode: NULLABLE
  name: trial_end
  type: TIMESTAMP
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: trial_end
- mode: NULLABLE
  name: cancel_at_period_end
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: cancel_at_period_end
- mode: NULLABLE
  name: ended_at
  type: TIMESTAMP
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: old_subscription_ended_at
- mode: NULLABLE
  name: ended_reason
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: old_subscription_ended_reason
- mode: NULLABLE
  name: fxa_uid
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: fxa_uid
- mode: NULLABLE
  name: provider
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: old_subscription_provider
- mode: NULLABLE
  name: plan_interval
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: old_subscription_plan_interval
- mode: NULLABLE
  name: plan_interval_count
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: old_subscription_plan_interval_count
- mode: NULLABLE
  name: plan_interval_timezone
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: plan_interval_timezone
- mode: NULLABLE
  name: product_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_last_transaction_product_id
- mode: NULLABLE
  name: in_billing_grace_period
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: in_billing_grace_period
- mode: NULLABLE
  name: billing_grace_period
  type: INTERVAL
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: billing_grace_period
- mode: REPEATED
  name: promotion_codes
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: promotion_codes
