-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.mozilla_vpn.deletion_request`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.mozillavpn.deletion_request`
