fields:
- mode: NULLABLE
  name: timestamp
  type: TIMESTAMP
  description: The precise UTC timestamp indicating when the event or record was ingested
    or generated, with microsecond-level precision.
- mode: NULLABLE
  name: email_address
  type: STRING
- mode: NULLABLE
  name: freq_deep_focused_work
  type: STRING
- mode: NULLABLE
  name: freq_understand_code
  type: STRING
- mode: NULLABLE
  name: freq_tools_intuitive
  type: STRING
- mode: NULLABLE
  name: freq_tech_debt_impact
  type: STRING
- mode: NULLABLE
  name: freq_long_technical_question_wait
  type: STRING
- mode: NULLABLE
  name: freq_code_review_within_4h
  type: STRING
- mode: NULLABLE
  name: freq_processes_easy
  type: STRING
- mode: NULLABLE
  name: agree_felt_productive
  type: STRING
- mode: NULLABLE
  name: agree_been_creative
  type: STRING
- mode: NULLABLE
  name: agree_ci_intuitive
  type: STRING
- mode: NULLABLE
  name: agree_change_confidence
  type: STRING
- mode: NULLABLE
  name: agree_learned_new_skills
  type: STRING
- mode: NULLABLE
  name: improvement_suggestion
  type: STRING
