-- Generated by ./bqetl generate events_daily
CREATE OR REPLACE TABLE
  fenix_derived.google_ads_campaign_cost_breakdowns_v1
PARTITION BY
  date
OPTIONS
  (require_partition_filter = TRUE)
AS
SELECT
  CAST(NULL AS date) AS date,
  CAST(NULL AS STRING) AS campaign_name,
  CAST(NULL AS FLOAT64) AS campaign_spend_in_cents,
  CAST(NULL AS INT64) AS ad_impressions,
  CAST(NULL AS INT64) AS ad_conversions,
  CAST(NULL AS INT64) AS installs,
  CAST(NULL AS INT64) AS dous,
  CAST(NULL AS INT64) AS marketing_ad_clicks,
  CAST(NULL AS INT64) AS revenue_generating_ad_clicks,
  CAST(NULL AS FLOAT64) AS cost_per_install_micros,
  CAST(NULL AS FLOAT64) AS cost_per_dou_micros,
  CAST(NULL AS FLOAT64) AS cost_per_marketing_ad_click_micros,
  CAST(NULL AS FLOAT64) AS cost_per_revenue_generating_ad_click_micros
