fields:
- name: ga_client_id
  mode: NULLABLE
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: ga_client_id
- name: ga_session_id
  mode: NULLABLE
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: ga_session_id
- name: session_date
  mode: NULLABLE
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: session_date
- name: is_first_session
  mode: NULLABLE
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: is_first_session
- name: session_number
  mode: NULLABLE
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: session_number
- name: time_on_site
  mode: NULLABLE
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: time_on_site
- name: pageviews
  mode: NULLABLE
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: pageviews
- name: country
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: country
- name: region
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: region
- name: city
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: city
- name: campaign_id
  type: STRING
  mode: NULLABLE
  description: "First reported campaign ID. Usually associated with AdWords."
- name: campaign
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: campaign
- name: source
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: source
- name: medium
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: medium
- name: term
  type: STRING
  mode: NULLABLE
  description: "First reported term, or keyword, value. If this was a search results page, this is the keyword entered."
- name: content
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: content
- name: gclid
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: gclid
- name: gclid_array
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: gclid_array
- name: device_category
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: device_category
- name: mobile_device_model
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: mobile_device_model
- name: mobile_device_string
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: mobile_device_string
- name: os
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: os
- name: os_version
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: os_version
- name: language
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: language
- name: browser
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: browser
- name: browser_version
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: browser_version
- name: had_download_event
  type: BOOLEAN
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: had_download_event
- name: firefox_desktop_downloads
  type: INT64
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: firefox_desktop_downloads
- name: last_reported_install_target
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: last_reported_install_target
- name: all_reported_install_targets
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: all_reported_install_targets
- name: last_reported_stub_session_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: last_reported_stub_session_id
- name: all_reported_stub_session_ids
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: all_reported_stub_session_ids
- name: landing_screen
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: landing_screen
- name: distinct_campaigns_from_event_params
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: distinct_campaigns_from_event_params
- name: first_campaign_from_event_params
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_schema.yaml
    field: first_campaign_from_event_params
