fields:
- mode: REQUIRED
  name: cpu_name
  type: STRING
  description: CPU Name
- mode: REQUIRED
  name: cpu_tdp
  type: FLOAT
  description: CPU TDP
- mode: REQUIRED
  name: cpu_cores
  type: INTEGER
  description: The number of logical CPU cores available on the client device as reported
    by the Firefox telemetry environment. Used to segment performance and hardware
    capability data.
- mode: NULLABLE
  name: cpu_type
  type: STRING
  description: CPU Type
