fields:
- mode: REQUIRED
  name: cpu_name
  type: STRING
  description: CPU Name
- mode: REQUIRED
  name: cpu_tdp
  type: FLOAT
  description: CPU TDP
- mode: REQUIRED
  name: cpu_cores
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: cpu_cores
- mode: NULLABLE
  name: cpu_type
  type: STRING
  description: CPU Type
