CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.hubs_derived.active_subscriptions_live`
AS
WITH subscriptions AS (
  SELECT
    *,
    TO_JSON_STRING(promotion_codes) AS json_promotion_codes
  FROM
    `moz-fx-data-shared-prod`.hubs.subscriptions
)
SELECT
  active_subscription_ids.active_date,
  subscriptions.plan_id,
  subscriptions.status,
  subscriptions.country,
  subscriptions.country_name,
  subscriptions.entrypoint_experiment,
  subscriptions.entrypoint_variation,
  subscriptions.utm_campaign,
  subscriptions.utm_content,
  subscriptions.utm_medium,
  subscriptions.utm_source,
  subscriptions.utm_term,
  subscriptions.provider,
  subscriptions.plan_amount,
  subscriptions.billing_scheme,
  subscriptions.plan_currency,
  subscriptions.plan_interval,
  subscriptions.plan_interval_count,
  subscriptions.product_id,
  subscriptions.product_name,
  subscriptions.pricing_plan,
  subscriptions.normalized_acquisition_channel,
  subscriptions.normalized_campaign,
  subscriptions.normalized_content,
  subscriptions.normalized_medium,
  subscriptions.normalized_source,
  subscriptions.website_channel_group,
  JSON_VALUE_ARRAY(subscriptions.json_promotion_codes) AS promotion_codes,
  subscriptions.promotion_discounts_amount,
  COUNT(*) AS `count`,
FROM
  subscriptions
JOIN
  `moz-fx-data-shared-prod`.hubs.active_subscription_ids
USING
  (subscription_id)
GROUP BY
  active_date,
  plan_id,
  status,
  country,
  country_name,
  entrypoint_experiment,
  entrypoint_variation,
  utm_campaign,
  utm_content,
  utm_medium,
  utm_source,
  utm_term,
  provider,
  plan_amount,
  billing_scheme,
  plan_currency,
  plan_interval,
  plan_interval_count,
  product_id,
  product_name,
  pricing_plan,
  normalized_acquisition_channel,
  normalized_campaign,
  normalized_content,
  normalized_medium,
  normalized_source,
  website_channel_group,
  json_promotion_codes,
  promotion_discounts_amount
