fields:
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_timestamp
- name: document_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: document_id
- name: os
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: os
- name: async_shutdown_timeout
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: async_shutdown_timeout
- name: ipc_channel_error
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: ipc_channel_error
- name: oom_allocation_size
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: oom_allocation_size
- name: moz_crash_reason
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: moz_crash_reason
- name: reason
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: reason
- name: crashing_thread
  type: INTEGER
  mode: NULLABLE
  description: The zero-based index into the threads array pointing to the thread that caused the crash;
    computed as the last thread index since only thread 0 and the crashing thread are retained after symbolication.
- name: threads
  type: RECORD
  mode: REPEATED
  fields:
  - name: frames
    type: RECORD
    mode: REPEATED
    fields:
    - name: module_offset
      type: STRING
      mode: NULLABLE
    - name: module
      type: STRING
      mode: NULLABLE
    - name: function
      type: STRING
      mode: NULLABLE
    - name: function_offset
      type: STRING
      mode: NULLABLE
    - name: file
      type: STRING
      mode: NULLABLE
    - name: line
      type: INTEGER
      mode: NULLABLE
    - name: inlines
      type: RECORD
      mode: REPEATED
      fields:
      - name: function
        type: STRING
        mode: NULLABLE
      - name: file
        type: STRING
        mode: NULLABLE
      - name: line
        type: INTEGER
        mode: NULLABLE
