fields:

- mode: NULLABLE
  name: funnel_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: funnel_date

- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: country

- mode: NULLABLE
  name: funnel_derived
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: funnel_derived

- mode: NULLABLE
  name: channel_raw
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel_raw

- mode: NULLABLE
  name: campaign
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: campaign

- mode: NULLABLE
  name: campaign_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: campaign_id

- mode: NULLABLE
  name: source
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: source

- mode: NULLABLE
  name: medium
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: medium

- mode: NULLABLE
  name: normalized_os
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_os

- mode: NULLABLE
  name: partner_org
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_org

- mode: NULLABLE
  name: distribution_model
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: distribution_model

- mode: NULLABLE
  name: distribution_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: distribution_id

- mode: NULLABLE
  name: visits
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: visits

- mode: NULLABLE
  name: downloads
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: downloads

- mode: NULLABLE
  name: installs
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: installs

- mode: NULLABLE
  name: new_profiles
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: new_profiles

- mode: NULLABLE
  name: return_user
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: return_user

- mode: NULLABLE
  name: retained_week4
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: retained_week4

- mode: NULLABLE
  name: channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel

- mode: NULLABLE
  name: subchannel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: subchannel
