fields:
- mode: NULLABLE
  name: os
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: os
- name: app_version
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_version
- name: app_build_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_build_id
- name: channel
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel
- name: metric
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: metric
- name: metric_type
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: metric_type
- name: key
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: key
- name: process
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: process
- name: first_bucket
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: first_bucket
- name: last_bucket
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: last_bucket
- name: num_buckets
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_buckets
- name: client_agg_type
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: client_agg_type
- name: agg_type
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: agg_type
- name: total_users
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: total_users
- name: aggregates
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: aggregates
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: key
  - name: value
    type: FLOAT
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: value
- name: non_norm_aggregates
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: non_norm_aggregates
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: key
  - name: value
    type: FLOAT
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: value
