fields:
- name: uid
  type: STRING
  mode: NULLABLE
  description: Account ID in hexadecimal format.
- name: credentialId
  type: STRING
  mode: NULLABLE
  description: WebAuthn credential ID in hexadecimal format.
- name: createdAt
  type: TIMESTAMP
  mode: NULLABLE
