-- Query generated by: templates/clients_daily_histogram_aggregates.sql.py
CREATE TEMPORARY FUNCTION get_keyval_pairs(y STRING)
RETURNS ARRAY<STRING>
LANGUAGE js AS
'''
  var z = new Array();
  node = JSON.parse(y);
  for (let [key, value] of Object.entries(node)) {
    z.push(`${key}:${value}`);
  }
  return z;
''';



-- convert a string like '[5, 6, 7]' to an array struct
CREATE TEMPORARY FUNCTION string_to_arr(y STRING)
RETURNS ARRAY<STRING>
LANGUAGE js AS
'''
  return JSON.parse(y);
''';


CREATE TEMP FUNCTION udf_get_bucket_range(histograms ARRAY<STRING>) AS ((
  WITH buckets AS (
    SELECT
      string_to_arr(JSON_EXTRACT(histogram, "$.range")) AS bucket_range,
      SAFE_CAST(JSON_EXTRACT(histogram, "$.bucket_count") AS INT64) AS num_buckets
    FROM UNNEST(histograms) AS histogram
    WHERE histogram IS NOT NULL
    LIMIT 1
  )

  SELECT AS STRUCT
    SAFE_CAST(bucket_range[OFFSET(0)] AS INT64) AS first_bucket,
    SAFE_CAST(bucket_range[OFFSET(1)] AS INT64) AS last_bucket,
    num_buckets
  FROM
    buckets));


CREATE TEMP FUNCTION udf_get_histogram_type(histograms ARRAY<STRING>) AS ((
    SELECT
      CASE SAFE_CAST(JSON_EXTRACT(histogram, "$.histogram_type") AS INT64)
        WHEN 0 THEN 'histogram-exponential'
        WHEN 1 THEN 'histogram-linear'
        WHEN 2 THEN 'histogram-boolean'
        WHEN 3 THEN 'histogram-flag'
        WHEN 4 THEN 'histogram-count'
        WHEN 5 THEN 'histogram-categorical'
      END AS histogram_type
    FROM UNNEST(histograms) AS histogram
    WHERE histogram IS NOT NULL
    LIMIT 1
));

CREATE TEMP FUNCTION
  udf_aggregate_json_sum(histograms ARRAY<STRING>) AS (ARRAY(
      SELECT
        AS STRUCT SPLIT(keyval, ':')[OFFSET(0)] AS key,
        SUM(SAFE_CAST(SPLIT(keyval, ':')[OFFSET(1)] AS INT64)) AS value
      FROM
        UNNEST(histograms) AS histogram,
        UNNEST(get_keyval_pairs(JSON_EXTRACT(histogram, "$.values"))) AS keyval
      WHERE histogram IS NOT NULL
      GROUP BY key));

WITH filtered AS (
    SELECT
        *,
        SPLIT(application.version, '.')[OFFSET(0)] AS app_version,
        DATE(submission_timestamp) as submission_date,
        normalized_os as os,
        application.build_id AS app_build_id,
        normalized_channel AS channel
    FROM `moz-fx-data-shared-prod.telemetry_stable.main_v4`
    WHERE DATE(submission_timestamp) = @submission_date
        AND normalized_channel in (
          "release", "beta", "nightly"
        )
        AND client_id IS NOT NULL),


grouped_metrics AS
  (select
    submission_timestamp,
    DATE(submission_timestamp) as submission_date,
    client_id,
    normalized_os as os,
    SPLIT(application.version, '.')[OFFSET(0)] AS app_version,
    application.build_id AS app_build_id,
    normalized_channel AS channel,
    ARRAY<STRUCT<
        name STRING,
        process STRING,
        value ARRAY<STRUCT<key STRING, value STRING>>
    >>[
        ('addon_content_policy_shim_blocking_loaded_ms', 'content', payload.processes.content.keyed_histograms.addon_content_policy_shim_blocking_loaded_ms),
        ('addon_content_policy_shim_blocking_loaded_ms', 'parent', payload.keyed_histograms.addon_content_policy_shim_blocking_loaded_ms),
        ('addon_content_policy_shim_blocking_loading_ms', 'content', payload.processes.content.keyed_histograms.addon_content_policy_shim_blocking_loading_ms),
        ('addon_content_policy_shim_blocking_loading_ms', 'parent', payload.keyed_histograms.addon_content_policy_shim_blocking_loading_ms),
        ('addon_forbidden_cpow_usage', 'content', payload.processes.content.keyed_histograms.addon_forbidden_cpow_usage),
        ('addon_forbidden_cpow_usage', 'parent', payload.keyed_histograms.addon_forbidden_cpow_usage),
        ('addon_shim_usage', 'content', payload.processes.content.keyed_histograms.addon_shim_usage),
        ('addon_shim_usage', 'parent', payload.keyed_histograms.addon_shim_usage),
        ('application_reputation_server_verdict_2', 'content', payload.processes.content.keyed_histograms.application_reputation_server_verdict_2),
        ('application_reputation_server_verdict_2', 'parent', payload.keyed_histograms.application_reputation_server_verdict_2),
        ('blocked_on_plugin_instance_destroy_ms', 'content', payload.processes.content.keyed_histograms.blocked_on_plugin_instance_destroy_ms),
        ('blocked_on_plugin_instance_destroy_ms', 'parent', payload.keyed_histograms.blocked_on_plugin_instance_destroy_ms),
        ('blocked_on_plugin_instance_init_ms', 'content', payload.processes.content.keyed_histograms.blocked_on_plugin_instance_init_ms),
        ('blocked_on_plugin_instance_init_ms', 'parent', payload.keyed_histograms.blocked_on_plugin_instance_init_ms),
        ('blocked_on_plugin_module_init_ms', 'content', payload.processes.content.keyed_histograms.blocked_on_plugin_module_init_ms),
        ('blocked_on_plugin_module_init_ms', 'parent', payload.keyed_histograms.blocked_on_plugin_module_init_ms),
        ('blocked_on_plugin_stream_init_ms', 'content', payload.processes.content.keyed_histograms.blocked_on_plugin_stream_init_ms),
        ('blocked_on_plugin_stream_init_ms', 'parent', payload.keyed_histograms.blocked_on_plugin_stream_init_ms),
        ('blocked_on_pluginasyncsurrogate_waitforinit_ms', 'content', payload.processes.content.keyed_histograms.blocked_on_pluginasyncsurrogate_waitforinit_ms),
        ('blocked_on_pluginasyncsurrogate_waitforinit_ms', 'parent', payload.keyed_histograms.blocked_on_pluginasyncsurrogate_waitforinit_ms),
        ('canvas_webgl_accl_failure_id', 'content', payload.processes.content.keyed_histograms.canvas_webgl_accl_failure_id),
        ('canvas_webgl_accl_failure_id', 'parent', payload.keyed_histograms.canvas_webgl_accl_failure_id),
        ('canvas_webgl_failure_id', 'content', payload.processes.content.keyed_histograms.canvas_webgl_failure_id),
        ('canvas_webgl_failure_id', 'parent', payload.keyed_histograms.canvas_webgl_failure_id),
        ('content_js_background_tick_delay_events_ms', 'content', payload.processes.content.keyed_histograms.content_js_background_tick_delay_events_ms),
        ('content_js_background_tick_delay_events_ms', 'parent', payload.keyed_histograms.content_js_background_tick_delay_events_ms),
        ('content_js_foreground_tick_delay_events_ms', 'content', payload.processes.content.keyed_histograms.content_js_foreground_tick_delay_events_ms),
        ('content_js_foreground_tick_delay_events_ms', 'parent', payload.keyed_histograms.content_js_foreground_tick_delay_events_ms),
        ('content_large_paint_phase_weight', 'content', payload.processes.content.keyed_histograms.content_large_paint_phase_weight),
        ('content_large_paint_phase_weight', 'parent', payload.keyed_histograms.content_large_paint_phase_weight),
        ('content_signature_verification_errors', 'content', payload.processes.content.keyed_histograms.content_signature_verification_errors),
        ('content_signature_verification_errors', 'parent', payload.keyed_histograms.content_signature_verification_errors),
        ('content_small_paint_phase_weight', 'content', payload.processes.content.keyed_histograms.content_small_paint_phase_weight),
        ('content_small_paint_phase_weight', 'parent', payload.keyed_histograms.content_small_paint_phase_weight),
        ('d3d11_compositing_failure_id', 'content', payload.processes.content.keyed_histograms.d3d11_compositing_failure_id),
        ('d3d11_compositing_failure_id', 'parent', payload.keyed_histograms.d3d11_compositing_failure_id),
        ('d3d9_compositing_failure_id', 'content', payload.processes.content.keyed_histograms.d3d9_compositing_failure_id),
        ('d3d9_compositing_failure_id', 'parent', payload.keyed_histograms.d3d9_compositing_failure_id),
        ('decoder_doctor_infobar_stats', 'content', payload.processes.content.keyed_histograms.decoder_doctor_infobar_stats),
        ('decoder_doctor_infobar_stats', 'parent', payload.keyed_histograms.decoder_doctor_infobar_stats),
        ('devtools_cold_toolbox_open_delay_ms', 'parent', payload.keyed_histograms.devtools_cold_toolbox_open_delay_ms),
        ('devtools_gcli_commands_keyed', 'content', payload.processes.content.keyed_histograms.devtools_gcli_commands_keyed),
        ('devtools_gcli_commands_keyed', 'parent', payload.keyed_histograms.devtools_gcli_commands_keyed),
        ('devtools_javascript_error_displayed', 'content', payload.processes.content.keyed_histograms.devtools_javascript_error_displayed),
        ('devtools_javascript_error_displayed', 'parent', payload.keyed_histograms.devtools_javascript_error_displayed),
        ('devtools_memory_breakdown_census_count', 'content', payload.processes.content.keyed_histograms.devtools_memory_breakdown_census_count),
        ('devtools_memory_breakdown_census_count', 'parent', payload.keyed_histograms.devtools_memory_breakdown_census_count),
        ('devtools_memory_breakdown_dominator_tree_count', 'content', payload.processes.content.keyed_histograms.devtools_memory_breakdown_dominator_tree_count),
        ('devtools_memory_breakdown_dominator_tree_count', 'parent', payload.keyed_histograms.devtools_memory_breakdown_dominator_tree_count),
        ('devtools_perftools_recording_features_used', 'content', payload.processes.content.keyed_histograms.devtools_perftools_recording_features_used),
        ('devtools_perftools_recording_features_used', 'parent', payload.keyed_histograms.devtools_perftools_recording_features_used),
        ('devtools_perftools_selected_view_ms', 'content', payload.processes.content.keyed_histograms.devtools_perftools_selected_view_ms),
        ('devtools_perftools_selected_view_ms', 'parent', payload.keyed_histograms.devtools_perftools_selected_view_ms),
        ('devtools_toolbox_page_reload_delay_ms', 'parent', payload.keyed_histograms.devtools_toolbox_page_reload_delay_ms),
        ('devtools_warm_toolbox_open_delay_ms', 'parent', payload.keyed_histograms.devtools_warm_toolbox_open_delay_ms),
        ('devtools_webide_connected_runtime_app_type', 'content', payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_app_type),
        ('devtools_webide_connected_runtime_app_type', 'parent', payload.keyed_histograms.devtools_webide_connected_runtime_app_type),
        ('devtools_webide_connected_runtime_id', 'content', payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_id),
        ('devtools_webide_connected_runtime_id', 'parent', payload.keyed_histograms.devtools_webide_connected_runtime_id),
        ('devtools_webide_connected_runtime_os', 'content', payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_os),
        ('devtools_webide_connected_runtime_os', 'parent', payload.keyed_histograms.devtools_webide_connected_runtime_os),
        ('devtools_webide_connected_runtime_platform_version', 'content', payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_platform_version),
        ('devtools_webide_connected_runtime_platform_version', 'parent', payload.keyed_histograms.devtools_webide_connected_runtime_platform_version),
        ('devtools_webide_connected_runtime_processor', 'content', payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_processor),
        ('devtools_webide_connected_runtime_processor', 'parent', payload.keyed_histograms.devtools_webide_connected_runtime_processor),
        ('devtools_webide_connected_runtime_type', 'content', payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_type),
        ('devtools_webide_connected_runtime_type', 'parent', payload.keyed_histograms.devtools_webide_connected_runtime_type),
        ('devtools_webide_connected_runtime_version', 'content', payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_version),
        ('devtools_webide_connected_runtime_version', 'parent', payload.keyed_histograms.devtools_webide_connected_runtime_version),
        ('dom_script_src_encoding', 'content', payload.processes.content.keyed_histograms.dom_script_src_encoding),
        ('dom_script_src_encoding', 'parent', payload.keyed_histograms.dom_script_src_encoding),
        ('form_filling_required_time_ms', 'parent', payload.keyed_histograms.form_filling_required_time_ms),
        ('fx_migration_bookmarks_import_ms', 'content', payload.processes.content.keyed_histograms.fx_migration_bookmarks_import_ms),
        ('fx_migration_bookmarks_import_ms', 'parent', payload.keyed_histograms.fx_migration_bookmarks_import_ms),
        ('fx_migration_bookmarks_jank_ms', 'content', payload.processes.content.keyed_histograms.fx_migration_bookmarks_jank_ms),
        ('fx_migration_bookmarks_jank_ms', 'parent', payload.keyed_histograms.fx_migration_bookmarks_jank_ms),
        ('fx_migration_bookmarks_quantity', 'content', payload.processes.content.keyed_histograms.fx_migration_bookmarks_quantity),
        ('fx_migration_bookmarks_quantity', 'parent', payload.keyed_histograms.fx_migration_bookmarks_quantity),
        ('fx_migration_errors', 'content', payload.processes.content.keyed_histograms.fx_migration_errors),
        ('fx_migration_errors', 'parent', payload.keyed_histograms.fx_migration_errors),
        ('fx_migration_history_import_ms', 'content', payload.processes.content.keyed_histograms.fx_migration_history_import_ms),
        ('fx_migration_history_import_ms', 'parent', payload.keyed_histograms.fx_migration_history_import_ms),
        ('fx_migration_history_jank_ms', 'content', payload.processes.content.keyed_histograms.fx_migration_history_jank_ms),
        ('fx_migration_history_jank_ms', 'parent', payload.keyed_histograms.fx_migration_history_jank_ms),
        ('fx_migration_history_quantity', 'content', payload.processes.content.keyed_histograms.fx_migration_history_quantity),
        ('fx_migration_history_quantity', 'parent', payload.keyed_histograms.fx_migration_history_quantity),
        ('fx_migration_imported_homepage', 'content', payload.processes.content.keyed_histograms.fx_migration_imported_homepage),
        ('fx_migration_imported_homepage', 'parent', payload.keyed_histograms.fx_migration_imported_homepage),
        ('fx_migration_logins_import_ms', 'content', payload.processes.content.keyed_histograms.fx_migration_logins_import_ms),
        ('fx_migration_logins_import_ms', 'parent', payload.keyed_histograms.fx_migration_logins_import_ms),
        ('fx_migration_logins_jank_ms', 'content', payload.processes.content.keyed_histograms.fx_migration_logins_jank_ms),
        ('fx_migration_logins_jank_ms', 'parent', payload.keyed_histograms.fx_migration_logins_jank_ms),
        ('fx_migration_logins_quantity', 'content', payload.processes.content.keyed_histograms.fx_migration_logins_quantity),
        ('fx_migration_logins_quantity', 'parent', payload.keyed_histograms.fx_migration_logins_quantity),
        ('fx_migration_usage', 'content', payload.processes.content.keyed_histograms.fx_migration_usage),
        ('fx_migration_usage', 'parent', payload.keyed_histograms.fx_migration_usage),
        ('fx_session_restore_content_collect_data_ms', 'content', payload.processes.content.keyed_histograms.fx_session_restore_content_collect_data_ms),
        ('fx_session_restore_content_collect_data_ms', 'parent', payload.keyed_histograms.fx_session_restore_content_collect_data_ms),
        ('fx_startup_migration_data_recency', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_data_recency),
        ('fx_startup_migration_data_recency', 'parent', payload.keyed_histograms.fx_startup_migration_data_recency),
        ('fx_startup_migration_undo_bookmarks_errorcount', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_undo_bookmarks_errorcount),
        ('fx_startup_migration_undo_bookmarks_errorcount', 'parent', payload.keyed_histograms.fx_startup_migration_undo_bookmarks_errorcount),
        ('fx_startup_migration_undo_bookmarks_ms', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_undo_bookmarks_ms),
        ('fx_startup_migration_undo_bookmarks_ms', 'parent', payload.keyed_histograms.fx_startup_migration_undo_bookmarks_ms),
        ('fx_startup_migration_undo_logins_errorcount', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_undo_logins_errorcount),
        ('fx_startup_migration_undo_logins_errorcount', 'parent', payload.keyed_histograms.fx_startup_migration_undo_logins_errorcount),
        ('fx_startup_migration_undo_logins_ms', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_undo_logins_ms),
        ('fx_startup_migration_undo_logins_ms', 'parent', payload.keyed_histograms.fx_startup_migration_undo_logins_ms),
        ('fx_startup_migration_undo_reason', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_undo_reason),
        ('fx_startup_migration_undo_reason', 'parent', payload.keyed_histograms.fx_startup_migration_undo_reason),
        ('fx_startup_migration_undo_total_ms', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_undo_total_ms),
        ('fx_startup_migration_undo_total_ms', 'parent', payload.keyed_histograms.fx_startup_migration_undo_total_ms),
        ('fx_startup_migration_undo_visits_errorcount', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_undo_visits_errorcount),
        ('fx_startup_migration_undo_visits_errorcount', 'parent', payload.keyed_histograms.fx_startup_migration_undo_visits_errorcount),
        ('fx_startup_migration_undo_visits_ms', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_undo_visits_ms),
        ('fx_startup_migration_undo_visits_ms', 'parent', payload.keyed_histograms.fx_startup_migration_undo_visits_ms),
        ('fx_startup_migration_used_recent_browser', 'content', payload.processes.content.keyed_histograms.fx_startup_migration_used_recent_browser),
        ('fx_startup_migration_used_recent_browser', 'parent', payload.keyed_histograms.fx_startup_migration_used_recent_browser),
        ('fx_tab_remote_navigation_delay_ms', 'content', payload.processes.content.keyed_histograms.fx_tab_remote_navigation_delay_ms),
        ('fx_tab_remote_navigation_delay_ms', 'parent', payload.keyed_histograms.fx_tab_remote_navigation_delay_ms),
        ('fx_tabletmode_page_load', 'content', payload.processes.content.keyed_histograms.fx_tabletmode_page_load),
        ('fx_tabletmode_page_load', 'parent', payload.keyed_histograms.fx_tabletmode_page_load),
        ('fx_urlbar_selected_result_index_by_type', 'content', payload.processes.content.keyed_histograms.fx_urlbar_selected_result_index_by_type),
        ('fx_urlbar_selected_result_index_by_type', 'parent', payload.keyed_histograms.fx_urlbar_selected_result_index_by_type),
        ('hsts_priming_request_duration', 'content', payload.processes.content.keyed_histograms.hsts_priming_request_duration),
        ('hsts_priming_request_duration', 'parent', payload.keyed_histograms.hsts_priming_request_duration),
        ('http_channel_disposition_upgrade', 'parent', payload.keyed_histograms.http_channel_disposition_upgrade),
        ('http_child_omt_stats', 'content', payload.processes.content.keyed_histograms.http_child_omt_stats),
        ('http_traffic_analysis_2', 'parent', payload.keyed_histograms.http_traffic_analysis_2),
        ('http_traffic_analysis_3', 'parent', payload.keyed_histograms.http_traffic_analysis_3),
        ('idle_runnable_budget_overuse_ms', 'content', payload.processes.content.keyed_histograms.idle_runnable_budget_overuse_ms),
        ('idle_runnable_budget_overuse_ms', 'parent', payload.keyed_histograms.idle_runnable_budget_overuse_ms),
        ('ipc_read_main_thread_latency_ms', 'content', payload.processes.content.keyed_histograms.ipc_read_main_thread_latency_ms),
        ('ipc_read_main_thread_latency_ms', 'parent', payload.keyed_histograms.ipc_read_main_thread_latency_ms),
        ('ipc_reply_size', 'content', payload.processes.content.keyed_histograms.ipc_reply_size),
        ('ipc_reply_size', 'parent', payload.keyed_histograms.ipc_reply_size),
        ('ipc_sync_main_latency_ms', 'content', payload.processes.content.keyed_histograms.ipc_sync_main_latency_ms),
        ('ipc_sync_main_latency_ms', 'parent', payload.keyed_histograms.ipc_sync_main_latency_ms),
        ('ipc_sync_message_manager_latency_ms', 'content', payload.processes.content.keyed_histograms.ipc_sync_message_manager_latency_ms),
        ('ipc_sync_message_manager_latency_ms', 'parent', payload.keyed_histograms.ipc_sync_message_manager_latency_ms),
        ('ipc_sync_receive_ms', 'content', payload.processes.content.keyed_histograms.ipc_sync_receive_ms),
        ('ipc_sync_receive_ms', 'parent', payload.keyed_histograms.ipc_sync_receive_ms),
        ('ipc_write_main_thread_latency_ms', 'content', payload.processes.content.keyed_histograms.ipc_write_main_thread_latency_ms),
        ('ipc_write_main_thread_latency_ms', 'parent', payload.keyed_histograms.ipc_write_main_thread_latency_ms),
        ('js_telemetry_addon_exceptions', 'content', payload.processes.content.keyed_histograms.js_telemetry_addon_exceptions),
        ('js_telemetry_addon_exceptions', 'parent', payload.keyed_histograms.js_telemetry_addon_exceptions),
        ('main_thread_runnable_ms', 'content', payload.processes.content.keyed_histograms.main_thread_runnable_ms),
        ('main_thread_runnable_ms', 'parent', payload.keyed_histograms.main_thread_runnable_ms),
        ('media_codec_used', 'content', payload.processes.content.keyed_histograms.media_codec_used),
        ('media_codec_used', 'parent', payload.keyed_histograms.media_codec_used),
        ('memory_distribution_among_content', 'content', payload.processes.content.keyed_histograms.memory_distribution_among_content),
        ('memory_distribution_among_content', 'parent', payload.keyed_histograms.memory_distribution_among_content),
        ('narrate_content_by_language_2', 'content', payload.processes.content.keyed_histograms.narrate_content_by_language_2),
        ('narrate_content_by_language_2', 'parent', payload.keyed_histograms.narrate_content_by_language_2),
        ('network_cache_entry_count', 'parent', payload.keyed_histograms.network_cache_entry_count),
        ('network_cache_entry_count_share', 'parent', payload.keyed_histograms.network_cache_entry_count_share),
        ('network_cache_isolation_entry_count_increase', 'parent', payload.keyed_histograms.network_cache_isolation_entry_count_increase),
        ('network_cache_isolation_size_increase', 'parent', payload.keyed_histograms.network_cache_isolation_size_increase),
        ('network_cache_isolation_unique_site_access_count', 'parent', payload.keyed_histograms.network_cache_isolation_unique_site_access_count),
        ('network_cache_size', 'parent', payload.keyed_histograms.network_cache_size),
        ('network_cache_size_share', 'parent', payload.keyed_histograms.network_cache_size_share),
        ('network_http_redirect_to_scheme', 'parent', payload.keyed_histograms.network_http_redirect_to_scheme),
        ('notify_observers_latency_ms', 'content', payload.processes.content.keyed_histograms.notify_observers_latency_ms),
        ('notify_observers_latency_ms', 'parent', payload.keyed_histograms.notify_observers_latency_ms),
        ('opengl_compositing_failure_id', 'content', payload.processes.content.keyed_histograms.opengl_compositing_failure_id),
        ('opengl_compositing_failure_id', 'parent', payload.keyed_histograms.opengl_compositing_failure_id),
        ('permission_request_handling_user_input', 'parent', payload.keyed_histograms.permission_request_handling_user_input),
        ('permission_request_origin_scheme', 'parent', payload.keyed_histograms.permission_request_origin_scheme),
        ('permission_request_third_party_origin', 'parent', payload.keyed_histograms.permission_request_third_party_origin),
        ('popup_notification_dismissal_ms', 'content', payload.processes.content.keyed_histograms.popup_notification_dismissal_ms),
        ('popup_notification_dismissal_ms', 'parent', payload.keyed_histograms.popup_notification_dismissal_ms),
        ('popup_notification_main_action_ms', 'content', payload.processes.content.keyed_histograms.popup_notification_main_action_ms),
        ('popup_notification_main_action_ms', 'parent', payload.keyed_histograms.popup_notification_main_action_ms),
        ('popup_notification_stats', 'content', payload.processes.content.keyed_histograms.popup_notification_stats),
        ('popup_notification_stats', 'parent', payload.keyed_histograms.popup_notification_stats),
        ('preferences_file_load_num_prefs', 'content', payload.processes.content.keyed_histograms.preferences_file_load_num_prefs),
        ('preferences_file_load_num_prefs', 'parent', payload.keyed_histograms.preferences_file_load_num_prefs),
        ('preferences_file_load_size_b', 'content', payload.processes.content.keyed_histograms.preferences_file_load_size_b),
        ('preferences_file_load_size_b', 'parent', payload.keyed_histograms.preferences_file_load_size_b),
        ('preferences_file_load_time_us', 'content', payload.processes.content.keyed_histograms.preferences_file_load_time_us),
        ('preferences_file_load_time_us', 'parent', payload.keyed_histograms.preferences_file_load_time_us),
        ('presshell_flushes_per_tick', 'content', payload.processes.content.keyed_histograms.presshell_flushes_per_tick),
        ('presshell_flushes_per_tick', 'parent', payload.keyed_histograms.presshell_flushes_per_tick),
        ('presshell_layout_total_ms_per_tick', 'content', payload.processes.content.keyed_histograms.presshell_layout_total_ms_per_tick),
        ('presshell_layout_total_ms_per_tick', 'parent', payload.keyed_histograms.presshell_layout_total_ms_per_tick),
        ('presshell_reqs_per_layout_flush', 'content', payload.processes.content.keyed_histograms.presshell_reqs_per_layout_flush),
        ('presshell_reqs_per_layout_flush', 'parent', payload.keyed_histograms.presshell_reqs_per_layout_flush),
        ('print_count', 'content', payload.processes.content.keyed_histograms.print_count),
        ('print_count', 'parent', payload.keyed_histograms.print_count),
        ('print_dialog_opened_count', 'content', payload.processes.content.keyed_histograms.print_dialog_opened_count),
        ('print_dialog_opened_count', 'parent', payload.keyed_histograms.print_dialog_opened_count),
        ('process_crash_submit_attempt', 'content', payload.processes.content.keyed_histograms.process_crash_submit_attempt),
        ('process_crash_submit_attempt', 'parent', payload.keyed_histograms.process_crash_submit_attempt),
        ('process_crash_submit_success', 'content', payload.processes.content.keyed_histograms.process_crash_submit_success),
        ('process_crash_submit_success', 'parent', payload.keyed_histograms.process_crash_submit_success),
        ('pwmgr_manage_sorted', 'content', payload.processes.content.keyed_histograms.pwmgr_manage_sorted),
        ('pwmgr_manage_sorted', 'parent', payload.keyed_histograms.pwmgr_manage_sorted),
        ('qm_first_initialization_attempt', 'parent', payload.keyed_histograms.qm_first_initialization_attempt),
        ('qm_init_telemetry_error', 'parent', payload.keyed_histograms.qm_init_telemetry_error),
        ('refresh_driver_tick_phase_weight', 'content', payload.processes.content.keyed_histograms.refresh_driver_tick_phase_weight),
        ('refresh_driver_tick_phase_weight', 'parent', payload.keyed_histograms.refresh_driver_tick_phase_weight),
        ('rejected_message_manager_message', 'content', payload.processes.content.keyed_histograms.rejected_message_manager_message),
        ('rejected_message_manager_message', 'parent', payload.keyed_histograms.rejected_message_manager_message),
        ('sandbox_failed_launch_keyed', 'parent', payload.keyed_histograms.sandbox_failed_launch_keyed),
        ('sandbox_rejected_syscalls', 'content', payload.processes.content.keyed_histograms.sandbox_rejected_syscalls),
        ('sandbox_rejected_syscalls', 'parent', payload.keyed_histograms.sandbox_rejected_syscalls),
        ('search_counts', 'content', payload.processes.content.keyed_histograms.search_counts),
        ('search_counts', 'parent', payload.keyed_histograms.search_counts),
        ('service_worker_fetch_event_channel_reset_ms', 'content', payload.processes.content.keyed_histograms.service_worker_fetch_event_channel_reset_ms),
        ('service_worker_fetch_event_channel_reset_ms', 'parent', payload.keyed_histograms.service_worker_fetch_event_channel_reset_ms),
        ('service_worker_fetch_event_dispatch_ms', 'content', payload.processes.content.keyed_histograms.service_worker_fetch_event_dispatch_ms),
        ('service_worker_fetch_event_dispatch_ms', 'parent', payload.keyed_histograms.service_worker_fetch_event_dispatch_ms),
        ('service_worker_fetch_event_finish_synthesized_response_ms', 'content', payload.processes.content.keyed_histograms.service_worker_fetch_event_finish_synthesized_response_ms),
        ('service_worker_fetch_event_finish_synthesized_response_ms', 'parent', payload.keyed_histograms.service_worker_fetch_event_finish_synthesized_response_ms),
        ('service_worker_fetch_interception_duration_ms', 'content', payload.processes.content.keyed_histograms.service_worker_fetch_interception_duration_ms),
        ('service_worker_fetch_interception_duration_ms', 'parent', payload.keyed_histograms.service_worker_fetch_interception_duration_ms),
        ('ssl_time_until_handshake_finished_keyed_by_ka', 'content', payload.processes.content.keyed_histograms.ssl_time_until_handshake_finished_keyed_by_ka),
        ('ssl_time_until_handshake_finished_keyed_by_ka', 'parent', payload.keyed_histograms.ssl_time_until_handshake_finished_keyed_by_ka),
        ('storage_sync_get_ops_size', 'content', payload.processes.content.keyed_histograms.storage_sync_get_ops_size),
        ('storage_sync_get_ops_size', 'parent', payload.keyed_histograms.storage_sync_get_ops_size),
        ('storage_sync_remove_ops', 'content', payload.processes.content.keyed_histograms.storage_sync_remove_ops),
        ('storage_sync_remove_ops', 'parent', payload.keyed_histograms.storage_sync_remove_ops),
        ('storage_sync_set_ops_size', 'content', payload.processes.content.keyed_histograms.storage_sync_set_ops_size),
        ('storage_sync_set_ops_size', 'parent', payload.keyed_histograms.storage_sync_set_ops_size),
        ('subprocess_abnormal_abort', 'content', payload.processes.content.keyed_histograms.subprocess_abnormal_abort),
        ('subprocess_abnormal_abort', 'parent', payload.keyed_histograms.subprocess_abnormal_abort),
        ('subprocess_crashes_with_dump', 'content', payload.processes.content.keyed_histograms.subprocess_crashes_with_dump),
        ('subprocess_crashes_with_dump', 'parent', payload.keyed_histograms.subprocess_crashes_with_dump),
        ('subprocess_kill_hard', 'content', payload.processes.content.keyed_histograms.subprocess_kill_hard),
        ('subprocess_kill_hard', 'parent', payload.keyed_histograms.subprocess_kill_hard),
        ('subprocess_launch_failure', 'content', payload.processes.content.keyed_histograms.subprocess_launch_failure),
        ('subprocess_launch_failure', 'parent', payload.keyed_histograms.subprocess_launch_failure),
        ('sync_worker_operation', 'content', payload.processes.content.keyed_histograms.sync_worker_operation),
        ('sync_worker_operation', 'parent', payload.keyed_histograms.sync_worker_operation),
        ('telemetry_invalid_ping_type_submitted', 'content', payload.processes.content.keyed_histograms.telemetry_invalid_ping_type_submitted),
        ('telemetry_invalid_ping_type_submitted', 'parent', payload.keyed_histograms.telemetry_invalid_ping_type_submitted),
        ('telemetry_send_failure_type_per_ping', 'parent', payload.keyed_histograms.telemetry_send_failure_type_per_ping),
        ('thread_wakeup', 'content', payload.processes.content.keyed_histograms.thread_wakeup),
        ('thread_wakeup', 'parent', payload.keyed_histograms.thread_wakeup),
        ('translated_pages_by_language', 'content', payload.processes.content.keyed_histograms.translated_pages_by_language),
        ('translated_pages_by_language', 'parent', payload.keyed_histograms.translated_pages_by_language),
        ('translation_opportunities_by_language', 'content', payload.processes.content.keyed_histograms.translation_opportunities_by_language),
        ('translation_opportunities_by_language', 'parent', payload.keyed_histograms.translation_opportunities_by_language),
        ('update_check_extended_error_external', 'content', payload.processes.content.keyed_histograms.update_check_extended_error_external),
        ('update_check_extended_error_external', 'parent', payload.keyed_histograms.update_check_extended_error_external),
        ('update_check_extended_error_notify', 'content', payload.processes.content.keyed_histograms.update_check_extended_error_notify),
        ('update_check_extended_error_notify', 'parent', payload.keyed_histograms.update_check_extended_error_notify),
        ('uptake_remote_content_result_1', 'content', payload.processes.content.keyed_histograms.uptake_remote_content_result_1),
        ('uptake_remote_content_result_1', 'parent', payload.keyed_histograms.uptake_remote_content_result_1),
        ('urlclassifier_cl_keyed_update_time', 'content', payload.processes.content.keyed_histograms.urlclassifier_cl_keyed_update_time),
        ('urlclassifier_cl_keyed_update_time', 'parent', payload.keyed_histograms.urlclassifier_cl_keyed_update_time),
        ('urlclassifier_complete_remote_status2', 'content', payload.processes.content.keyed_histograms.urlclassifier_complete_remote_status2),
        ('urlclassifier_complete_remote_status2', 'parent', payload.keyed_histograms.urlclassifier_complete_remote_status2),
        ('urlclassifier_complete_server_response_time', 'content', payload.processes.content.keyed_histograms.urlclassifier_complete_server_response_time),
        ('urlclassifier_complete_server_response_time', 'parent', payload.keyed_histograms.urlclassifier_complete_server_response_time),
        ('urlclassifier_complete_timeout2', 'content', payload.processes.content.keyed_histograms.urlclassifier_complete_timeout2),
        ('urlclassifier_complete_timeout2', 'parent', payload.keyed_histograms.urlclassifier_complete_timeout2),
        ('urlclassifier_update_error', 'content', payload.processes.content.keyed_histograms.urlclassifier_update_error),
        ('urlclassifier_update_error', 'parent', payload.keyed_histograms.urlclassifier_update_error),
        ('urlclassifier_update_remote_network_error', 'content', payload.processes.content.keyed_histograms.urlclassifier_update_remote_network_error),
        ('urlclassifier_update_remote_network_error', 'parent', payload.keyed_histograms.urlclassifier_update_remote_network_error),
        ('urlclassifier_update_remote_status2', 'content', payload.processes.content.keyed_histograms.urlclassifier_update_remote_status2),
        ('urlclassifier_update_remote_status2', 'parent', payload.keyed_histograms.urlclassifier_update_remote_status2),
        ('urlclassifier_update_server_response_time', 'content', payload.processes.content.keyed_histograms.urlclassifier_update_server_response_time),
        ('urlclassifier_update_server_response_time', 'parent', payload.keyed_histograms.urlclassifier_update_server_response_time),
        ('urlclassifier_update_timeout', 'content', payload.processes.content.keyed_histograms.urlclassifier_update_timeout),
        ('urlclassifier_update_timeout', 'parent', payload.keyed_histograms.urlclassifier_update_timeout),
        ('video_hidden_play_time_percentage', 'content', payload.processes.content.keyed_histograms.video_hidden_play_time_percentage),
        ('video_hidden_play_time_percentage', 'parent', payload.keyed_histograms.video_hidden_play_time_percentage),
        ('video_inferred_decode_suspend_percentage', 'content', payload.processes.content.keyed_histograms.video_inferred_decode_suspend_percentage),
        ('video_inferred_decode_suspend_percentage', 'parent', payload.keyed_histograms.video_inferred_decode_suspend_percentage),
        ('video_inter_keyframe_average_ms', 'content', payload.processes.content.keyed_histograms.video_inter_keyframe_average_ms),
        ('video_inter_keyframe_average_ms', 'parent', payload.keyed_histograms.video_inter_keyframe_average_ms),
        ('video_inter_keyframe_max_ms', 'content', payload.processes.content.keyed_histograms.video_inter_keyframe_max_ms),
        ('video_inter_keyframe_max_ms', 'parent', payload.keyed_histograms.video_inter_keyframe_max_ms),
        ('video_suspend_recovery_time_ms', 'content', payload.processes.content.keyed_histograms.video_suspend_recovery_time_ms),
        ('video_suspend_recovery_time_ms', 'parent', payload.keyed_histograms.video_suspend_recovery_time_ms),
        ('video_unblackinglisting_dxva_driver_runtime_status', 'content', payload.processes.content.keyed_histograms.video_unblackinglisting_dxva_driver_runtime_status),
        ('weave_engine_sync_errors', 'content', payload.processes.content.keyed_histograms.weave_engine_sync_errors),
        ('weave_engine_sync_errors', 'parent', payload.keyed_histograms.weave_engine_sync_errors),
        ('web_permission_cleared', 'content', payload.processes.content.keyed_histograms.web_permission_cleared),
        ('web_permission_cleared', 'parent', payload.keyed_histograms.web_permission_cleared),
        ('webext_background_page_load_ms_by_addonid', 'parent', payload.keyed_histograms.webext_background_page_load_ms_by_addonid),
        ('webext_browseraction_popup_open_ms_by_addonid', 'parent', payload.keyed_histograms.webext_browseraction_popup_open_ms_by_addonid),
        ('webext_browseraction_popup_preload_result_count_by_addonid', 'parent', payload.keyed_histograms.webext_browseraction_popup_preload_result_count_by_addonid),
        ('webext_content_script_injection_ms_by_addonid', 'content', payload.processes.content.keyed_histograms.webext_content_script_injection_ms_by_addonid),
        ('webext_content_script_injection_ms_by_addonid', 'parent', payload.keyed_histograms.webext_content_script_injection_ms_by_addonid),
        ('webext_extension_startup_ms_by_addonid', 'parent', payload.keyed_histograms.webext_extension_startup_ms_by_addonid),
        ('webext_pageaction_popup_open_ms_by_addonid', 'parent', payload.keyed_histograms.webext_pageaction_popup_open_ms_by_addonid),
        ('webext_storage_local_get_ms_by_addonid', 'content', payload.processes.content.keyed_histograms.webext_storage_local_get_ms_by_addonid),
        ('webext_storage_local_get_ms_by_addonid', 'parent', payload.keyed_histograms.webext_storage_local_get_ms_by_addonid),
        ('webext_storage_local_idb_get_ms_by_addonid', 'content', payload.processes.content.keyed_histograms.webext_storage_local_idb_get_ms_by_addonid),
        ('webext_storage_local_idb_get_ms_by_addonid', 'parent', payload.keyed_histograms.webext_storage_local_idb_get_ms_by_addonid),
        ('webext_storage_local_idb_set_ms_by_addonid', 'content', payload.processes.content.keyed_histograms.webext_storage_local_idb_set_ms_by_addonid),
        ('webext_storage_local_idb_set_ms_by_addonid', 'parent', payload.keyed_histograms.webext_storage_local_idb_set_ms_by_addonid),
        ('webext_storage_local_set_ms_by_addonid', 'content', payload.processes.content.keyed_histograms.webext_storage_local_set_ms_by_addonid),
        ('webext_storage_local_set_ms_by_addonid', 'parent', payload.keyed_histograms.webext_storage_local_set_ms_by_addonid),
        ('webext_user_script_injection_ms_by_addonid', 'content', payload.processes.content.keyed_histograms.webext_user_script_injection_ms_by_addonid),
        ('webext_user_script_injection_ms_by_addonid', 'parent', payload.keyed_histograms.webext_user_script_injection_ms_by_addonid)
    ] as metrics
  FROM filtered),

  flattened_metrics AS
    (SELECT
      submission_timestamp,
      submission_date,
      client_id,
      os,
      app_version,
      app_build_id,
      channel,
      process,
      metrics.name AS metric,
      value.key AS key,
      value.value AS value
    FROM grouped_metrics
    CROSS JOIN UNNEST(metrics) AS metrics
    CROSS JOIN unnest(metrics.value) AS value),

aggregated AS (
  SELECT
      submission_date,
      client_id,
      os,
      app_version,
      app_build_id,
      channel,
      process,
      metric,
      key,
      ARRAY_AGG(value) as bucket_range,
      ARRAY_AGG(value) as value
  FROM flattened_metrics
  GROUP BY
      client_id,
      submission_date,
      os,
      app_version,
      app_build_id,
      channel,
      process,
      metric,
      key)

SELECT
  client_id,
  submission_date,
  os,
  app_version,
  app_build_id,
  channel,
  ARRAY_AGG(STRUCT<
    metric STRING,
    metric_type STRING,
    key STRING,
    process STRING,
    agg_type STRING,
    bucket_range STRUCT<
      first_bucket INT64,
      last_bucket INT64,
      num_buckets INT64
    >,
    value ARRAY<STRUCT<key STRING, value INT64>>
  >(
      metric,
      udf_get_histogram_type(bucket_range),
      key,
      process,
      '',
      udf_get_bucket_range(bucket_range),
      udf_aggregate_json_sum(value)
  )) AS histogram_aggregates
FROM aggregated
GROUP BY
  client_id,
  submission_date,
  os,
  app_version,
  app_build_id,
  channel
