type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Customer Experience
    notification_channels:
    - slack: '#cx-de-collaboration'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.customer_experience.kitsune_retrieval_index.product
    metrics:
    - saved_metric_id: has_no_unclassified_value
