fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- name: installer_type
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: installer_type
- name: update_channel
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: update_channel
- name: nbr_install_attempts
  type: INTEGER
  mode: NULLABLE
  description: Count of install attempts
- name: user_cancelled
  type: FLOAT
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: user_cancelled
- name: timeout
  type: FLOAT
  mode: NULLABLE
  description: Number of install attempts failing due to timeout
