CREATE TABLE IF NOT EXISTS
  `moz-fx-data-marketing-prod.acoustic.contact_raw_v1`(
    basket_token STRING,
    create_timestamp STRING,
    double_opt_in INTEGER,
    email STRING,
    email_format STRING,
    email_id STRING,
    email_lang STRING,
    fxa_account_deleted INTEGER,
    fxa_created_date STRING,
    fxa_first_service STRING,
    fxa_id STRING,
    cohort STRING,
    has_opted_out_of_email INTEGER,
    last_modified_date DATE,
    mailing_country STRING,
    recipient_id INTEGER,
    sfdc_id STRING,
    sub_common_voice INTEGER,
    sub_firefox_accounts_journey INTEGER,
    sub_firefox_news INTEGER,
    sub_hubs INTEGER,
    sub_internet_health_report INTEGER,
    sub_knowledge_is_power INTEGER,
    sub_miti INTEGER,
    sub_mixed_reality INTEGER,
    sub_mozilla_fellowship_awardee_alumni INTEGER,
    sub_mozilla_festival INTEGER,
    sub_mozilla_foundation INTEGER,
    sub_mozilla_technology INTEGER,
    sub_mozillians_nda INTEGER,
    sub_take_action_for_the_internet INTEGER,
    sub_test_pilot INTEGER,
    sub_about_mozilla INTEGER,
    sub_apps_and_hacks INTEGER,
    sub_rally INTEGER,
    sub_firefox_sweepstakes INTEGER,
    relay_waitlist_geo STRING,
    vpn_waitlist_geo STRING,
    vpn_waitlist_platform STRING
  )
PARTITION BY
  last_modified_date
CLUSTER BY
  has_opted_out_of_email,
  double_opt_in,
  email_lang,
  mailing_country
