-- -- Construct the JSON payload in Braze required format
-- SELECT
--   CURRENT_TIMESTAMP() AS UPDATED_AT,
--   external_id AS EXTERNAL_ID,
--   TO_JSON(
--     STRUCT(
--       email AS email,
--       email_subscribe AS email_subscribe,
--       ARRAY_AGG(
--         STRUCT(
--           subscriptions_array.firefox_subscription_id AS subscription_group_id,
--           subscriptions_array.subscription_state AS subscription_state
--         )
--         )
--       ) AS subscription_groups
--     )
--   ) AS PAYLOAD
select * from `moz-fx-data-shared-prod.braze_derived.users_v1`