CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.stripe.itemized_tax_transactions`
AS
SELECT
  id,
  type,
  currency,
  transaction_date_utc,
  tax_date_utc,
  refund_id,
  line_item_id,
  subtotal,
  total,
  tax_behavior,
  tax_code,
  jurisdiction_name,
  jurisdiction_level,
  country_code,
  state_code,
  CAST(NULL AS STRING) AS origin_resolved_address_country,
  CAST(NULL AS STRING) AS origin_resolved_address_state,
  taxability,
  taxability_reason,
  tax_rate,
  quantity,
  payment_intent_id,
  customer_tax_id,
  destination_resolved_address_country,
  destination_resolved_address_state,
  destination_resolved_address_city,
  destination_resolved_address_postal_code,
  destination_resolved_address_line1,
  destination_resolved_address_line2,
  tax_name,
  tax_type,
  taxable_amount,
  non_taxable_amount,
  tax_amount,
  filing_currency,
  filing_exchange_rate,
  filing_total,
  filing_non_taxable_amount,
  filing_taxable_amount,
  filing_tax_amount
FROM
  `moz-fx-data-shared-prod`.stripe_external.itemized_tax_transactions_v1
WHERE
  DATE(transaction_date_utc) < '2026-02-10'
UNION ALL
SELECT
  id,
  type,
  currency,
  transaction_date AS transaction_date_utc,
  tax_date AS tax_date_utc,
  CAST(NULL AS STRING) AS refund_id,
  line_item_id,
  subtotal,
  total,
  CAST(NULL AS STRING) AS tax_behavior,
  tax_code,
  jurisdiction_name,
  jurisdiction_level,
  country_code,
  state_code,
  origin_resolved_address_country,
  origin_resolved_address_state,
  taxability,
  taxability_reason,
  tax_rate,
  quantity_decimal AS quantity,
  CAST(NULL AS STRING) AS payment_intent_id,
  customer_tax_id,
  destination_resolved_address_country,
  destination_resolved_address_state,
  CAST(NULL AS STRING) AS destination_resolved_address_city,
  CAST(NULL AS STRING) AS destination_resolved_address_postal_code,
  CAST(NULL AS STRING) AS destination_resolved_address_line1,
  CAST(NULL AS STRING) AS destination_resolved_address_line2,
  tax_name,
  CAST(NULL AS STRING) AS tax_type,
  taxable_amount,
  non_taxable_amount,
  tax_amount,
  filing_currency,
  filing_exchange_rate,
  filing_total,
  filing_non_taxable_amount,
  filing_taxable_amount,
  filing_tax_amount
FROM
  `moz-fx-data-shared-prod`.stripe_external.itemized_tax_transactions_v2
WHERE
  DATE(transaction_date) >= '2026-02-10'
