"""Profile every column in a BigQuery table — distinct values, frequency, and null rate."""

import logging
import random
import re
import time
from argparse import ArgumentParser
from datetime import datetime, timezone

import anthropic
from google.cloud import bigquery

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s: %(levelname)s: %(message)s"
)

# Cardinality threshold: fields with <= 50 distinct values store the full value + frequency list.
# Fields above the threshold store only the distinct count and one example value (shape, not enumeration)
HIGH_CARDINALITY_THRESHOLD = 50
SKIP_DISTINCT_TYPES = {
    "STRUCT",
    "JSON",
    "RECORD",
    "ARRAY",
}  # COUNT(DISTINCT ...) not supported for these types
TIER3_COLUMNS = {
    "metrics"
}  # wide/repeated STRUCTs deferred to a future job. Not currently profiled.
SOURCE_PROJECT = "moz-fx-data-shared-prod"
DEST_TABLE = "mozdata-nonprod.analysis.gkabbz_data_profiling_test_v1"
CLAUDE_MODEL = "claude-sonnet-4-6"

DEST_SCHEMA = [
    bigquery.SchemaField(
        "source_project",
        "STRING",
        mode="REQUIRED",
        description="GCP project of the profiled table (e.g. moz-fx-data-shared-prod).",
    ),
    bigquery.SchemaField(
        "source_dataset",
        "STRING",
        mode="REQUIRED",
        description="BigQuery dataset of the profiled table.",
    ),
    bigquery.SchemaField(
        "source_table",
        "STRING",
        mode="REQUIRED",
        description="Name of the profiled table (without project or dataset).",
    ),
    bigquery.SchemaField(
        "column_name",
        "STRING",
        mode="REQUIRED",
        description="Field path of the profiled column, using dot notation for nested fields (e.g. client_info.app_channel).",
    ),
    bigquery.SchemaField(
        "data_type",
        "STRING",
        mode="REQUIRED",
        description="BigQuery data type of the column as reported by INFORMATION_SCHEMA.",
    ),
    bigquery.SchemaField(
        "null_rate",
        "FLOAT",
        mode="NULLABLE",
        description="Percentage of rows where this column is NULL, rounded to one decimal place. Null for undocumented (Tier 3) columns.",
    ),
    bigquery.SchemaField(
        "distinct_count",
        "INTEGER",
        mode="NULLABLE",
        description=(
            "Number of distinct non-null values observed. Null for high-cardinality columns"
            " where COUNT(DISTINCT) is unsupported (STRUCT, ARRAY, JSON) or for undocumented columns."
        ),
    ),
    bigquery.SchemaField(
        "is_high_cardinality",
        "BOOLEAN",
        mode="NULLABLE",
        description=(
            "True if distinct_count exceeds the cardinality threshold (50)."
            " High-cardinality columns store only an example value;"
            " low-cardinality columns store the full value/frequency list."
        ),
    ),
    bigquery.SchemaField(
        "example_value",
        "STRING",
        mode="NULLABLE",
        description=(
            "A single representative value sampled from the column. Only populated for high-cardinality columns."
            " PII-like values (emails, UUIDs, etc.) are stored as-is here but should not be surfaced in descriptions."
        ),
    ),
    bigquery.SchemaField(
        "values",
        "RECORD",
        mode="REPEATED",
        description="Full value/frequency list for low-cardinality columns (distinct_count <= 50). Empty for high-cardinality or undocumented columns.",
        fields=[
            bigquery.SchemaField(
                "value",
                "STRING",
                mode="NULLABLE",
                description="A distinct value observed in the column, cast to STRING.",
            ),
            bigquery.SchemaField(
                "frequency",
                "INTEGER",
                mode="NULLABLE",
                description="Number of rows containing this value in the profiled sample.",
            ),
        ],
    ),
    bigquery.SchemaField(
        "pass1_description",
        "STRING",
        mode="NULLABLE",
        description="Data-driven description generated by Claude based solely on observed column statistics (Pass 1). Null for undocumented (Tier 3) columns.",
    ),
    bigquery.SchemaField(
        "column_tier",
        "STRING",
        mode="NULLABLE",
        description=(
            "Profiling tier: 'scalar' (top-level non-STRUCT column),"
            " 'leaf' (leaf field inside a simple non-repeated STRUCT, profiled using dot notation),"
            " or 'undocumented' (ARRAY/REPEATED fields or deferred columns e.g. metrics,"
            " stored as a placeholder with no profiling data)."
        ),
    ),
    bigquery.SchemaField(
        "profiled_at",
        "TIMESTAMP",
        mode="REQUIRED",
        description="UTC timestamp of when this row was written to the profiling table.",
    ),
]


def parse_args():
    """Parse command line arguments."""
    parser = ArgumentParser(description="Profile every column in a BigQuery table.")
    parser.add_argument(
        "--table",
        required=True,
        help="Fully qualified BQ table (project.dataset.table).",
    )
    return parser.parse_args()


def get_columns(client, table):
    """Return (field_path, data_type, tier) tuples for the given table.

    Queries INFORMATION_SCHEMA to collect all columns and assign each a tier
    Tier assignment drives everything downstream i.e. what gets profiled, a description or what's passed over

    Tiers:
      scalar      - top-level non-STRUCT column
      leaf        - leaf field inside a simple (non-repeated) STRUCT
      undocumented - ARRAY/REPEATED fields or TIER3_COLUMNS (no profiling - stored with null description)
    """
    project, dataset, table_name = table.split(".")
    query = f"""
        SELECT
            fp.field_path,
            fp.data_type,
            fp.column_name,
            c.data_type AS top_level_data_type
        FROM `{project}`.`{dataset}`.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS AS fp
        JOIN `{project}`.`{dataset}`.INFORMATION_SCHEMA.COLUMNS AS c
            ON fp.table_name = c.table_name AND fp.column_name = c.column_name
        WHERE fp.table_name = '{table_name}'
        ORDER BY c.ordinal_position, fp.field_path
    """
    results = []
    for row in client.query(query).result():
        field_path = row.field_path
        data_type = row.data_type
        column_name = row.column_name
        top_level_data_type = row.top_level_data_type

        is_tier3 = (
            top_level_data_type.upper().startswith("ARRAY")
            or column_name in TIER3_COLUMNS
        )
        if is_tier3:
            if field_path == column_name:
                results.append((field_path, top_level_data_type, "undocumented"))
            continue

        if data_type.upper().startswith("STRUCT"):
            continue  # intermediate STRUCT node, not a leaf

        tier = "leaf" if "." in field_path else "scalar"
        results.append((field_path, data_type, tier))

    return results


def field_path_to_sql(field_path):
    """Convert dot-notation field path to backtick-quoted SQL reference.

    i.e. converts client_info.app_channel → `client_info`.`app_channel`
    """
    return ".".join(f"`{part}`" for part in field_path.split("."))


def field_path_to_alias(field_path):
    """Convert dot-notation field path to a flat alias (dots → double underscores) for use as column alias.

    i.e. client_info.app_channel → client_info__app_channel
    """
    return field_path.replace(".", "__")


def build_profile_query(table, columns, partition_filter=None):
    """
    Build a single query that profiles every profilable column in one pass.

    Undocumented (Tier 3) columns are excluded — they will be handled separately.
    If the table has a sample_id column, samples a random 1% slice.
    """
    profilable = [(fp, dt) for fp, dt, tier in columns if tier != "undocumented"]
    has_sample_id = any(fp == "sample_id" for fp, _ in profilable)

    total_rows = "COUNT(*) AS total_rows"
    col_stats = []
    for field_path, data_type in profilable:
        alias = field_path_to_alias(field_path)
        sql_ref = field_path_to_sql(field_path)
        col_stats.append(f"COUNTIF({sql_ref} IS NULL) AS `{alias}__nulls`")
        if any(t in data_type.upper() for t in SKIP_DISTINCT_TYPES):
            col_stats.append(f"NULL AS `{alias}__distinct`")
        else:
            col_stats.append(f"COUNT(DISTINCT {sql_ref}) AS `{alias}__distinct`")
            col_stats.append(
                f"APPROX_TOP_COUNT({sql_ref}, 50) AS `{alias}__top_values`"
            )
        col_stats.append(f"ANY_VALUE({sql_ref}) AS `{alias}__example`")

    select = ",\n        ".join([total_rows] + col_stats)

    where_clauses = []
    if partition_filter:
        where_clauses.append(partition_filter)
    if has_sample_id:
        sample_id = random.randint(1, 99)
        where_clauses.append(f"`sample_id` = {sample_id}")
        logging.info(
            f"sample_id column detected — using sample_id = {sample_id} (~1% sample)"
        )

    where = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""
    return f"SELECT {select} FROM `{table}` {where}"


def check_table_has_rows(client, table):
    """Return True if the table has at least one row, False if empty."""
    project, dataset, table_name = table.split(".")
    query = f"""
        SELECT total_rows
        FROM `{project}.region-us`.INFORMATION_SCHEMA.TABLE_STORAGE
        WHERE project_id = '{project}'
        AND table_schema = '{dataset}'
        AND table_name = '{table_name}'
    """
    rows = list(client.query(query).result())
    if not rows:
        logging.warning(f"Table not found in INFORMATION_SCHEMA: {table}")
        return False
    total_rows = rows[0].total_rows
    if total_rows == 0:
        logging.warning(f"Skipping {table} — table is empty (total_rows=0)")
        return False
    logging.info(f"Pre-flight check passed: {total_rows:,} rows in {table}")
    return True


def profile_table(client, table):
    """Profile every column in the table and return structured results."""
    # Get columns to get column tier list
    columns = get_columns(client, table)
    logging.info(f"Found {len(columns)} columns in {table}")

    # Run profile query without partition filter
    profile_query = build_profile_query(table, columns)
    partition_filter = None

    try:
        job = client.query(profile_query)
        rows = list(job.result())
        logging.info(
            f"Profile query processed {job.total_bytes_processed / 1e9:.2f} GB"
        )
    # if BQ throws "partition filter required" error, parses the partition column and retries with a 1 day window
    except Exception as e:
        error_msg = str(e)
        if "without a filter over column(s)" in error_msg:
            match = re.search(r"filter over column\(s\) '([^']+)'", error_msg)
            if not match:
                logging.error(f"Could not parse partition column from error: {e}")
                return {}
            partition_col = match.group(1)
            logging.info(
                f"Partition filter required on '{partition_col}', retrying with 1-day window from 7 days ago"
            )
            partition_filter = (
                f"DATE(`{partition_col}`) = DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)"
            )
            profile_query = build_profile_query(table, columns, partition_filter)
            try:
                job = client.query(profile_query)
                rows = list(job.result())
                logging.info(
                    f"Profile query processed {job.total_bytes_processed / 1e9:.2f} GB"
                )
            except Exception as retry_e:
                logging.error(f"Retry failed: {retry_e}")
                return {}
        else:
            logging.error(f"Failed to profile {table}: {e}")
            return {}

    row = rows[0]
    total_rows = row.total_rows
    results = {}

    # Add undocumented (Tier 3) columns first — no profiling data, just a placeholder
    for field_path, data_type, tier in columns:
        if tier == "undocumented":
            results[field_path] = {
                "type": "undocumented",
                "data_type": data_type,
                "null_rate": None,
            }

    # Profile scalar and leaf columns
    for field_path, data_type, tier in columns:
        if tier == "undocumented":
            continue
        alias = field_path_to_alias(field_path)
        null_count = getattr(row, f"{alias}__nulls")
        distinct_count = getattr(row, f"{alias}__distinct")
        example = getattr(row, f"{alias}__example")
        null_rate = round(null_count / total_rows * 100, 1) if total_rows > 0 else 0

        top_values_raw = getattr(row, f"{alias}__top_values", []) or []
        top_values = [(item["value"], item["count"]) for item in top_values_raw]

        if distinct_count is not None and distinct_count <= HIGH_CARDINALITY_THRESHOLD:
            results[field_path] = {
                "type": "low_cardinality",
                "data_type": data_type,
                "distinct_count": distinct_count,
                "null_rate": null_rate,
                "values": top_values,
            }
        else:
            results[field_path] = {
                "type": "high_cardinality",
                "data_type": data_type,
                "distinct_count": distinct_count,
                "null_rate": null_rate,
                "example": str(example),
                "values": top_values[:5],
            }

    return results


def build_description_prompt(table, col, stats):
    """Build a prompt for Pass 1 description generation."""
    lines = [
        f"Table: {table}",
        f"Column: {col}",
        f"Data type: {stats['data_type']}",
        f"Null rate: {stats['null_rate']}%",
    ]
    if stats["type"] == "low_cardinality":
        values_str = ", ".join(f"{str(v)!r} ({f:,})" for v, f in stats["values"][:10])
        lines.append(f"Distinct values: {stats['distinct_count']}")
        lines.append(f"Values (value: frequency): {values_str}")
    elif stats["type"] == "high_cardinality":
        dc = stats["distinct_count"]
        lines.append(
            f"Distinct count: {dc:,}  (high cardinality)"
            if dc is not None
            else "Distinct count: unknown (ARRAY type)"
        )
        if stats.get("values"):
            top_str = ", ".join(f"{str(v)!r} ({f:,})" for v, f in stats["values"])
            lines.append(f"Top values (value: frequency): {top_str}")
        else:
            lines.append(f"Example value: {stats['example']}")
    else:
        lines.append("Note: Complex type (STRUCT/JSON) — profiling skipped.")
        lines.append(f"Example: {stats['example']}")

    context = "\n".join(lines)
    return (
        "You are a data analyst writing field descriptions for a BigQuery data warehouse. "
        "Based only on the observed data below, write a single concise sentence describing what this column contains. "
        "Be specific — mention the type of values and what a high null rate implies about usage. "
        "Do not speculate beyond what the data shows.\n\n"
        "Important: if any example or observed value appears to be PII (e.g. an email address, UUID, user ID, IP address, or other personal identifier), "
        "do not include the actual value in your description — use a randomly generated placeholder that looks like the email, uuid, or user_id instead.\n\n"
        f"{context}\n\n"
        "Description:"
    )


def generate_descriptions(table, profile):
    """Call Claude API to generate a Pass 1 description for every column."""
    client = anthropic.Anthropic()
    logging.info(f"Generating Pass 1 descriptions for {len(profile)} columns")
    for col, stats in profile.items():
        if stats["type"] == "undocumented":
            continue
        prompt = build_description_prompt(table, col, stats)
        try:
            response = client.messages.create(
                model=CLAUDE_MODEL,
                max_tokens=256,
                messages=[{"role": "user", "content": prompt}],
            )
            stats["pass1_description"] = response.content[0].text.strip()
        except Exception as e:
            logging.error(f"Failed to generate description for {col}: {e}")
            stats["pass1_description"] = None
    return profile


def to_bq_records(table, profile):
    """Convert profile results to a list of BigQuery row dicts."""
    project, dataset, table_name = table.split(".")
    profiled_at = datetime.now(timezone.utc).isoformat()
    records = []

    for col, stats in profile.items():
        record = {
            "source_project": project,
            "source_dataset": dataset,
            "source_table": table_name,
            "column_name": col,
            "data_type": stats["data_type"],
            "null_rate": stats["null_rate"],
            "distinct_count": None,
            "is_high_cardinality": None,
            "example_value": None,
            "values": [],
            "pass1_description": stats.get("pass1_description"),
            "column_tier": stats["type"],
            "profiled_at": profiled_at,
        }

        if stats["type"] == "undocumented":
            pass  # null_rate already None, no other fields to populate
        elif stats["type"] == "low_cardinality":
            record["distinct_count"] = stats["distinct_count"]
            record["is_high_cardinality"] = False
            record["values"] = [
                {"value": str(v) if v is not None else None, "frequency": f}
                for v, f in stats["values"]
            ]
        else:
            record["distinct_count"] = stats["distinct_count"]
            record["is_high_cardinality"] = True
            record["example_value"] = stats.get("example")
            record["values"] = [
                {"value": str(v) if v is not None else None, "frequency": f}
                for v, f in stats.get("values", [])
            ]

        records.append(record)

    return records


def save_to_bq(records, dest_table):
    """Write profile records to the destination BigQuery table, creating it if needed."""
    client = bigquery.Client(project="mozdata-nonprod")
    job_config = bigquery.LoadJobConfig(
        schema=DEST_SCHEMA,
        write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
        source_format=bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
        schema_update_options=[bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION],
    )
    job = client.load_table_from_json(records, dest_table, job_config=job_config)
    job.result()
    logging.info(f"Saved {len(records)} rows to {dest_table}")


def log_profile(table, profile):
    """Log the table profile in a readable format."""
    logging.info("=" * 70)
    logging.info(f"TABLE: {table}")
    logging.info("=" * 70)
    for col, stats in profile.items():
        logging.info(f"  {col}")
        logging.info(f"    null rate:      {stats['null_rate']}%")
        if stats["type"] == "undocumented":
            logging.info(
                f"    type:           {stats['data_type']}  (undocumented — deferred to future job)"
            )
        elif stats["type"] == "low_cardinality":
            logging.info(f"    distinct count: {stats['distinct_count']}")
            for value, freq in stats["values"]:
                logging.info(f"      {str(value)!r:40} {freq:>10,}")
        else:
            dc = stats["distinct_count"]
            logging.info(
                f"    distinct count: {dc:,}  (high cardinality)"
                if dc is not None
                else "    distinct count: unknown (ARRAY type)"
            )
            logging.info(f"    example:        {stats['example']}")
        if stats.get("pass1_description"):
            logging.info(f"    description:    {stats['pass1_description']}")


def main():
    """Profile every column in a BigQuery table and save results to BigQuery."""
    args = parse_args()
    client = bigquery.Client(project=SOURCE_PROJECT)
    if not check_table_has_rows(client, args.table):
        return
    logging.info(f"Profiling {args.table}")
    start = time.time()
    profile = profile_table(client, args.table)
    profile = generate_descriptions(args.table, profile)
    elapsed = time.time() - start
    log_profile(args.table, profile)
    records = to_bq_records(args.table, profile)
    save_to_bq(records, DEST_TABLE)
    logging.info(f"Done in {elapsed:.1f}s")


if __name__ == "__main__":
    import sys

    # --- TEST BLOCK — only used when no args are passed on the command line ---
    if len(sys.argv) == 1:
        sys.argv = [
            "gk_field_sampler.py",
            "--table",
            "moz-fx-data-shared-prod.firefox_desktop_derived.newtab_items_daily_v1",
        ]
    # ----------------------------------------
    main()
