fields: !flatten-lists
- name: id
  type: STRING
  mode: NULLABLE
  description: |-
    Revised changelog ID.
- name: timestamp
  type: TIMESTAMP
  mode: NULLABLE
  description: |-
    When the change ostensibly occurred.
- name: created_at
  type: TIMESTAMP
  mode: NULLABLE
  description: |-
    When the revised changelog record was created.
- name: type
  type: STRING
  mode: NULLABLE
  description: |-
    Type of revised changelog.

    * "original" indicates the changelog wasn't altered from what SubPlat recorded.
    * "adjusted_..." indicates a minor adjustment was made, like altering when the change was considered to have occurred.
    * "synthetic_..." indicates the changelog was synthesized based on other available data.
- name: google_subscriptions_changelog_id
  type: STRING
  mode: NULLABLE
  description: |-
    ID of the `google_subscriptions_changelog_v1` record this changelog was derived from.
- !include-fields
  table: moz-fx-data-shared-prod.subscription_platform_derived.google_subscriptions_changelog_v1
  field_names:
  - firestore_export_event_id
  - firestore_export_operation
  - subscription
