-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.lockwise_android.metrics`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.mozilla_lockbox.metrics`
