CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.messaging_system.onboarding`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.messaging_system_stable.onboarding_v1`
