SELECT
  date_day,
  organization_id,
  organization_name,
  campaign_id,
  campaign_name,
  ad_group_id,
  ad_group_name,
  keyword_id,
  keyword_text,
  match_type,
  currency,
  keyword_status,
  taps,
  tap_new_downloads AS new_downloads,
  tap_redownloads AS redownloads,
  tap_total_downloads AS total_downloads,
  impressions,
  spend,
FROM
  `moz-fx-data-bq-fivetran.dbt_fivetran_transformation_apple_search_ads.apple_search_ads__keyword_report`
