fields:
- name: client_id
  type: STRING
  mode: NULLABLE
  description: ''
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: androidSdkVersion
  type: INT64
  mode: NULLABLE
  description: ''
- name: appVersion
  type: STRING
  mode: NULLABLE
  description: ''
- name: daysSinceInstall
  type: INT64
  mode: NULLABLE
  description: ''
- name: daysSinceUpdate
  type: INT64
  mode: NULLABLE
  description: ''
- name: deviceManufacturer
  type: STRING
  mode: NULLABLE
  description: ''
- name: deviceModel
  type: STRING
  mode: NULLABLE
  description: ''
- name: eventQuery_daysOpenedInLast28
  type: INT64
  mode: NULLABLE
  description: ''
- name: installReferrerResponseUtmCampaign
  type: STRING
  mode: NULLABLE
  description: ''
- name: installReferrerResponseUtmContent
  type: STRING
  mode: NULLABLE
  description: ''
- name: installReferrerResponseUtmMedium
  type: STRING
  mode: NULLABLE
  description: ''
- name: installReferrerResponseUtmSource
  type: STRING
  mode: NULLABLE
  description: ''
- name: installReferrerResponseUtmTerm
  type: STRING
  mode: NULLABLE
  description: ''
- name: isFirstRun
  type: BOOLEAN
  mode: NULLABLE
  description: ''
- name: language
  type: STRING
  mode: NULLABLE
  description: ''
- name: locale
  type: STRING
  mode: NULLABLE
  description: ''
- name: region
  type: STRING
  mode: NULLABLE
  description: ''
- name: context
  type: JSON
  mode: NULLABLE
  description: ''
