fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The UTC calendar date on which a ping or record was received by Mozilla's
    ingestion pipeline. Used as the primary partitioning and filtering dimension for
    date-based analysis.
- name: cert_load_error
  type: STRING
  mode: NULLABLE
  description: Certificate Load Error Description
- name: error_dau
  type: INTEGER
  mode: NULLABLE
  description: Number of unique clients experiencing this certificate load error
- name: error_events
  type: INTEGER
  mode: NULLABLE
  description: Number of events for this certificate load error
