type: BIGCONFIG_FILE
row_creation_times:
  column_selectors:
  - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_ios_derived.baseline_clients_city_seen_v1.first_seen_city_date
tag_deployments:
- collection:
    name: Operational Checks
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_ios_derived.baseline_clients_city_seen_v1.*
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_name: FRESHNESS
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_name: VOLUME
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
table_deployments:
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - fq_table_name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_ios_derived.baseline_clients_city_seen_v1
    columns:
    - column_name: app_id
      metrics:
      - saved_metric_id: is_not_null
        rct_overrides:
        - first_seen_city_date
    - column_name: sample_id
      metrics:
      - saved_metric_id: is_not_null
        rct_overrides:
        - first_seen_city_date
    - column_name: first_seen_city_date
      metrics:
      - saved_metric_id: is_not_null
        rct_overrides:
        - first_seen_city_date
    - column_name: first_seen_city
      metrics:
      - saved_metric_id: is_not_null
        rct_overrides:
        - first_seen_city_date
    - column_name: client_id
      metrics:
      - saved_metric_id: is_not_null
        rct_overrides:
        - first_seen_city_date
      - saved_metric_id: is_valid_client_id
        rct_overrides:
        - first_seen_city_date
      - saved_metric_id: composite_key_uniqueness_2_column
        parameters:
        - key: col_1
          column_name: client_id
        - key: col_1_string
          string_value: client_id
        - key: col_2
          column_name: app_id
        - key: col_2_string
          string_value: app_id
        - key: table
          string_value: moz-fx-data-shared-prod.firefox_ios_derived.baseline_clients_city_seen_v1
        rct_overrides:
        - FULL_SCAN
    - column_name: last_seen_city_date
      metrics:
      - saved_metric_id: is_not_null
        rct_overrides:
        - last_seen_city_date
    - column_name: last_seen_city
      metrics:
      - saved_metric_id: is_not_null
        rct_overrides:
        - last_seen_city_date
