CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.firefox_desktop.fog_validation`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.firefox_desktop_stable.fog_validation_v1`
