fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: ping
  type: STRING
- mode: NULLABLE
  name: channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel
- mode: NULLABLE
  name: metric_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: metric_name
- mode: REPEATED
  name: percentiles
  type: INTEGER
- mode: NULLABLE
  name: mean
  type: FLOAT
- mode: NULLABLE
  name: std_dev
  type: FLOAT
- mode: NULLABLE
  name: median
  type: INTEGER
