CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.telemetry.anonymous`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.telemetry_stable.anonymous_v4`
