select
  submission_date,
  search_engine,
  search_access_point,
  pocket_story_position,
  default_private_search_engine,
  default_search_engine,
  os,
  os_version,
  country_code,
  channel,
  browser_version,
  browser_name,
  newtab_open_source,
  pocket_is_signed_in,
  pocket_enabled,
  pocket_sponsored_stories_enabled,
  topsites_enabled,
  newtab_homepage_category,
  newtab_newtab_category,
  newtab_search_enabled,
  topsites_rows,
  is_new_profile,
  activity_segment,

  COUNT(DISTINCT client_id) AS client_count,
  COUNT(DISTINCT legacy_telemetry_client_id) AS legacy_telemetry_client_count,
  COUNT(DISTINCT newtab_visit_id) AS newtab_interactions_visits,
        -- Topsite
  sum(topsite_clicks) AS topsite_clicks,
  sum(sponsored_topsite_clicks) AS sponsored_topsite_clicks,
  sum(organic_topsite_clicks) AS organic_topsite_clicks,
  sum(topsite_impressions) AS topsite_impressions,
  sum(sponsored_topsite_impressions) AS sponsored_topsite_impressions,
  sum(organic_topsite_impressions) AS organic_topsite_impressions,
  sum(topsite_dismissals) AS topsite_dismissals,
  sum(sponsored_topsite_dismissals) AS sponsored_topsite_dismissals,
  sum(organic_topsite_dismissals) AS organic_topsite_dismissals,
        -- Search
  sum(searches) AS searches,
  sum(tagged_search_ad_clicks) AS tagged_search_ad_clicks,
  sum(tagged_search_ad_impressions) AS tagged_search_ad_impressions,
  sum(follow_on_search_ad_clicks) AS follow_on_search_ad_clicks,
  sum(follow_on_search_ad_impressions) AS follow_on_search_ad_impressions,
  sum(tagged_follow_on_search_ad_clicks) AS tagged_follow_on_search_ad_clicks,
  sum(tagged_follow_on_search_ad_impressions) AS tagged_follow_on_search_ad_impressions,
        -- Pocket
  sum(pocket_impressions) AS pocket_impressions,
  sum(sponsored_pocket_impressions) AS sponsored_pocket_impressions,
  sum(organic_pocket_impressions) AS organic_pocket_impressions,
  sum(pocket_clicks) AS pocket_clicks,
  sum(sponsored_pocket_clicks) AS sponsored_pocket_clicks,
  sum(organic_pocket_clicks) AS organic_pocket_clicks,
  sum(pocket_saves) AS pocket_saves,
  sum(sponsored_pocket_saves) AS sponsored_pocket_saves,
  sum(organic_pocket_saves) AS organic_pocket_saves,
from
  `moz-fx-data-shared-prod.telemetry_derived.newtab_interactions_v1`
WHERE
  submission_date = @submission_date
GROUP BY
  submission_date,
  search_engine,
  search_access_point,
  pocket_story_position,
  default_private_search_engine,
  default_search_engine,
  os,
  os_version,
  country_code,
  channel,
  browser_version,
  browser_name,
  newtab_open_source,
  pocket_is_signed_in,
  pocket_enabled,
  pocket_sponsored_stories_enabled,
  topsites_enabled,
  newtab_homepage_category,
  newtab_newtab_category,
  newtab_search_enabled,
  topsites_rows,
  is_new_profile,
  activity_segment
