CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.webpagetest.webpagetest_run`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.webpagetest_stable.webpagetest_run_v1`
