-- generated by: python3 -m bigquery_etl.glam.clients_scalar_aggregates --init --source glam.clients_daily_scalar_aggregates_v1
CREATE TABLE IF NOT EXISTS
  `moz-fx-data-shared-prod.glam_etl.fenix_clients_scalar_aggregates_v1`(
    client_id STRING,
    ping_type STRING,
    os STRING,
    app_version INT64,
    app_build_id STRING,
    channel STRING,
    scalar_aggregates ARRAY<
      STRUCT<metric STRING, metric_type STRING, key STRING, agg_type STRING, value FLOAT64>
    >
  )
PARTITION BY
  RANGE_BUCKET(app_version, GENERATE_ARRAY(0, 100, 1))
CLUSTER BY
  app_version,
  channel,
  client_id
