"""Functions that retrieve allow or block lists of probes."""
from datetime import date

from dateutil.relativedelta import relativedelta
from google.cloud import bigquery

six_months = date.today() + relativedelta(months=+6)

GLAM_USAGE_SERVICE = "https://glam.telemetry.mozilla.org/api/v1/usage/"
RECENT_PROBE_DAYS = 90


def query_hot_list():
    """Query glam_probes_hot_list to use."""
    project = "moz-fx-data-shared-prod"
    client = bigquery.Client(project)
    job = client.query(
        """
            SELECT
            metrics
            FROM
                `dev_telemetry_derived.glam_probes_hot_list` h
            INNER JOIN (
            SELECT
                MAX(date) AS max_date
            FROM
                `dev_telemetry_derived.glam_probes_hot_list`) m
            ON
            h.date = m.max_date
        """
    )
    results = job.result()
    for row in results:
        hot_list = row.metrics  # Only one row expected according to the query above
    return hot_list


def get_etl_excluded_probes_quickfix(product):
    """Provide a static list of probes that must be excluded from aggregation."""
    # See https://github.com/mozilla/glam/issues/1865
    forbidden_probes_by_product = {
        "fenix": {},
        "desktop": {"sqlite_store_open", "sqlite_store_query"},
    }
    return forbidden_probes_by_product[product]


def temp_hardcoded_most_used_probes():
    """Provide a temporary static list of most used probes - used for testing dev etl."""
    return [
        "pdfjs_editing",
        "pdfjs_buttons",
        "gfx_macos_video_low_power",
        "wr_renderer_time",
        "browser_ui_interaction_content_context",
        "perf_startup_cold_main_app_to_first_frame",
        "dns_trr_lookup_time3",
        "a11y_instantiated_flag",
        "netwerk_early_hints",
        "composite_time",
        "perf_awesomebar_bookmark_suggestions",
        "video_hdr_play_time_ms",
        "media_mkv_canplay_requested",
        "use_counter2_xsltprocessor_constructor_page",
        "wr_rasterize_blobs_time",
        "use_counter2_xslstylesheet_document",
        "glean_baseline_duration",
        "perf_first_contentful_paint_ms",
        "pdf_viewer_used",
        "browser_engagement_active_ticks",
        "video_play_time_ms",
        "crlite_vs_ocsp_result",
        "eh_num_of_hints_per_page",
        "perf_page_load_time_ms",
        "urlclassifier_cl_keyed_update_time",
        "use_counter2_xsltprocessor_constructor_document",
        "query_stripping_count",
        "glean_database_size",
        "wr_renderer_time_no_sc",
        "perf_startup_app_on_create_to_megazord_init",
        "use_counter2_xslstylesheet_page",
        "gc_ms",
        "pdf_viewer_time_to_view_ms",
        "wr_scenebuild_time",
        "dns_native_queuing",
        "wr_rasterize_glyphs_time",
        "timestamps_first_paint_two",
        "keypress_present_latency",
        "perf_awesomebar_clipboard_suggestions",
        "geckoview_page_load_time",
        "loaded_tab_count",
        "memory_total",
        "gc_slice_ms",
        "tab_count",
        "wr_renderer_time_no_sc_ms",
        "browser_set_default_user_choice_result",
        "crash_metrics_crash_count",
        "power_battery_percentage_when_user_active",
        "perf_awesomebar_shortcuts_suggestions",
        "content_full_paint_time",
        "glean_error_invalid_overflow",
        "browser_engagement_total_uri_count",
        "gc_nursery_promotion_rate",
        "browser_search_ad_clicks",
        "gc_slice_was_long",
        "startup_timeline_framework_primary",
        "perf_startup_cold_unknwn_app_to_first_frame",
        "gc_mark_rate_2",
        "use_counter2_deprecated_idbmutablefileopen_page",
        "gc_animation_ms",
        "gc_mark_ms",
        "fx_session_restore_write_file_ms",
        "http_sub_dns_issue_time",
        "use_counter2_privatebrowsingidbfactoryopen_document",
        "gc_budget_ms_2",
        "gc_prepare_ms",
        "a11y_instantiators",
        "a11y_hcm_background",
        "gc_budget_was_increased",
        "ssl_handshake_result",
        "wr_framebuild_time",
        "fx_content_crash_not_submitted",
        "perf_awesomebar_history_suggestions",
        "pdf_viewer_is_attachment",
        "contextual_services_quicksuggest_impression",
        "fog_failed_idle_registration",
        "gc_mark_roots_us",
        "query_stripping_count_by_param",
        "gc_compact_ms",
        "gmp_update_xml_fetch_result",
        "perf_dom_content_loaded_time_ms",
        "fullscreen_change_ms",
        "sidebar_opened",
        "http3_connection_close_code_3",
        "dom_contentprocess_build_id_mismatch",
        "gc_budget_overrun",
        "network_dns_end_to_connect_start_ms",
        "query_stripping_param_count",
        "use_counter2_documentexeccommandcontentreadonly_document",
        "browser_set_default_result",
        "perf_awesomebar_session_suggestions",
        "avif_sequence",
        "performance_page_non_blank_paint",
        "performance_pageload_load_time",
        "gc_reset_reason",
        "places_favicon_png_sizes",
        "perf_startup_home_fragment_on_view_created",
        "metrics_search_widget_installed",
        "a11y_backplate",
        "dnt_usage",
        "eh_time_to_final_response",
        "performance_pageload_load_time_responsestart",
        "moz_sqlite_other_sync_main_thread_ms",
        "image_decode_speed_png",
        "perf_startup_base_bfragment_on_create_view",
        "cert_validation_http_request_failed_time",
        "http_response_version",
        "perf_startup_app_on_create_to_glean_init",
        "perf_startup_home_activity_on_create",
        "dom_script_loading_source",
        "predictor_prefetch_use_status",
        "dns_lookup_time",
        "lazyload_image_not_viewport",
        "power_gpu_time_per_process_type_ms",
        "prconnect_fail_blocking_time_link_change",
        "perf_startup_cold_view_app_to_first_frame",
        "metrics_tabs_open_count",
        "gfx_hdr_windows_display_colorspace_bitfield",
        "fx_sanitize_formdata",
        "telemetry_send_failure_type",
        "places_autocomplete_1st_result_time_ms",
        "fog_ipc_buffer_sizes",
        "time_to_first_contentful_paint_ms",
        "contextual_services_quicksuggest_help_nonsponsored_bestmatch",
        "gc_time_between_slices_ms",
        "gc_reset",
        "http3_blocked_by_stream_limit_per_conn",
        "image_decode_speed_jpeg",
        "glean_validation_app_forceclosed_count",
        "input_event_response_coalesced_ms",
        "cryptominers_blocked_count",
        "browser_startup_abouthome_cache_result",
        "use_counter2_documentquerycommandstateorvalueinsertbronreturn_document",
        "contextual_services_quicksuggest_block_nonsponsored_bestmatch",
        "referrer_policy_count",
        "gc_mark_gray_ms_2",
        "cert_pinning_failures_by_ca",
        "forget_skippable_frequency",
        "browser_ui_toolbar_widgets",
        "addons_has_enabled_addons",
        "perf_startup_base_bfragment_on_view_created",
        "start_time",
        "extensions_startup_cache_load_time",
        "performance_pageload_fcp",
        "perf_awesomebar_synced_tabs_suggestions",
        "gc_time_between_s",
        "places_bookmarks_count",
        "gc_sweep_ms",
        "dns_native_lookup_time",
        "performance_pageload_dcl",
        "gc_mark_weak_ms",
        "perf_page_load",
        "webfont_download_time_after_start",
        "time_to_first_interaction_ms",
        "gc_nursery_bytes_2",
        "perf_startup_home_fragment_on_create_view",
        "text_recognition_api_performance",
        "js_pageload_baseline_compile_ms",
        "use_counter2_deprecated_mathml_deprecatedstixgeneraloperatorstretching_document",
        "time_to_dom_interactive_ms",
        "use_counter2_documentquerycommandsupportedorenabledcontentreadonly_document",
        "storage_stats_cache_bytes",
        "performance_pageload_fcp_responsestart",
        "glean_error_invalid_label",
        "fx_content_crash_presented",
        "http_page_dns_lookup_time",
        "http3_saved_dgrams",
        "gc_non_incremental_reason",
        "gc_slice_count",
        "dns_httpssvc_connection_failed_reason",
        "js_pageload_parse_ms",
        "gc_non_incremental",
        "network_async_open_to_transaction_pending_ms",
        "gc_in_progress_ms",
        "gc_is_compartmental",
        "devtools_inspector_opened_count",
        "timestamps_about_home_topsites_first_paint",
        "gc_effectiveness",
        "fog_validation_profile_disk_is_ssd",
        "cycle_collector_worker_visited_gced",
        "gc_minor_us",
        "metrics_has_recent_pwas",
        "browser_engagement_mirror_for_uri_count",
        "contextual_services_quicksuggest_block_sponsored_bestmatch",
        "dns_trr_success3",
        "use_counter2_documentexeccommandcontentreadonly_page",
        "fx_tab_switch_spinner_visible_ms",
        "fx_migration_source_browser",
        "fx_tab_switch_spinner_visible_long_ms",
        "addresses_deleted",
        "contentblocking_trackers_blocked_count",
        "networking_nss_initialization",
        "use_counter2_deprecated_mozcurrenttransform_document",
        "startup_run_from_dmg_install_outcome",
        "addon_signature_verification_status",
        "use_counter2_scheduler_posttask_page",
        "logins_store_write_query_count",
        "engine_tab_kill_foreground_age",
        "storage_stats_data_dir_bytes",
        "service_worker_launch_time_2",
        "preferences_signed_in_sync",
        "update_ping_count_subsequent",
        "power_cpu_ms_per_thread_gpu_process",
        "search_service_init_ms",
        "cookie_retrieval_samesite_problem",
        "network_cache_metadata_first_read_time_ms",
        "metrics_has_top_sites",
        "use_counter2_element_sethtml_document",
        "input_event_response_ms",
        "fx_lazyload_image_page_load_ms",
        "use_counter2_documentquerycommandstateorvalueinsertbronreturn_page",
        "http3_loss_ratio",
        "use_counter2_documentquerycommandsupportedorenabledcontentreadonly_page",
        "fx_refresh_driver_content_frame_delay_ms",
        "fx_page_reload_skip_cache_ms",
        "time_to_load_event_end_ms",
        "http3_late_ack",
        "places_idle_maintenance_time_ms",
        "http_page_dns_issue_time",
        "http3_0rtt_state_duration",
        "update_no_window_auto_restarts",
        "contextual_services_quicksuggest_block_nonsponsored",
        "tls_early_data_bytes_written",
        "browser_attribution_errors",
        "update_download_code_unknown",
        "contextual_services_quicksuggest_click",
        "image_decode_speed_webp",
        "http3_0rtt_state",
        "browser_link_open_newwindow_restriction",
        "content_process_count",
        "predictor_total_preconnects_created",
        "startup_timeline_framework_start_read_error",
        "a11y_isimpledom_usage_flag",
        "master_password_enabled",
        "performance_pageload_req_anim_frame_callback",
        "service_worker_fetch_event_finish_synthesized_response_ms_2",
        "time_to_load_event_start_ms",
        "eh_final_response",
        "timestamps_first_paint",
        "gc_slow_task",
        "android_sdk_version",
        "perf_awesomebar_search_engine_suggestions",
        "places_tags_count",
        "metrics_search_count",
        "startup_timeline_framework_secondary",
        "use_counter2_documentexeccommanddecreasefontsize_document",
        "http3_counts_pto",
        "startup_timeline_clock_ticks_per_second_v2",
        "urlclassifier_cl_check_time",
        "use_counter2_sanitizer_constructor_document",
        "wr_gpu_wait_time",
        "search_counts",
        "dns_renewal_time_for_ttl",
        "migration_settings_total_duration",
        "lazyload_image_viewport_loaded",
        "telemetry_event_recording_error",
        "perf_startup_app_on_create_to_setup_in_main",
        "http_subitem_first_byte_latency_time",
        "startup_crash_detected",
        "cycle_collector_worker_oom",
        "use_counter2_documentexeccommandheading_page",
        "gc_slow_phase",
        "predictor_total_preconnects",
        "perf_startup_application_on_create",
        "use_counter2_element_sethtml_page",
        "gc_tenured_survival_rate",
        "use_counter2_onstart_document",
        "checkerboard_severity",
        "update_cannot_stage_notify",
        "a11y_tree_update_timing_ms",
        "telemetry_archive_checking_over_quota_ms",
        "network_async_open_child_to_transaction_pending_ms",
        "weave_device_count_desktop",
        "urlclassifier_vlps_fileload_time",
        "android_autofill_supported",
        "use_counter2_window_absoluteorientationsensor_document",
        "places_database_size_per_page_b",
        "urlclassifier_update_server_response_time",
        "update_notification_main_action_menu",
        "transaction_wait_time_http",
        "image_decode_time",
        "devtools_webconsole_time_active_seconds",
        "spdy_chunk_recvd",
        "http_request_per_page",
        "startup_timeline_clock_ticks_per_second",
        "gc_max_pause_ms_2",
        "perf_startup_home_activity_on_start",
        "sqlite_store_open",
        "blocklist_mlbf_generation_time",
        "devtools_storage_opened_count",
        "subprocess_kill_hard",
        "js_pageload_execution_ms",
        "use_counter2_sanitizer_sanitize_page",
        "places_pages_count",
        "migration_open_tabs_total_duration",
        "a11y_theme",
        "trr_attempt_count",
        "http_page_tls_handshake",
        "h3p_perf_page_load_time_ms",
        "metrics_default_wallpaper",
        "cycle_collector_visited_ref_counted",
        "browser_search_adclicks_contextmenu",
        "ssl_handshake_result_first_try",
        "update_pref_service_errors_subsequent",
        "osfile_worker_ready_ms",
        "home_screen_home_screen_view_count",
        "customize_home_opening_screen",
        "gc_mmu_50",
        "blocklist_use_xml",
        "use_counter2_window_performanceeventtiming_document",
        "webrtc_h264_enabled",
        "use_counter2_privatebrowsingcachesdelete_document",
        "sandbox_failed_launch_keyed",
        "gc_budget_ms",
        "metrics.search_widget_installed",
        "dns_lookup_disposition3",
        "http3_upload_time_10m_100m",
        "content_documents_destroyed",
        "performance_pageload_dcl_responsestart",
        "glean_error_invalid_state",
        "checkerboard_potential_duration",
        "use_counter2_css_property_all_document",
        "page_load_error",
        "webrtc_video_quality_outbound_packetloss_rate",
        "glean_time_invalid_timezone_offset",
        "transaction_wait_time_http3",
        "storage_stats_query_stats_duration",
        "performance_time_load_event_start_preload",
        "use_counter2_documentquerycommandsupportedorenabledheading_page",
        "media_decoder_backend_used",
        "browser_engagement_profile_count",
        "paint_build_displaylist_time",
        "cycle_collector_max_pause",
        "devtools_accessibility_simulation_activated",
        "system_font_fallback",
        "recent_synced_tabs_recent_synced_tab_time_to_load",
        "fx_page_load_ms_2",
        "localdomstorage_clear_blocking_ms",
        "urlbar_picked_searchmode_bookmarkmenu",
        "fennec_bookmarks_count",
        "glean_core_migration_successful",
        "performance_time_response_start",
        "use_counter2_sanitizer_sanitize_document",
        "tls_early_data_negotiated",
        "http_page_cache_read_time_v2",
        "performance_time_load_event_start",
        "tls_early_data_accepted",
        "http_child_omt_stats",
        "use_counter2_window_webkitspeechrecognitionevent_document",
        "wallpapers_discovered_wallpaper_feature",
        "http_sub_complete_load_net_v2",
        "glean_upload_deleted_pings_after_quota_hit",
        "geckoview_startup_runtime",
        "serviceworker_registrations",
        "http_09_info",
        "pdf_viewer_document_generator",
        "seq",
        "http_saw_quic_alt_protocol_2",
        "memory_js_gc_heap",
        "performance_time_load_event_start_no_preload",
        "pwmgr_num_saved_passwords",
        "pdf_viewer_print",
        "js_pageload_gc_ms",
        "engine_kill_background_age",
        "performance_time_load_event_end_preload",
        "js_pageload_xdr_encoding_ms",
        "http_page_complete_load_net",
        "memory_storage_sqlite",
        "transaction_wait_time_spdy",
        "contextual_services_quicksuggest_click_sponsored_bestmatch",
        "service_worker_fetch_interception_duration_ms_2",
        "ssl_handshake_result_ech_grease",
        "js_pageload_protect_ms",
        "webrtc_call_type",
        "use_counter2_deprecated_windowcontentuntrusted_document",
        "js_pageload_delazification_ms",
        "http3_tls_handshake",
        "avif_a1lx",
        "video_clearkey_play_time_ms",
        "fog_validation_legacy_telemetry_client_id",
        "use_counter2_appearance_nonwidget_button_document",
        "glean_baseline_locale",
        "http3_request_per_conn",
        "wr_time_to_frame_build_ms",
        "sqlite_store_query",
        "update_check_code_subsequent",
        "customize_home_most_visited_sites",
        "deletion_request_context_id",
        "use_counter2_deprecated_idbdatabasecreatemutablefile_page",
        "glean_error_preinit_tasks_overflow",
        "text_recognition_interaction_timing",
        "contextual_services_topsites_impression",
        "device_manufacturer",
        "privacy_globalprivacycontrol_functionality_was_ever_enabled",
        "cycle_collector_slice_during_idle",
        "performance_time_dom_content_loaded_start",
        "contextual_services_quicksuggest_click_nonsponsored_bestmatch",
        "network_response_start_parent_to_content_ms",
        "use_counter2_deprecated_windowcontentuntrusted_page",
        "webext_storage_local_idb_set_ms",
        "avif_cicp_cp",
        "fog_ipc_flush_durations",
        "gfx_adapter_primary_device_id",
        "glean_upload_discarded_exceeding_pings_size",
        "engine_tab_kills",
        "privacy_globalprivacycontrol_functionality_enabled",
        "http3_drop_dgrams",
        "gc_minor_reason",
        "serviceworker_running_max",
        "experiments",
        "use_counter2_windowopenemptyurl_page",
        "contextual_services_quicksuggest_help",
        "blocklist_mlbf_enabled",
        "avif_cicp_mc",
        "bfcache_combo",
        "browser_engagement_total_uri_count_normal_and_private_mode",
        "glean_validation_metrics_ping_count",
        "fx_tab_switch_total_e10s_ms",
        "media_hls_canplay_requested",
        "webrtc_max_video_send_track",
        "load_input_event_response_ms",
        "total_content_page_load_time",
        "telemetry_sdk_build",
        "wr_time_to_render_start",
        "recent_synced_tabs_recent_synced_tab_shown",
        "storage_stats_app_bytes",
        "lazyload_image_total",
        "performance_page_total_content_page_load",
        "urlbar_picked_searchmode_keywordoffer",
        "fog_ipc_shutdown_registration_failures",
        "fog_ipc_flush_failures",
        "logins_store_unlock_time",
        "device_model",
        "lazyload_image_viewport_loading",
        "perf_startup_startup_type",
        "content_process_max",
        "performance_time_dom_content_loaded_end",
        "fx_refresh_driver_sync_scroll_frame_delay_ms",
        "http_request_per_page_from_cache",
        "memory_vsize",
        "http_channel_onstart_success",
        "time_to_load_event_start_preload_ms",
        "search_service_us_timezone_mismatched_country",
        "h3p_perf_first_contentful_paint_ms",
        "gfx_checkerboard_duration",
        "glean_validation_first_run_hour",
        "browser_ui_interaction_textrecognition_error",
        "performance_pageload_dcl",
        "search_terms_group_size_distribution",
        "performance_time_dom_complete",
        "lazyload_image_started",
        "glean_error_invalid_value",
        "contextual_services_quicksuggest_block_sponsored",
    ]


def get_most_used_probes():
    """Fetch and provide probes that have been used lately in Glam.

    Important: The API does not distinguish from different products (e.g.: fenix, desktop),
    so make sure the list of probes from this function goes through a filter
    to avoid computing probes for a different product.
    """
    # Temporarily returning a list of hardcoded probes, for testing
    return temp_hardcoded_most_used_probes()
    """
    from_date = (date.today() - relativedelta(months=3)).strftime("%Y%m%d")
    url_req = Request(
        f"{GLAM_USAGE_SERVICE}?fromDate={from_date}&fields=probe_name&actionType=PROBE_SEARCH&agg=count",
        None,
        {

        },
    )
    probe_names = []
    with urlopen(url_req) as url:
        data_str = gzip.decompress(url.read()).decode()
        data = json.loads(data_str)
        probe_names = [entry["probe_name"] for entry in data]

    return probe_names
    """


def probe_is_recent_legacy(probe_data):
    """Check probe data and returns if probe was created in the last RECENT_PROBE_DAYS."""
    # Temporarily return false in favor of hardcoded list of recently used probes
    return False
    """
    probe_created_on = datetime.strptime(
        probe_data["first_added"]["nightly"], "%Y-%m-%d %H:%M:%S"
    )
    return (datetime.now() - probe_created_on).days <= RECENT_PROBE_DAYS
    """


def probe_is_recent_glean(probe, product):
    """Return whether probe was created in the last 90 days."""
    # Temporarily return false in favor of hardcoded list of recently used probes
    return False
    """
    product_map = {
        "firefox_desktop": "firefox_desktop",
        "org_mozilla_fenix": "fenix",
    }

    if product not in product_map.keys():
        raise Exception(f"Product not supported: {product}")

    product_path = product_map[product]
    domain = "https://dictionary.telemetry.mozilla.org"
    url = f"{domain}/data/{product_path}/metrics/data_{probe}.json"
    url_req = Request(url)

    with urlopen(url_req) as url:
        data = json.loads(url.read())
        probe_created_on = datetime.strptime(
            data["date_first_seen"], "%Y-%m-%d %H:%M:%S"
        )

    return (datetime.now() - probe_created_on).days <= RECENT_PROBE_DAYS
    """
