CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.telemetry.normandy_login_study`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.telemetry_stable.normandy_login_study_v4`
