-- Generated via bigquery_etl.glean_usage
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.org_mozilla_ios_firefoxbeta.events_stream`
AS
SELECT
  *,
  STRUCT(
    STRUCT(
      LAX_BOOL(event_extra.agreed) AS `agreed`,
      LAX_BOOL(event_extra.changed_to) AS `changed_to`,
      LAX_BOOL(event_extra.did_confirm) AS `did_confirm`,
      LAX_BOOL(event_extra.enabled) AS `enabled`,
      LAX_BOOL(event_extra.etp_enabled) AS `etp_enabled`,
      LAX_BOOL(event_extra.granted) AS `granted`,
      LAX_BOOL(event_extra.has_share_message) AS `has_share_message`,
      LAX_BOOL(event_extra.is_enabled) AS `is_enabled`,
      LAX_BOOL(event_extra.is_enrolled_in_sent_from_firefox) AS `is_enrolled_in_sent_from_firefox`,
      LAX_BOOL(event_extra.is_homepage) AS `is_homepage`,
      LAX_BOOL(event_extra.is_opted_in_sent_from_firefox) AS `is_opted_in_sent_from_firefox`,
      LAX_BOOL(event_extra.is_private) AS `is_private`,
      LAX_BOOL(event_extra.is_private_mode) AS `is_private_mode`,
      LAX_BOOL(event_extra.is_toolbar) AS `is_toolbar`,
      LAX_BOOL(event_extra.outcome) AS `outcome`
    ) AS `boolean`,
    STRUCT(
      LAX_INT64(event_extra.average_tabs_in_all_groups) AS `average_tabs_in_all_groups`,
      LAX_INT64(event_extra.consecutive_crash) AS `consecutive_crash`,
      LAX_INT64(event_extra.groups_two_tabs_only) AS `groups_two_tabs_only`,
      LAX_INT64(event_extra.groups_with_more_than_two_tab) AS `groups_with_more_than_two_tab`,
      LAX_INT64(event_extra.index) AS `index`,
      LAX_INT64(event_extra.length_chars) AS `length_chars`,
      LAX_INT64(event_extra.length_words) AS `length_words`,
      LAX_INT64(event_extra.level) AS `level`,
      LAX_INT64(event_extra.n_chars) AS `n_chars`,
      LAX_INT64(event_extra.n_results) AS `n_results`,
      LAX_INT64(event_extra.n_words) AS `n_words`,
      LAX_INT64(event_extra.position) AS `position`,
      LAX_INT64(event_extra.selected_tab_index) AS `selected_tab_index`,
      LAX_INT64(event_extra.size) AS `size`,
      LAX_INT64(event_extra.total_num_of_groups) AS `total_num_of_groups`,
      LAX_INT64(event_extra.total_tabs_in_all_groups) AS `total_tabs_in_all_groups`
    ) AS `quantity`,
    STRUCT(
      JSON_VALUE(event_extra.action) AS `action`,
      JSON_VALUE(event_extra.action_uuid) AS `action_uuid`,
      JSON_VALUE(event_extra.activity_identifier) AS `activity_identifier`,
      JSON_VALUE(event_extra.alert_setting) AS `alert_setting`,
      JSON_VALUE(event_extra.bookmark_count) AS `bookmark_count`,
      JSON_VALUE(event_extra.branch) AS `branch`,
      JSON_VALUE(event_extra.button_action) AS `button_action`,
      JSON_VALUE(event_extra.card_type) AS `card_type`,
      JSON_VALUE(event_extra.changed_from) AS `changed_from`,
      JSON_VALUE(event_extra.changed_to) AS `changed_to`,
      JSON_VALUE(event_extra.conflict_slug) AS `conflict_slug`,
      JSON_VALUE(event_extra.connection_type) AS `connection_type`,
      JSON_VALUE(event_extra.disabled_engines) AS `disabled_engines`,
      JSON_VALUE(event_extra.enabled_engines) AS `enabled_engines`,
      JSON_VALUE(event_extra.engagement_type) AS `engagement_type`,
      JSON_VALUE(event_extra.enrollment_id) AS `enrollment_id`,
      JSON_VALUE(event_extra.error_code) AS `error_code`,
      JSON_VALUE(event_extra.error_string) AS `error_string`,
      JSON_VALUE(event_extra.error_type) AS `error_type`,
      JSON_VALUE(event_extra.etp_setting) AS `etp_setting`,
      JSON_VALUE(event_extra.experiment) AS `experiment`,
      JSON_VALUE(event_extra.experiment_type) AS `experiment_type`,
      JSON_VALUE(event_extra.feature_id) AS `feature_id`,
      JSON_VALUE(event_extra.flow_type) AS `flow_type`,
      JSON_VALUE(event_extra.groups) AS `groups`,
      JSON_VALUE(event_extra.hint_type) AS `hint_type`,
      JSON_VALUE(event_extra.interaction) AS `interaction`,
      JSON_VALUE(event_extra.is_accessibility_size_enabled) AS `is_accessibility_size_enabled`,
      JSON_VALUE(event_extra.is_enabled) AS `is_enabled`,
      JSON_VALUE(event_extra.is_private) AS `is_private`,
      JSON_VALUE(event_extra.is_running) AS `is_running`,
      JSON_VALUE(event_extra.location) AS `location`,
      JSON_VALUE(event_extra.media_type) AS `media_type`,
      JSON_VALUE(event_extra.message_key) AS `message_key`,
      JSON_VALUE(event_extra.message_surface) AS `message_surface`,
      JSON_VALUE(event_extra.mode) AS `mode`,
      JSON_VALUE(event_extra.model) AS `model`,
      JSON_VALUE(event_extra.new_name) AS `new_name`,
      JSON_VALUE(event_extra.old_name) AS `old_name`,
      JSON_VALUE(event_extra.option) AS `option`,
      JSON_VALUE(event_extra.origin) AS `origin`,
      JSON_VALUE(event_extra.part_id) AS `part_id`,
      JSON_VALUE(event_extra.period) AS `period`,
      JSON_VALUE(event_extra.position) AS `position`,
      JSON_VALUE(event_extra.preference) AS `preference`,
      JSON_VALUE(event_extra.preferred_size) AS `preferred_size`,
      JSON_VALUE(event_extra.provider) AS `provider`,
      JSON_VALUE(event_extra.reading_list_count) AS `reading_list_count`,
      JSON_VALUE(event_extra.reason) AS `reason`,
      JSON_VALUE(event_extra.received_url) AS `received_url`,
      JSON_VALUE(event_extra.results) AS `results`,
      JSON_VALUE(event_extra.sap) AS `sap`,
      JSON_VALUE(event_extra.search_mode) AS `search_mode`,
      JSON_VALUE(event_extra.section) AS `section`,
      JSON_VALUE(event_extra.selected_result) AS `selected_result`,
      JSON_VALUE(event_extra.selected_result_subtype) AS `selected_result_subtype`,
      JSON_VALUE(event_extra.sequence_id) AS `sequence_id`,
      JSON_VALUE(event_extra.sequence_position) AS `sequence_position`,
      JSON_VALUE(event_extra.setting) AS `setting`,
      JSON_VALUE(event_extra.share_type) AS `share_type`,
      JSON_VALUE(event_extra.size) AS `size`,
      JSON_VALUE(event_extra.slug) AS `slug`,
      JSON_VALUE(event_extra.source) AS `source`,
      JSON_VALUE(event_extra.status) AS `status`,
      JSON_VALUE(event_extra.surface) AS `surface`,
      JSON_VALUE(event_extra.survey_id) AS `survey_id`,
      JSON_VALUE(event_extra.tile_type) AS `tile_type`,
      JSON_VALUE(event_extra.timeframe) AS `timeframe`,
      JSON_VALUE(event_extra.toggle_type) AS `toggle_type`,
      JSON_VALUE(event_extra.tou_version) AS `tou_version`,
      JSON_VALUE(event_extra.trigger) AS `trigger`,
      JSON_VALUE(event_extra.type) AS `type`,
      JSON_VALUE(event_extra.user_selection) AS `user_selection`,
      JSON_VALUE(event_extra.wallpaper_name) AS `wallpaper_name`,
      JSON_VALUE(event_extra.wallpaper_type) AS `wallpaper_type`
    ) AS `string`
  ) AS extras
FROM
  `moz-fx-data-shared-prod.org_mozilla_ios_firefoxbeta_derived.events_stream_v1`
