fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: sample_id
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sample_id
- mode: NULLABLE
  name: client_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: client_id
- mode: NULLABLE
  name: profile_group_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: profile_group_id
- mode: NULLABLE
  name: os
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: os
- mode: NULLABLE
  name: app_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_version
- mode: NULLABLE
  name: app_build_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_build_id
- mode: NULLABLE
  name: channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel
- fields:
  - mode: NULLABLE
    name: metric
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: metric
  - mode: NULLABLE
    name: metric_type
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: metric_type
  - mode: NULLABLE
    name: key
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: key
  - mode: NULLABLE
    name: process
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: process
  - mode: NULLABLE
    name: agg_type
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: agg_type
  - mode: NULLABLE
    name: value
    type: FLOAT
    description: The aggregated scalar value computed according to agg_type for this metric on the submission date.
  mode: REPEATED
  name: scalar_aggregates
  type: RECORD
