fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: update_channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: update_channel
- mode: NULLABLE
  name: installer_type
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: installer_type
- mode: NULLABLE
  name: install_count
  type: INTEGER
  description: Install Count
