-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.firefox_reality.session_end`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.org_mozilla_vrbrowser.session_end`
