CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.firefox_installer.install`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.firefox_installer_stable.install_v1`
