-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.firefox_ios.temp_history_sync`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.org_mozilla_ios_firefox.temp_history_sync`
