-- Generated via ./bqetl generate glean_usage
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.focus_android.captcha_detection`
AS
SELECT
  "org_mozilla_focus" AS normalized_app_id,
  "release" AS normalized_channel,
  additional_properties,
  client_info,
  document_id,
  events,
  metadata,
  STRUCT(
    STRUCT(
      metrics.boolean.captcha_detection_network_cookie_cookiebehavior_optinpartitioning,
      metrics.boolean.captcha_detection_network_cookie_cookiebehavior_optinpartitioning_pbm,
      metrics.boolean.captcha_detection_privacy_fingerprintingprotection,
      metrics.boolean.captcha_detection_privacy_fingerprintingprotection_pbm,
      metrics.boolean.captcha_detection_privacy_resistfingerprinting,
      metrics.boolean.captcha_detection_privacy_resistfingerprinting_pbmode,
      metrics.boolean.captcha_detection_privacy_trackingprotection_cryptomining_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_fingerprinting_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_pbm_enabled
    ) AS `boolean`,
    STRUCT(
      metrics.counter.captcha_detection_arkoselabs_pc,
      metrics.counter.captcha_detection_arkoselabs_pc_pbm,
      metrics.counter.captcha_detection_arkoselabs_pf,
      metrics.counter.captcha_detection_arkoselabs_pf_pbm,
      metrics.counter.captcha_detection_arkoselabs_ps,
      metrics.counter.captcha_detection_arkoselabs_ps_pbm,
      metrics.counter.captcha_detection_awswaf_pc,
      metrics.counter.captcha_detection_awswaf_pc_pbm,
      metrics.counter.captcha_detection_awswaf_pf,
      metrics.counter.captcha_detection_awswaf_pf_pbm,
      metrics.counter.captcha_detection_awswaf_ps,
      metrics.counter.captcha_detection_awswaf_ps_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_cc,
      metrics.counter.captcha_detection_cloudflare_turnstile_cc_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_cf,
      metrics.counter.captcha_detection_cloudflare_turnstile_cf_pbm,
      metrics.counter.captcha_detection_datadome_bl,
      metrics.counter.captcha_detection_datadome_bl_pbm,
      metrics.counter.captcha_detection_datadome_pc,
      metrics.counter.captcha_detection_datadome_pc_pbm,
      metrics.counter.captcha_detection_datadome_ps,
      metrics.counter.captcha_detection_datadome_ps_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_ac,
      metrics.counter.captcha_detection_google_recaptcha_v2_ac_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_pc,
      metrics.counter.captcha_detection_google_recaptcha_v2_pc_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_ps,
      metrics.counter.captcha_detection_google_recaptcha_v2_ps_pbm,
      metrics.counter.captcha_detection_hcaptcha_ac,
      metrics.counter.captcha_detection_hcaptcha_ac_pbm,
      metrics.counter.captcha_detection_hcaptcha_pc,
      metrics.counter.captcha_detection_hcaptcha_pc_pbm,
      metrics.counter.captcha_detection_hcaptcha_ps,
      metrics.counter.captcha_detection_hcaptcha_ps_pbm,
      metrics.counter.captcha_detection_pages_visited,
      metrics.counter.captcha_detection_pages_visited_pbm,
      metrics.counter.captcha_detection_arkoselabs_oc,
      metrics.counter.captcha_detection_arkoselabs_oc_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_oc,
      metrics.counter.captcha_detection_cloudflare_turnstile_oc_pbm,
      metrics.counter.captcha_detection_datadome_oc,
      metrics.counter.captcha_detection_google_recaptcha_v2_oc,
      metrics.counter.captcha_detection_google_recaptcha_v2_oc_pbm,
      metrics.counter.captcha_detection_hcaptcha_oc,
      metrics.counter.captcha_detection_hcaptcha_oc_pbm
    ) AS `counter`,
    STRUCT(
      metrics.custom_distribution.captcha_detection_arkoselabs_solutions_required,
      metrics.custom_distribution.captcha_detection_arkoselabs_solutions_required_pbm,
      metrics.custom_distribution.captcha_detection_awswaf_solutions_required,
      metrics.custom_distribution.captcha_detection_awswaf_solutions_required_pbm
    ) AS `custom_distribution`,
    STRUCT(
      metrics.labeled_counter.glean_error_invalid_label,
      metrics.labeled_counter.glean_error_invalid_overflow,
      metrics.labeled_counter.glean_error_invalid_state,
      metrics.labeled_counter.glean_error_invalid_value
    ) AS `labeled_counter`,
    STRUCT(
      metrics.string.captcha_detection_network_cookie_cookiebehavior,
      metrics.string.glean_client_annotation_experimentation_id
    ) AS `string`
  ) AS `metrics`,
  normalized_app_name,
  normalized_country_code,
  normalized_os,
  normalized_os_version,
  ping_info,
  sample_id,
  submission_timestamp,
  app_version_major,
  app_version_minor,
  app_version_patch
FROM
  `moz-fx-data-shared-prod.org_mozilla_focus.captcha_detection`
UNION ALL
SELECT
  "org_mozilla_focus_beta" AS normalized_app_id,
  "beta" AS normalized_channel,
  additional_properties,
  client_info,
  document_id,
  events,
  metadata,
  STRUCT(
    STRUCT(
      metrics.boolean.captcha_detection_network_cookie_cookiebehavior_optinpartitioning,
      metrics.boolean.captcha_detection_network_cookie_cookiebehavior_optinpartitioning_pbm,
      metrics.boolean.captcha_detection_privacy_fingerprintingprotection,
      metrics.boolean.captcha_detection_privacy_fingerprintingprotection_pbm,
      metrics.boolean.captcha_detection_privacy_resistfingerprinting,
      metrics.boolean.captcha_detection_privacy_resistfingerprinting_pbmode,
      metrics.boolean.captcha_detection_privacy_trackingprotection_cryptomining_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_fingerprinting_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_pbm_enabled
    ) AS `boolean`,
    STRUCT(
      metrics.counter.captcha_detection_arkoselabs_pc,
      metrics.counter.captcha_detection_arkoselabs_pc_pbm,
      metrics.counter.captcha_detection_arkoselabs_pf,
      metrics.counter.captcha_detection_arkoselabs_pf_pbm,
      metrics.counter.captcha_detection_arkoselabs_ps,
      metrics.counter.captcha_detection_arkoselabs_ps_pbm,
      metrics.counter.captcha_detection_awswaf_pc,
      metrics.counter.captcha_detection_awswaf_pc_pbm,
      metrics.counter.captcha_detection_awswaf_pf,
      metrics.counter.captcha_detection_awswaf_pf_pbm,
      metrics.counter.captcha_detection_awswaf_ps,
      metrics.counter.captcha_detection_awswaf_ps_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_cc,
      metrics.counter.captcha_detection_cloudflare_turnstile_cc_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_cf,
      metrics.counter.captcha_detection_cloudflare_turnstile_cf_pbm,
      metrics.counter.captcha_detection_datadome_bl,
      metrics.counter.captcha_detection_datadome_bl_pbm,
      metrics.counter.captcha_detection_datadome_pc,
      metrics.counter.captcha_detection_datadome_pc_pbm,
      metrics.counter.captcha_detection_datadome_ps,
      metrics.counter.captcha_detection_datadome_ps_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_ac,
      metrics.counter.captcha_detection_google_recaptcha_v2_ac_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_pc,
      metrics.counter.captcha_detection_google_recaptcha_v2_pc_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_ps,
      metrics.counter.captcha_detection_google_recaptcha_v2_ps_pbm,
      metrics.counter.captcha_detection_hcaptcha_ac,
      metrics.counter.captcha_detection_hcaptcha_ac_pbm,
      metrics.counter.captcha_detection_hcaptcha_pc,
      metrics.counter.captcha_detection_hcaptcha_pc_pbm,
      metrics.counter.captcha_detection_hcaptcha_ps,
      metrics.counter.captcha_detection_hcaptcha_ps_pbm,
      metrics.counter.captcha_detection_pages_visited,
      metrics.counter.captcha_detection_pages_visited_pbm,
      metrics.counter.captcha_detection_arkoselabs_oc,
      metrics.counter.captcha_detection_arkoselabs_oc_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_oc,
      metrics.counter.captcha_detection_cloudflare_turnstile_oc_pbm,
      metrics.counter.captcha_detection_datadome_oc,
      metrics.counter.captcha_detection_google_recaptcha_v2_oc,
      metrics.counter.captcha_detection_google_recaptcha_v2_oc_pbm,
      metrics.counter.captcha_detection_hcaptcha_oc,
      metrics.counter.captcha_detection_hcaptcha_oc_pbm
    ) AS `counter`,
    STRUCT(
      metrics.custom_distribution.captcha_detection_arkoselabs_solutions_required,
      metrics.custom_distribution.captcha_detection_arkoselabs_solutions_required_pbm,
      metrics.custom_distribution.captcha_detection_awswaf_solutions_required,
      metrics.custom_distribution.captcha_detection_awswaf_solutions_required_pbm
    ) AS `custom_distribution`,
    STRUCT(
      metrics.labeled_counter.glean_error_invalid_label,
      metrics.labeled_counter.glean_error_invalid_overflow,
      metrics.labeled_counter.glean_error_invalid_state,
      metrics.labeled_counter.glean_error_invalid_value
    ) AS `labeled_counter`,
    STRUCT(
      metrics.string.captcha_detection_network_cookie_cookiebehavior,
      metrics.string.glean_client_annotation_experimentation_id
    ) AS `string`
  ) AS `metrics`,
  normalized_app_name,
  normalized_country_code,
  normalized_os,
  normalized_os_version,
  ping_info,
  sample_id,
  submission_timestamp,
  app_version_major,
  app_version_minor,
  app_version_patch
FROM
  `moz-fx-data-shared-prod.org_mozilla_focus_beta.captcha_detection`
UNION ALL
SELECT
  "org_mozilla_focus_nightly" AS normalized_app_id,
  "nightly" AS normalized_channel,
  additional_properties,
  STRUCT(
    client_info.android_sdk_version,
    client_info.app_build,
    client_info.app_channel,
    client_info.app_display_version,
    client_info.architecture,
    client_info.build_date,
    client_info.client_id,
    client_info.device_manufacturer,
    client_info.device_model,
    client_info.first_run_date,
    client_info.locale,
    client_info.os,
    client_info.os_version,
    client_info.session_count,
    client_info.session_id,
    client_info.telemetry_sdk_build,
    client_info.windows_build_number,
    STRUCT(
      client_info.attribution.campaign,
      client_info.attribution.content,
      client_info.attribution.medium,
      client_info.attribution.source,
      client_info.attribution.term,
      CAST(NULL AS JSON) AS `ext`
    ) AS `attribution`,
    STRUCT(client_info.distribution.name, CAST(NULL AS JSON) AS `ext`) AS `distribution`
  ) AS `client_info`,
  document_id,
  events,
  metadata,
  STRUCT(
    STRUCT(
      metrics.boolean.captcha_detection_network_cookie_cookiebehavior_optinpartitioning,
      metrics.boolean.captcha_detection_network_cookie_cookiebehavior_optinpartitioning_pbm,
      metrics.boolean.captcha_detection_privacy_fingerprintingprotection,
      metrics.boolean.captcha_detection_privacy_fingerprintingprotection_pbm,
      metrics.boolean.captcha_detection_privacy_resistfingerprinting,
      metrics.boolean.captcha_detection_privacy_resistfingerprinting_pbmode,
      metrics.boolean.captcha_detection_privacy_trackingprotection_cryptomining_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_fingerprinting_enabled,
      metrics.boolean.captcha_detection_privacy_trackingprotection_pbm_enabled
    ) AS `boolean`,
    STRUCT(
      metrics.counter.captcha_detection_arkoselabs_pc,
      metrics.counter.captcha_detection_arkoselabs_pc_pbm,
      metrics.counter.captcha_detection_arkoselabs_pf,
      metrics.counter.captcha_detection_arkoselabs_pf_pbm,
      metrics.counter.captcha_detection_arkoselabs_ps,
      metrics.counter.captcha_detection_arkoselabs_ps_pbm,
      metrics.counter.captcha_detection_awswaf_pc,
      metrics.counter.captcha_detection_awswaf_pc_pbm,
      metrics.counter.captcha_detection_awswaf_pf,
      metrics.counter.captcha_detection_awswaf_pf_pbm,
      metrics.counter.captcha_detection_awswaf_ps,
      metrics.counter.captcha_detection_awswaf_ps_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_cc,
      metrics.counter.captcha_detection_cloudflare_turnstile_cc_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_cf,
      metrics.counter.captcha_detection_cloudflare_turnstile_cf_pbm,
      metrics.counter.captcha_detection_datadome_bl,
      metrics.counter.captcha_detection_datadome_bl_pbm,
      metrics.counter.captcha_detection_datadome_pc,
      metrics.counter.captcha_detection_datadome_pc_pbm,
      metrics.counter.captcha_detection_datadome_ps,
      metrics.counter.captcha_detection_datadome_ps_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_ac,
      metrics.counter.captcha_detection_google_recaptcha_v2_ac_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_pc,
      metrics.counter.captcha_detection_google_recaptcha_v2_pc_pbm,
      metrics.counter.captcha_detection_google_recaptcha_v2_ps,
      metrics.counter.captcha_detection_google_recaptcha_v2_ps_pbm,
      metrics.counter.captcha_detection_hcaptcha_ac,
      metrics.counter.captcha_detection_hcaptcha_ac_pbm,
      metrics.counter.captcha_detection_hcaptcha_pc,
      metrics.counter.captcha_detection_hcaptcha_pc_pbm,
      metrics.counter.captcha_detection_hcaptcha_ps,
      metrics.counter.captcha_detection_hcaptcha_ps_pbm,
      metrics.counter.captcha_detection_pages_visited,
      metrics.counter.captcha_detection_pages_visited_pbm,
      metrics.counter.captcha_detection_arkoselabs_oc,
      metrics.counter.captcha_detection_arkoselabs_oc_pbm,
      metrics.counter.captcha_detection_cloudflare_turnstile_oc,
      metrics.counter.captcha_detection_cloudflare_turnstile_oc_pbm,
      metrics.counter.captcha_detection_datadome_oc,
      metrics.counter.captcha_detection_google_recaptcha_v2_oc,
      metrics.counter.captcha_detection_google_recaptcha_v2_oc_pbm,
      metrics.counter.captcha_detection_hcaptcha_oc,
      metrics.counter.captcha_detection_hcaptcha_oc_pbm
    ) AS `counter`,
    STRUCT(
      metrics.custom_distribution.captcha_detection_arkoselabs_solutions_required,
      metrics.custom_distribution.captcha_detection_arkoselabs_solutions_required_pbm,
      metrics.custom_distribution.captcha_detection_awswaf_solutions_required,
      metrics.custom_distribution.captcha_detection_awswaf_solutions_required_pbm
    ) AS `custom_distribution`,
    STRUCT(
      metrics.labeled_counter.glean_error_invalid_label,
      metrics.labeled_counter.glean_error_invalid_overflow,
      metrics.labeled_counter.glean_error_invalid_state,
      metrics.labeled_counter.glean_error_invalid_value
    ) AS `labeled_counter`,
    STRUCT(
      metrics.string.captcha_detection_network_cookie_cookiebehavior,
      metrics.string.glean_client_annotation_experimentation_id
    ) AS `string`
  ) AS `metrics`,
  normalized_app_name,
  normalized_country_code,
  normalized_os,
  normalized_os_version,
  ping_info,
  sample_id,
  submission_timestamp,
  app_version_major,
  app_version_minor,
  app_version_patch
FROM
  `moz-fx-data-shared-prod.org_mozilla_focus_nightly.captcha_detection`
