CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.telemetry.xfocsp_error_report`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.telemetry_stable.xfocsp_error_report_v4`
