SELECT
  plan_id,
  status,
  customer_start_date,
  subscription_start_date,
  canceled_at,
  cancel_at,
  cancel_at_period_end,
  ended_at,
  end_date,
  country,
  country_name,
  user_registration_date,
  referrer,
  utm_medium,
  utm_source,
  utm_content,
  utm_campaign,
  attribution_category,
  coarse_attribution_category,
  provider,
  plan_amount,
  billing_scheme,
  plan_currency,
  plan_interval,
  product_id,
  pricing_plan,
  product_name,
  normalized_medium,
  normalized_source,
  normalized_campaign,
  normalized_content,
  normalized_acquisition_channel,
  `date`,
  website_channel_group,
  COUNT(DISTINCT customer_id) AS customers,
  COUNT(DISTINCT subscription_id) AS subscriptions,
FROM
  all_subscriptions_v1
CROSS JOIN
  UNNEST(
    GENERATE_DATE_ARRAY(
      DATE(subscription_start_date),
      -- GENERATE_DATE_ARRAY is inclusive and subscriptions are not active on the end_date
      DATE(end_date) - 1
    )
  ) AS `date`
WHERE
  (`date` BETWEEN "2020-07-01" AND CURRENT_DATE - 1)
GROUP BY
  plan_id,
  status,
  customer_start_date,
  subscription_start_date,
  canceled_at,
  cancel_at,
  cancel_at_period_end,
  ended_at,
  end_date,
  country,
  country_name,
  user_registration_date,
  referrer,
  utm_medium,
  utm_source,
  utm_content,
  utm_campaign,
  attribution_category,
  coarse_attribution_category,
  provider,
  plan_amount,
  billing_scheme,
  plan_currency,
  plan_interval,
  product_id,
  pricing_plan,
  product_name,
  normalized_medium,
  normalized_source,
  normalized_campaign,
  normalized_content,
  normalized_acquisition_channel,
  `date`,
  website_channel_group
