-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.fenix.addresses_sync`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.org_mozilla_firefox.addresses_sync`
