fields:

- name: submission_date
  mode: NULLABLE
  type: DATE
  description: |-
    Logical date processed, also used for partitioning.

- name: activity_unix_timestamp
  mode: NULLABLE
  type: INTEGER
  description: activity_date in UNIX seconds.

- name: fbc
  mode: NULLABLE
  type: STRING
  description: |-
    Formatted fbc (expected format: fb.subdomain_index.creation_time.fbclid).

- name: conversion_name
  mode: NULLABLE
  type: STRING
  description: Conversion name.

- name: run_timestamp
  mode: NULLABLE
  type: TIMESTAMP
  description: Timestamp when the job run.
