fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- name: release_channel_stub_installs_count
  type: INTEGER
  mode: NULLABLE
  description: Count of release channel stub installs
- name: uninstalls_count
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: uninstalls_count
- name: uninstall_to_install_ratio
  type: FLOAT
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: uninstall_to_install_ratio
