fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: usage
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: usage
- mode: NULLABLE
  name: id_bucket
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: id_bucket
- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: country
- mode: NULLABLE
  name: locale
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: locale
- mode: NULLABLE
  name: os
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: os
- mode: NULLABLE
  name: channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel
- mode: NULLABLE
  name: attributed
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attributed
- name: metrics
  type: RECORD
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: metrics
  fields:
  - name: day_0
    type: RECORD
    mode: NULLABLE
    description: Day 0
    fields:
    - name: dau
      type: INTEGER
      mode: NULLABLE
      description: !include-field-description
        file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
        field: dau
    - name: wau
      type: INTEGER
      mode: NULLABLE
      description: !include-field-description
        file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
        field: wau
    - name: mau
      type: INTEGER
      mode: NULLABLE
      description: !include-field-description
        file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
        field: mau
    - name: active_days_in_week
      type: INTEGER
      mode: NULLABLE
      description: Active Days in Week
  - name: day_6
    type: RECORD
    mode: NULLABLE
    description: Day 6
    fields:
    - name: new_profiles
      type: INTEGER
      mode: NULLABLE
      description: !include-field-description
        file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
        field: new_profiles
  - name: day_13
    type: RECORD
    mode: NULLABLE
    description: Day 13
    fields:
    - name: new_profiles
      type: INTEGER
      mode: NULLABLE
      description: !include-field-description
        file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
        field: new_profiles
    - name: active_in_week_0
      type: INTEGER
      mode: NULLABLE
      description: Active in Week 0
    - name: active_in_week_1
      type: INTEGER
      mode: NULLABLE
      description: Active in Week 1
    - name: active_in_weeks_0_and_1
      type: INTEGER
      mode: NULLABLE
      description: Active in Weeks 0 and 1
    - name: new_profile_active_in_week_0
      type: INTEGER
      mode: NULLABLE
      description: New Profile Active in Week 0
    - name: new_profile_active_in_week_1
      type: INTEGER
      mode: NULLABLE
      description: New Profile Active in Week 1
    - name: new_profile_active_in_weeks_0_and_1
      type: INTEGER
      mode: NULLABLE
      description: New Profile Active in Weeks 0 and 1
