-- Query generated by: templates/clients_daily_histogram_aggregates.sql.py
CREATE TEMPORARY FUNCTION get_keyval_pairs(y STRING)
RETURNS ARRAY<STRING>
LANGUAGE js
AS
  '''
          var z = new Array();
          node = JSON.parse(y);
          for (let [key, value] of Object.entries(node)) {
            z.push(`${key}:${value}`);
          }
          return z;
        ''';

        -- convert a string like '[5, 6, 7]' to an array struct
CREATE TEMPORARY FUNCTION string_to_arr(y STRING)
RETURNS ARRAY<STRING>
LANGUAGE js
AS
  '''
          return JSON.parse(y);
        ''';

CREATE TEMP FUNCTION udf_get_histogram_type(histograms ARRAY<STRING>) AS (
  (
    SELECT
      CASE
        SAFE_CAST(JSON_EXTRACT(histogram, "$.histogram_type") AS INT64)
      WHEN
        0
      THEN
        'histogram-exponential'
      WHEN
        1
      THEN
        'histogram-linear'
      WHEN
        2
      THEN
        'histogram-boolean'
      WHEN
        3
      THEN
        'histogram-flag'
      WHEN
        4
      THEN
        'histogram-count'
      WHEN
        5
      THEN
        'histogram-categorical'
      END
      AS histogram_type
    FROM
      UNNEST(histograms) AS histogram
    WHERE
      histogram IS NOT NULL
      AND JSON_EXTRACT(histogram, "$.histogram_type") IS NOT NULL
    LIMIT
      1
  )
);

CREATE TEMP FUNCTION udf_aggregate_json_sum(histograms ARRAY<STRING>) AS (
  ARRAY(
    SELECT AS STRUCT
      SPLIT(keyval, ':')[OFFSET(0)] AS key,
      SUM(SAFE_CAST(SPLIT(keyval, ':')[OFFSET(1)] AS INT64)) AS value
    FROM
      UNNEST(histograms) AS histogram,
      UNNEST(get_keyval_pairs(JSON_EXTRACT(histogram, "$.values"))) AS keyval
    WHERE
      histogram IS NOT NULL
      AND JSON_EXTRACT(histogram, "$.values") IS NOT NULL
    GROUP BY
      key
  )
);

WITH filtered AS (
  SELECT
    *,
    SPLIT(application.version, '.')[OFFSET(0)] AS app_version,
    DATE(submission_timestamp) AS submission_date,
    normalized_os AS os,
    application.build_id AS app_build_id,
    normalized_channel AS channel
  FROM
    `moz-fx-data-shared-prod.telemetry_stable.main_v4`
  WHERE
    DATE(submission_timestamp) = @submission_date
    AND normalized_channel IN ("release", "beta", "nightly")
    AND client_id IS NOT NULL
),
sampled_data AS (
  SELECT
    *
  FROM
    filtered
  WHERE
    channel IN ("nightly", "beta")
    OR (channel = "release" AND os != "Windows")
  UNION ALL
  SELECT
    *
  FROM
    filtered
  WHERE
    channel = 'release'
    AND os = 'Windows'
    AND sample_id >= @min_sample_id
    AND sample_id <= @max_sample_id
),
grouped_metrics AS (
  SELECT
    DATE(submission_timestamp) AS submission_date,
    sample_id,
    client_id,
    normalized_os AS os,
    SPLIT(application.version, '.')[OFFSET(0)] AS app_version,
    application.build_id AS app_build_id,
    normalized_channel AS channel,
    ARRAY<
      STRUCT<
        name STRING,
        process STRING,
        value ARRAY<STRUCT<key STRING, value STRING>>,
        bucket_range STRUCT<first_bucket INT64, last_bucket INT64, num_buckets INT64>
      >
    >[
      (
        'addon_content_policy_shim_blocking_loaded_ms',
        'content',
        payload.processes.content.keyed_histograms.addon_content_policy_shim_blocking_loaded_ms,
        (1, 60000, 20)
      ),
      (
        'addon_content_policy_shim_blocking_loaded_ms',
        'parent',
        payload.keyed_histograms.addon_content_policy_shim_blocking_loaded_ms,
        (1, 60000, 20)
      ),
      (
        'addon_content_policy_shim_blocking_loading_ms',
        'content',
        payload.processes.content.keyed_histograms.addon_content_policy_shim_blocking_loading_ms,
        (1, 60000, 20)
      ),
      (
        'addon_content_policy_shim_blocking_loading_ms',
        'parent',
        payload.keyed_histograms.addon_content_policy_shim_blocking_loading_ms,
        (1, 60000, 20)
      ),
      (
        'addon_forbidden_cpow_usage',
        'content',
        payload.processes.content.keyed_histograms.addon_forbidden_cpow_usage,
        (1, 2, 3)
      ),
      (
        'addon_forbidden_cpow_usage',
        'parent',
        payload.keyed_histograms.addon_forbidden_cpow_usage,
        (1, 2, 3)
      ),
      (
        'addon_shim_usage',
        'content',
        payload.processes.content.keyed_histograms.addon_shim_usage,
        (1, 15, 16)
      ),
      ('addon_shim_usage', 'parent', payload.keyed_histograms.addon_shim_usage, (1, 15, 16)),
      (
        'application_reputation_server_verdict_2',
        'content',
        payload.processes.content.keyed_histograms.application_reputation_server_verdict_2,
        (1, 50, 51)
      ),
      (
        'application_reputation_server_verdict_2',
        'parent',
        payload.keyed_histograms.application_reputation_server_verdict_2,
        (1, 50, 51)
      ),
      (
        'blocked_on_plugin_instance_destroy_ms',
        'content',
        payload.processes.content.keyed_histograms.blocked_on_plugin_instance_destroy_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_plugin_instance_destroy_ms',
        'parent',
        payload.keyed_histograms.blocked_on_plugin_instance_destroy_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_plugin_instance_init_ms',
        'content',
        payload.processes.content.keyed_histograms.blocked_on_plugin_instance_init_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_plugin_instance_init_ms',
        'parent',
        payload.keyed_histograms.blocked_on_plugin_instance_init_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_plugin_module_init_ms',
        'content',
        payload.processes.content.keyed_histograms.blocked_on_plugin_module_init_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_plugin_module_init_ms',
        'parent',
        payload.keyed_histograms.blocked_on_plugin_module_init_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_plugin_stream_init_ms',
        'content',
        payload.processes.content.keyed_histograms.blocked_on_plugin_stream_init_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_plugin_stream_init_ms',
        'parent',
        payload.keyed_histograms.blocked_on_plugin_stream_init_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_pluginasyncsurrogate_waitforinit_ms',
        'content',
        payload.processes.content.keyed_histograms.blocked_on_pluginasyncsurrogate_waitforinit_ms,
        (1, 10000, 20)
      ),
      (
        'blocked_on_pluginasyncsurrogate_waitforinit_ms',
        'parent',
        payload.keyed_histograms.blocked_on_pluginasyncsurrogate_waitforinit_ms,
        (1, 10000, 20)
      ),
      (
        'canvas_webgl_accl_failure_id',
        'content',
        payload.processes.content.keyed_histograms.canvas_webgl_accl_failure_id,
        (1, 2, 3)
      ),
      (
        'canvas_webgl_accl_failure_id',
        'parent',
        payload.keyed_histograms.canvas_webgl_accl_failure_id,
        (1, 2, 3)
      ),
      (
        'canvas_webgl_failure_id',
        'content',
        payload.processes.content.keyed_histograms.canvas_webgl_failure_id,
        (1, 2, 3)
      ),
      (
        'canvas_webgl_failure_id',
        'parent',
        payload.keyed_histograms.canvas_webgl_failure_id,
        (1, 2, 3)
      ),
      (
        'content_js_background_tick_delay_events_ms',
        'content',
        payload.processes.content.keyed_histograms.content_js_background_tick_delay_events_ms,
        (1, 100, 10)
      ),
      (
        'content_js_background_tick_delay_events_ms',
        'parent',
        payload.keyed_histograms.content_js_background_tick_delay_events_ms,
        (1, 100, 10)
      ),
      (
        'content_js_foreground_tick_delay_events_ms',
        'content',
        payload.processes.content.keyed_histograms.content_js_foreground_tick_delay_events_ms,
        (1, 100, 10)
      ),
      (
        'content_js_foreground_tick_delay_events_ms',
        'parent',
        payload.keyed_histograms.content_js_foreground_tick_delay_events_ms,
        (1, 100, 10)
      ),
      (
        'content_large_paint_phase_weight',
        'content',
        payload.processes.content.keyed_histograms.content_large_paint_phase_weight,
        (1, 100, 10)
      ),
      (
        'content_large_paint_phase_weight',
        'parent',
        payload.keyed_histograms.content_large_paint_phase_weight,
        (1, 100, 10)
      ),
      (
        'content_signature_verification_errors',
        'content',
        payload.processes.content.keyed_histograms.content_signature_verification_errors,
        (1, 50, 51)
      ),
      (
        'content_signature_verification_errors',
        'parent',
        payload.keyed_histograms.content_signature_verification_errors,
        (1, 50, 51)
      ),
      (
        'content_small_paint_phase_weight',
        'content',
        payload.processes.content.keyed_histograms.content_small_paint_phase_weight,
        (1, 100, 10)
      ),
      (
        'content_small_paint_phase_weight',
        'parent',
        payload.keyed_histograms.content_small_paint_phase_weight,
        (1, 100, 10)
      ),
      (
        'd3d11_compositing_failure_id',
        'content',
        payload.processes.content.keyed_histograms.d3d11_compositing_failure_id,
        (1, 2, 3)
      ),
      (
        'd3d11_compositing_failure_id',
        'parent',
        payload.keyed_histograms.d3d11_compositing_failure_id,
        (1, 2, 3)
      ),
      (
        'd3d9_compositing_failure_id',
        'content',
        payload.processes.content.keyed_histograms.d3d9_compositing_failure_id,
        (1, 2, 3)
      ),
      (
        'd3d9_compositing_failure_id',
        'parent',
        payload.keyed_histograms.d3d9_compositing_failure_id,
        (1, 2, 3)
      ),
      (
        'decoder_doctor_infobar_stats',
        'content',
        payload.processes.content.keyed_histograms.decoder_doctor_infobar_stats,
        (1, 8, 9)
      ),
      (
        'decoder_doctor_infobar_stats',
        'parent',
        payload.keyed_histograms.decoder_doctor_infobar_stats,
        (1, 8, 9)
      ),
      (
        'devtools_cold_toolbox_open_delay_ms',
        'parent',
        payload.keyed_histograms.devtools_cold_toolbox_open_delay_ms,
        (1, 60000, 100)
      ),
      (
        'devtools_gcli_commands_keyed',
        'content',
        payload.processes.content.keyed_histograms.devtools_gcli_commands_keyed,
        (1, 2, 3)
      ),
      (
        'devtools_gcli_commands_keyed',
        'parent',
        payload.keyed_histograms.devtools_gcli_commands_keyed,
        (1, 2, 3)
      ),
      (
        'devtools_javascript_error_displayed',
        'content',
        payload.processes.content.keyed_histograms.devtools_javascript_error_displayed,
        (1, 2, 3)
      ),
      (
        'devtools_javascript_error_displayed',
        'parent',
        payload.keyed_histograms.devtools_javascript_error_displayed,
        (1, 2, 3)
      ),
      (
        'devtools_memory_breakdown_census_count',
        'content',
        payload.processes.content.keyed_histograms.devtools_memory_breakdown_census_count,
        (1, 2, 3)
      ),
      (
        'devtools_memory_breakdown_census_count',
        'parent',
        payload.keyed_histograms.devtools_memory_breakdown_census_count,
        (1, 2, 3)
      ),
      (
        'devtools_memory_breakdown_dominator_tree_count',
        'content',
        payload.processes.content.keyed_histograms.devtools_memory_breakdown_dominator_tree_count,
        (1, 2, 3)
      ),
      (
        'devtools_memory_breakdown_dominator_tree_count',
        'parent',
        payload.keyed_histograms.devtools_memory_breakdown_dominator_tree_count,
        (1, 2, 3)
      ),
      (
        'devtools_perftools_recording_features_used',
        'content',
        payload.processes.content.keyed_histograms.devtools_perftools_recording_features_used,
        (1, 2, 3)
      ),
      (
        'devtools_perftools_recording_features_used',
        'parent',
        payload.keyed_histograms.devtools_perftools_recording_features_used,
        (1, 2, 3)
      ),
      (
        'devtools_perftools_selected_view_ms',
        'content',
        payload.processes.content.keyed_histograms.devtools_perftools_selected_view_ms,
        (1, 600000, 20)
      ),
      (
        'devtools_perftools_selected_view_ms',
        'parent',
        payload.keyed_histograms.devtools_perftools_selected_view_ms,
        (1, 600000, 20)
      ),
      (
        'devtools_toolbox_page_reload_delay_ms',
        'parent',
        payload.keyed_histograms.devtools_toolbox_page_reload_delay_ms,
        (1, 120000, 100)
      ),
      (
        'devtools_warm_toolbox_open_delay_ms',
        'parent',
        payload.keyed_histograms.devtools_warm_toolbox_open_delay_ms,
        (1, 60000, 100)
      ),
      (
        'devtools_webide_connected_runtime_app_type',
        'content',
        payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_app_type,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_app_type',
        'parent',
        payload.keyed_histograms.devtools_webide_connected_runtime_app_type,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_id',
        'content',
        payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_id,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_id',
        'parent',
        payload.keyed_histograms.devtools_webide_connected_runtime_id,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_os',
        'content',
        payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_os,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_os',
        'parent',
        payload.keyed_histograms.devtools_webide_connected_runtime_os,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_platform_version',
        'content',
        payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_platform_version,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_platform_version',
        'parent',
        payload.keyed_histograms.devtools_webide_connected_runtime_platform_version,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_processor',
        'content',
        payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_processor,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_processor',
        'parent',
        payload.keyed_histograms.devtools_webide_connected_runtime_processor,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_type',
        'content',
        payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_type,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_type',
        'parent',
        payload.keyed_histograms.devtools_webide_connected_runtime_type,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_version',
        'content',
        payload.processes.content.keyed_histograms.devtools_webide_connected_runtime_version,
        (1, 2, 3)
      ),
      (
        'devtools_webide_connected_runtime_version',
        'parent',
        payload.keyed_histograms.devtools_webide_connected_runtime_version,
        (1, 2, 3)
      ),
      (
        'dom_script_src_encoding',
        'content',
        payload.processes.content.keyed_histograms.dom_script_src_encoding,
        (1, 2, 3)
      ),
      (
        'dom_script_src_encoding',
        'parent',
        payload.keyed_histograms.dom_script_src_encoding,
        (1, 2, 3)
      ),
      (
        'form_filling_required_time_ms',
        'parent',
        payload.keyed_histograms.form_filling_required_time_ms,
        (1, 300000, 22)
      ),
      (
        'fx_migration_bookmarks_import_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_bookmarks_import_ms,
        (1, 100000, 70)
      ),
      (
        'fx_migration_bookmarks_import_ms',
        'parent',
        payload.keyed_histograms.fx_migration_bookmarks_import_ms,
        (1, 100000, 70)
      ),
      (
        'fx_migration_bookmarks_jank_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_bookmarks_jank_ms,
        (1, 60000, 20)
      ),
      (
        'fx_migration_bookmarks_jank_ms',
        'parent',
        payload.keyed_histograms.fx_migration_bookmarks_jank_ms,
        (1, 60000, 20)
      ),
      (
        'fx_migration_bookmarks_quantity',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_bookmarks_quantity,
        (1, 1000, 20)
      ),
      (
        'fx_migration_bookmarks_quantity',
        'parent',
        payload.keyed_histograms.fx_migration_bookmarks_quantity,
        (1, 1000, 20)
      ),
      (
        'fx_migration_errors',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_errors,
        (1, 12, 13)
      ),
      ('fx_migration_errors', 'parent', payload.keyed_histograms.fx_migration_errors, (1, 12, 13)),
      (
        'fx_migration_history_import_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_history_import_ms,
        (1, 100000, 70)
      ),
      (
        'fx_migration_history_import_ms',
        'parent',
        payload.keyed_histograms.fx_migration_history_import_ms,
        (1, 100000, 70)
      ),
      (
        'fx_migration_history_jank_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_history_jank_ms,
        (1, 60000, 20)
      ),
      (
        'fx_migration_history_jank_ms',
        'parent',
        payload.keyed_histograms.fx_migration_history_jank_ms,
        (1, 60000, 20)
      ),
      (
        'fx_migration_history_quantity',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_history_quantity,
        (1, 10000, 40)
      ),
      (
        'fx_migration_history_quantity',
        'parent',
        payload.keyed_histograms.fx_migration_history_quantity,
        (1, 10000, 40)
      ),
      (
        'fx_migration_imported_homepage',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_imported_homepage,
        (1, 2, 3)
      ),
      (
        'fx_migration_imported_homepage',
        'parent',
        payload.keyed_histograms.fx_migration_imported_homepage,
        (1, 2, 3)
      ),
      (
        'fx_migration_logins_import_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_logins_import_ms,
        (1, 100000, 70)
      ),
      (
        'fx_migration_logins_import_ms',
        'parent',
        payload.keyed_histograms.fx_migration_logins_import_ms,
        (1, 100000, 70)
      ),
      (
        'fx_migration_logins_jank_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_logins_jank_ms,
        (1, 60000, 20)
      ),
      (
        'fx_migration_logins_jank_ms',
        'parent',
        payload.keyed_histograms.fx_migration_logins_jank_ms,
        (1, 60000, 20)
      ),
      (
        'fx_migration_logins_quantity',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_logins_quantity,
        (1, 1000, 20)
      ),
      (
        'fx_migration_logins_quantity',
        'parent',
        payload.keyed_histograms.fx_migration_logins_quantity,
        (1, 1000, 20)
      ),
      (
        'fx_migration_usage',
        'content',
        payload.processes.content.keyed_histograms.fx_migration_usage,
        (1, 12, 13)
      ),
      ('fx_migration_usage', 'parent', payload.keyed_histograms.fx_migration_usage, (1, 12, 13)),
      (
        'fx_session_restore_content_collect_data_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_session_restore_content_collect_data_ms,
        (1, 30000, 20)
      ),
      (
        'fx_session_restore_content_collect_data_ms',
        'parent',
        payload.keyed_histograms.fx_session_restore_content_collect_data_ms,
        (1, 30000, 20)
      ),
      (
        'fx_startup_migration_data_recency',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_data_recency,
        (1, 8760, 50)
      ),
      (
        'fx_startup_migration_data_recency',
        'parent',
        payload.keyed_histograms.fx_startup_migration_data_recency,
        (1, 8760, 50)
      ),
      (
        'fx_startup_migration_undo_bookmarks_errorcount',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_undo_bookmarks_errorcount,
        (1, 100, 20)
      ),
      (
        'fx_startup_migration_undo_bookmarks_errorcount',
        'parent',
        payload.keyed_histograms.fx_startup_migration_undo_bookmarks_errorcount,
        (1, 100, 20)
      ),
      (
        'fx_startup_migration_undo_bookmarks_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_undo_bookmarks_ms,
        (1, 60000, 20)
      ),
      (
        'fx_startup_migration_undo_bookmarks_ms',
        'parent',
        payload.keyed_histograms.fx_startup_migration_undo_bookmarks_ms,
        (1, 60000, 20)
      ),
      (
        'fx_startup_migration_undo_logins_errorcount',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_undo_logins_errorcount,
        (1, 100, 20)
      ),
      (
        'fx_startup_migration_undo_logins_errorcount',
        'parent',
        payload.keyed_histograms.fx_startup_migration_undo_logins_errorcount,
        (1, 100, 20)
      ),
      (
        'fx_startup_migration_undo_logins_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_undo_logins_ms,
        (1, 60000, 20)
      ),
      (
        'fx_startup_migration_undo_logins_ms',
        'parent',
        payload.keyed_histograms.fx_startup_migration_undo_logins_ms,
        (1, 60000, 20)
      ),
      (
        'fx_startup_migration_undo_reason',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_undo_reason,
        (1, 10, 11)
      ),
      (
        'fx_startup_migration_undo_reason',
        'parent',
        payload.keyed_histograms.fx_startup_migration_undo_reason,
        (1, 10, 11)
      ),
      (
        'fx_startup_migration_undo_total_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_undo_total_ms,
        (1, 60000, 20)
      ),
      (
        'fx_startup_migration_undo_total_ms',
        'parent',
        payload.keyed_histograms.fx_startup_migration_undo_total_ms,
        (1, 60000, 20)
      ),
      (
        'fx_startup_migration_undo_visits_errorcount',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_undo_visits_errorcount,
        (1, 100, 20)
      ),
      (
        'fx_startup_migration_undo_visits_errorcount',
        'parent',
        payload.keyed_histograms.fx_startup_migration_undo_visits_errorcount,
        (1, 100, 20)
      ),
      (
        'fx_startup_migration_undo_visits_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_undo_visits_ms,
        (1, 60000, 20)
      ),
      (
        'fx_startup_migration_undo_visits_ms',
        'parent',
        payload.keyed_histograms.fx_startup_migration_undo_visits_ms,
        (1, 60000, 20)
      ),
      (
        'fx_startup_migration_used_recent_browser',
        'content',
        payload.processes.content.keyed_histograms.fx_startup_migration_used_recent_browser,
        (1, 2, 3)
      ),
      (
        'fx_startup_migration_used_recent_browser',
        'parent',
        payload.keyed_histograms.fx_startup_migration_used_recent_browser,
        (1, 2, 3)
      ),
      (
        'fx_tab_remote_navigation_delay_ms',
        'content',
        payload.processes.content.keyed_histograms.fx_tab_remote_navigation_delay_ms,
        (1, 4000, 100)
      ),
      (
        'fx_tab_remote_navigation_delay_ms',
        'parent',
        payload.keyed_histograms.fx_tab_remote_navigation_delay_ms,
        (1, 4000, 100)
      ),
      (
        'fx_tabletmode_page_load',
        'content',
        payload.processes.content.keyed_histograms.fx_tabletmode_page_load,
        (1, 100000, 30)
      ),
      (
        'fx_tabletmode_page_load',
        'parent',
        payload.keyed_histograms.fx_tabletmode_page_load,
        (1, 100000, 30)
      ),
      (
        'fx_urlbar_selected_result_index_by_type',
        'content',
        payload.processes.content.keyed_histograms.fx_urlbar_selected_result_index_by_type,
        (1, 14, 15)
      ),
      (
        'fx_urlbar_selected_result_index_by_type',
        'parent',
        payload.keyed_histograms.fx_urlbar_selected_result_index_by_type,
        (1, 14, 15)
      ),
      (
        'hsts_priming_request_duration',
        'content',
        payload.processes.content.keyed_histograms.hsts_priming_request_duration,
        (100, 30000, 100)
      ),
      (
        'hsts_priming_request_duration',
        'parent',
        payload.keyed_histograms.hsts_priming_request_duration,
        (100, 30000, 100)
      ),
      (
        'http3_connecttion_close_code',
        'content',
        payload.processes.content.keyed_histograms.http3_connecttion_close_code,
        (1, 100, 101)
      ),
      (
        'http3_connecttion_close_code',
        'parent',
        payload.keyed_histograms.http3_connecttion_close_code,
        (1, 100, 101)
      ),
      (
        'http_cache_disposition_3',
        'content',
        payload.processes.content.keyed_histograms.http_cache_disposition_3,
        (1, 50, 51)
      ),
      (
        'http_cache_disposition_3',
        'parent',
        payload.keyed_histograms.http_cache_disposition_3,
        (1, 50, 51)
      ),
      (
        'http_channel_disposition_upgrade',
        'parent',
        payload.keyed_histograms.http_channel_disposition_upgrade,
        (1, 50, 51)
      ),
      (
        'http_child_omt_stats',
        'content',
        payload.processes.content.keyed_histograms.http_child_omt_stats,
        (1, 50, 51)
      ),
      (
        'http_traffic_analysis_2',
        'parent',
        payload.keyed_histograms.http_traffic_analysis_2,
        (1, 50, 51)
      ),
      (
        'http_traffic_analysis_3',
        'parent',
        payload.keyed_histograms.http_traffic_analysis_3,
        (1, 50, 51)
      ),
      (
        'idle_runnable_budget_overuse_ms',
        'content',
        payload.processes.content.keyed_histograms.idle_runnable_budget_overuse_ms,
        (1, 10000, 10)
      ),
      (
        'idle_runnable_budget_overuse_ms',
        'parent',
        payload.keyed_histograms.idle_runnable_budget_overuse_ms,
        (1, 10000, 10)
      ),
      (
        'ipc_read_main_thread_latency_ms',
        'content',
        payload.processes.content.keyed_histograms.ipc_read_main_thread_latency_ms,
        (1, 500, 20)
      ),
      (
        'ipc_read_main_thread_latency_ms',
        'parent',
        payload.keyed_histograms.ipc_read_main_thread_latency_ms,
        (1, 500, 20)
      ),
      (
        'ipc_reply_size',
        'content',
        payload.processes.content.keyed_histograms.ipc_reply_size,
        (1, 8000000, 50)
      ),
      ('ipc_reply_size', 'parent', payload.keyed_histograms.ipc_reply_size, (1, 8000000, 50)),
      (
        'ipc_sync_main_latency_ms',
        'content',
        payload.processes.content.keyed_histograms.ipc_sync_main_latency_ms,
        (32, 750, 40)
      ),
      (
        'ipc_sync_main_latency_ms',
        'parent',
        payload.keyed_histograms.ipc_sync_main_latency_ms,
        (32, 750, 40)
      ),
      (
        'ipc_sync_message_manager_latency_ms',
        'content',
        payload.processes.content.keyed_histograms.ipc_sync_message_manager_latency_ms,
        (32, 750, 40)
      ),
      (
        'ipc_sync_message_manager_latency_ms',
        'parent',
        payload.keyed_histograms.ipc_sync_message_manager_latency_ms,
        (32, 750, 40)
      ),
      (
        'ipc_sync_receive_ms',
        'content',
        payload.processes.content.keyed_histograms.ipc_sync_receive_ms,
        (32, 750, 40)
      ),
      (
        'ipc_sync_receive_ms',
        'parent',
        payload.keyed_histograms.ipc_sync_receive_ms,
        (32, 750, 40)
      ),
      (
        'ipc_write_main_thread_latency_ms',
        'content',
        payload.processes.content.keyed_histograms.ipc_write_main_thread_latency_ms,
        (1, 500, 20)
      ),
      (
        'ipc_write_main_thread_latency_ms',
        'parent',
        payload.keyed_histograms.ipc_write_main_thread_latency_ms,
        (1, 500, 20)
      ),
      (
        'js_telemetry_addon_exceptions',
        'content',
        payload.processes.content.keyed_histograms.js_telemetry_addon_exceptions,
        (1, 2, 3)
      ),
      (
        'js_telemetry_addon_exceptions',
        'parent',
        payload.keyed_histograms.js_telemetry_addon_exceptions,
        (1, 2, 3)
      ),
      (
        'main_thread_runnable_ms',
        'content',
        payload.processes.content.keyed_histograms.main_thread_runnable_ms,
        (1, 10000, 10)
      ),
      (
        'main_thread_runnable_ms',
        'parent',
        payload.keyed_histograms.main_thread_runnable_ms,
        (1, 10000, 10)
      ),
      (
        'media_codec_used',
        'content',
        payload.processes.content.keyed_histograms.media_codec_used,
        (1, 2, 3)
      ),
      ('media_codec_used', 'parent', payload.keyed_histograms.media_codec_used, (1, 2, 3)),
      (
        'memory_distribution_among_content',
        'content',
        payload.processes.content.keyed_histograms.memory_distribution_among_content,
        (1, 200, 100)
      ),
      (
        'memory_distribution_among_content',
        'parent',
        payload.keyed_histograms.memory_distribution_among_content,
        (1, 200, 100)
      ),
      (
        'narrate_content_by_language_2',
        'content',
        payload.processes.content.keyed_histograms.narrate_content_by_language_2,
        (1, 4, 5)
      ),
      (
        'narrate_content_by_language_2',
        'parent',
        payload.keyed_histograms.narrate_content_by_language_2,
        (1, 4, 5)
      ),
      (
        'network_cache_entry_count',
        'parent',
        payload.keyed_histograms.network_cache_entry_count,
        (1, 100000, 100)
      ),
      (
        'network_cache_entry_count_share',
        'parent',
        payload.keyed_histograms.network_cache_entry_count_share,
        (1, 99, 100)
      ),
      (
        'network_cache_isolation_entry_count_increase',
        'parent',
        payload.keyed_histograms.network_cache_isolation_entry_count_increase,
        (1, 200, 100)
      ),
      (
        'network_cache_isolation_size_increase',
        'parent',
        payload.keyed_histograms.network_cache_isolation_size_increase,
        (1, 200, 100)
      ),
      (
        'network_cache_isolation_unique_site_access_count',
        'parent',
        payload.keyed_histograms.network_cache_isolation_unique_site_access_count,
        (1, 1000, 100)
      ),
      ('network_cache_size', 'parent', payload.keyed_histograms.network_cache_size, (1, 4000, 100)),
      (
        'network_cache_size_share',
        'parent',
        payload.keyed_histograms.network_cache_size_share,
        (1, 99, 100)
      ),
      (
        'network_http_redirect_to_scheme',
        'parent',
        payload.keyed_histograms.network_http_redirect_to_scheme,
        (1, 50, 51)
      ),
      (
        'notify_observers_latency_ms',
        'content',
        payload.processes.content.keyed_histograms.notify_observers_latency_ms,
        (3, 512, 20)
      ),
      (
        'notify_observers_latency_ms',
        'parent',
        payload.keyed_histograms.notify_observers_latency_ms,
        (3, 512, 20)
      ),
      (
        'opengl_compositing_failure_id',
        'content',
        payload.processes.content.keyed_histograms.opengl_compositing_failure_id,
        (1, 2, 3)
      ),
      (
        'opengl_compositing_failure_id',
        'parent',
        payload.keyed_histograms.opengl_compositing_failure_id,
        (1, 2, 3)
      ),
      (
        'permission_request_handling_user_input',
        'parent',
        payload.keyed_histograms.permission_request_handling_user_input,
        (1, 2, 3)
      ),
      (
        'permission_request_origin_scheme',
        'parent',
        payload.keyed_histograms.permission_request_origin_scheme,
        (1, 10, 11)
      ),
      (
        'permission_request_third_party_origin',
        'parent',
        payload.keyed_histograms.permission_request_third_party_origin,
        (1, 2, 3)
      ),
      (
        'popup_notification_dismissal_ms',
        'content',
        payload.processes.content.keyed_histograms.popup_notification_dismissal_ms,
        (200, 20000, 50)
      ),
      (
        'popup_notification_dismissal_ms',
        'parent',
        payload.keyed_histograms.popup_notification_dismissal_ms,
        (200, 20000, 50)
      ),
      (
        'popup_notification_main_action_ms',
        'content',
        payload.processes.content.keyed_histograms.popup_notification_main_action_ms,
        (100, 600000, 40)
      ),
      (
        'popup_notification_main_action_ms',
        'parent',
        payload.keyed_histograms.popup_notification_main_action_ms,
        (100, 600000, 40)
      ),
      (
        'popup_notification_stats',
        'content',
        payload.processes.content.keyed_histograms.popup_notification_stats,
        (1, 40, 41)
      ),
      (
        'popup_notification_stats',
        'parent',
        payload.keyed_histograms.popup_notification_stats,
        (1, 40, 41)
      ),
      (
        'preferences_file_load_num_prefs',
        'content',
        payload.processes.content.keyed_histograms.preferences_file_load_num_prefs,
        (1, 10000, 20)
      ),
      (
        'preferences_file_load_num_prefs',
        'parent',
        payload.keyed_histograms.preferences_file_load_num_prefs,
        (1, 10000, 20)
      ),
      (
        'preferences_file_load_size_b',
        'content',
        payload.processes.content.keyed_histograms.preferences_file_load_size_b,
        (1, 2000000, 20)
      ),
      (
        'preferences_file_load_size_b',
        'parent',
        payload.keyed_histograms.preferences_file_load_size_b,
        (1, 2000000, 20)
      ),
      (
        'preferences_file_load_time_us',
        'content',
        payload.processes.content.keyed_histograms.preferences_file_load_time_us,
        (1, 1000000, 20)
      ),
      (
        'preferences_file_load_time_us',
        'parent',
        payload.keyed_histograms.preferences_file_load_time_us,
        (1, 1000000, 20)
      ),
      (
        'presshell_flushes_per_tick',
        'content',
        payload.processes.content.keyed_histograms.presshell_flushes_per_tick,
        (1, 256, 32)
      ),
      (
        'presshell_flushes_per_tick',
        'parent',
        payload.keyed_histograms.presshell_flushes_per_tick,
        (1, 256, 32)
      ),
      (
        'presshell_layout_total_ms_per_tick',
        'content',
        payload.processes.content.keyed_histograms.presshell_layout_total_ms_per_tick,
        (1, 1000, 50)
      ),
      (
        'presshell_layout_total_ms_per_tick',
        'parent',
        payload.keyed_histograms.presshell_layout_total_ms_per_tick,
        (1, 1000, 50)
      ),
      (
        'presshell_reqs_per_layout_flush',
        'content',
        payload.processes.content.keyed_histograms.presshell_reqs_per_layout_flush,
        (1, 256, 32)
      ),
      (
        'presshell_reqs_per_layout_flush',
        'parent',
        payload.keyed_histograms.presshell_reqs_per_layout_flush,
        (1, 256, 32)
      ),
      ('print_count', 'content', payload.processes.content.keyed_histograms.print_count, (1, 2, 3)),
      ('print_count', 'parent', payload.keyed_histograms.print_count, (1, 2, 3)),
      (
        'print_dialog_opened_count',
        'content',
        payload.processes.content.keyed_histograms.print_dialog_opened_count,
        (1, 2, 3)
      ),
      (
        'print_dialog_opened_count',
        'parent',
        payload.keyed_histograms.print_dialog_opened_count,
        (1, 2, 3)
      ),
      (
        'process_crash_submit_attempt',
        'content',
        payload.processes.content.keyed_histograms.process_crash_submit_attempt,
        (1, 2, 3)
      ),
      (
        'process_crash_submit_attempt',
        'parent',
        payload.keyed_histograms.process_crash_submit_attempt,
        (1, 2, 3)
      ),
      (
        'process_crash_submit_success',
        'content',
        payload.processes.content.keyed_histograms.process_crash_submit_success,
        (1, 2, 3)
      ),
      (
        'process_crash_submit_success',
        'parent',
        payload.keyed_histograms.process_crash_submit_success,
        (1, 2, 3)
      ),
      (
        'pwmgr_manage_sorted',
        'content',
        payload.processes.content.keyed_histograms.pwmgr_manage_sorted,
        (1, 2, 3)
      ),
      ('pwmgr_manage_sorted', 'parent', payload.keyed_histograms.pwmgr_manage_sorted, (1, 2, 3)),
      (
        'qm_first_initialization_attempt',
        'parent',
        payload.keyed_histograms.qm_first_initialization_attempt,
        (1, 2, 3)
      ),
      (
        'qm_init_telemetry_error',
        'parent',
        payload.keyed_histograms.qm_init_telemetry_error,
        (1, 75, 76)
      ),
      (
        'refresh_driver_tick_phase_weight',
        'content',
        payload.processes.content.keyed_histograms.refresh_driver_tick_phase_weight,
        (1, 100, 12)
      ),
      (
        'refresh_driver_tick_phase_weight',
        'parent',
        payload.keyed_histograms.refresh_driver_tick_phase_weight,
        (1, 100, 12)
      ),
      (
        'rejected_message_manager_message',
        'content',
        payload.processes.content.keyed_histograms.rejected_message_manager_message,
        (1, 2, 3)
      ),
      (
        'rejected_message_manager_message',
        'parent',
        payload.keyed_histograms.rejected_message_manager_message,
        (1, 2, 3)
      ),
      (
        'sandbox_failed_launch_keyed',
        'parent',
        payload.keyed_histograms.sandbox_failed_launch_keyed,
        (1, 50, 51)
      ),
      (
        'sandbox_rejected_syscalls',
        'content',
        payload.processes.content.keyed_histograms.sandbox_rejected_syscalls,
        (1, 2, 3)
      ),
      (
        'sandbox_rejected_syscalls',
        'parent',
        payload.keyed_histograms.sandbox_rejected_syscalls,
        (1, 2, 3)
      ),
      (
        'search_counts',
        'content',
        payload.processes.content.keyed_histograms.search_counts,
        (1, 2, 3)
      ),
      ('search_counts', 'parent', payload.keyed_histograms.search_counts, (1, 2, 3)),
      (
        'service_worker_fetch_event_channel_reset_ms',
        'content',
        payload.processes.content.keyed_histograms.service_worker_fetch_event_channel_reset_ms,
        (1, 2000, 25)
      ),
      (
        'service_worker_fetch_event_channel_reset_ms',
        'parent',
        payload.keyed_histograms.service_worker_fetch_event_channel_reset_ms,
        (1, 2000, 25)
      ),
      (
        'service_worker_fetch_event_dispatch_ms',
        'content',
        payload.processes.content.keyed_histograms.service_worker_fetch_event_dispatch_ms,
        (1, 2000, 25)
      ),
      (
        'service_worker_fetch_event_dispatch_ms',
        'parent',
        payload.keyed_histograms.service_worker_fetch_event_dispatch_ms,
        (1, 2000, 25)
      ),
      (
        'service_worker_fetch_event_finish_synthesized_response_ms',
        'content',
        payload.processes.content.keyed_histograms.service_worker_fetch_event_finish_synthesized_response_ms,
        (1, 2000, 25)
      ),
      (
        'service_worker_fetch_event_finish_synthesized_response_ms',
        'parent',
        payload.keyed_histograms.service_worker_fetch_event_finish_synthesized_response_ms,
        (1, 2000, 25)
      ),
      (
        'service_worker_fetch_interception_duration_ms',
        'content',
        payload.processes.content.keyed_histograms.service_worker_fetch_interception_duration_ms,
        (1, 6000, 25)
      ),
      (
        'service_worker_fetch_interception_duration_ms',
        'parent',
        payload.keyed_histograms.service_worker_fetch_interception_duration_ms,
        (1, 6000, 25)
      ),
      (
        'ssl_time_until_handshake_finished_keyed_by_ka',
        'content',
        payload.processes.content.keyed_histograms.ssl_time_until_handshake_finished_keyed_by_ka,
        (1, 60000, 200)
      ),
      (
        'ssl_time_until_handshake_finished_keyed_by_ka',
        'parent',
        payload.keyed_histograms.ssl_time_until_handshake_finished_keyed_by_ka,
        (1, 60000, 200)
      ),
      (
        'storage_sync_get_ops_size',
        'content',
        payload.processes.content.keyed_histograms.storage_sync_get_ops_size,
        (1, 100000, 30)
      ),
      (
        'storage_sync_get_ops_size',
        'parent',
        payload.keyed_histograms.storage_sync_get_ops_size,
        (1, 100000, 30)
      ),
      (
        'storage_sync_remove_ops',
        'content',
        payload.processes.content.keyed_histograms.storage_sync_remove_ops,
        (1, 2, 3)
      ),
      (
        'storage_sync_remove_ops',
        'parent',
        payload.keyed_histograms.storage_sync_remove_ops,
        (1, 2, 3)
      ),
      (
        'storage_sync_set_ops_size',
        'content',
        payload.processes.content.keyed_histograms.storage_sync_set_ops_size,
        (1, 100000, 30)
      ),
      (
        'storage_sync_set_ops_size',
        'parent',
        payload.keyed_histograms.storage_sync_set_ops_size,
        (1, 100000, 30)
      ),
      (
        'subprocess_abnormal_abort',
        'content',
        payload.processes.content.keyed_histograms.subprocess_abnormal_abort,
        (1, 2, 3)
      ),
      (
        'subprocess_abnormal_abort',
        'parent',
        payload.keyed_histograms.subprocess_abnormal_abort,
        (1, 2, 3)
      ),
      (
        'subprocess_crashes_with_dump',
        'content',
        payload.processes.content.keyed_histograms.subprocess_crashes_with_dump,
        (1, 2, 3)
      ),
      (
        'subprocess_crashes_with_dump',
        'parent',
        payload.keyed_histograms.subprocess_crashes_with_dump,
        (1, 2, 3)
      ),
      (
        'subprocess_kill_hard',
        'content',
        payload.processes.content.keyed_histograms.subprocess_kill_hard,
        (1, 2, 3)
      ),
      ('subprocess_kill_hard', 'parent', payload.keyed_histograms.subprocess_kill_hard, (1, 2, 3)),
      (
        'subprocess_launch_failure',
        'content',
        payload.processes.content.keyed_histograms.subprocess_launch_failure,
        (1, 2, 3)
      ),
      (
        'subprocess_launch_failure',
        'parent',
        payload.keyed_histograms.subprocess_launch_failure,
        (1, 2, 3)
      ),
      (
        'sync_worker_operation',
        'content',
        payload.processes.content.keyed_histograms.sync_worker_operation,
        (1, 5000, 20)
      ),
      (
        'sync_worker_operation',
        'parent',
        payload.keyed_histograms.sync_worker_operation,
        (1, 5000, 20)
      ),
      (
        'telemetry_invalid_ping_type_submitted',
        'content',
        payload.processes.content.keyed_histograms.telemetry_invalid_ping_type_submitted,
        (1, 2, 3)
      ),
      (
        'telemetry_invalid_ping_type_submitted',
        'parent',
        payload.keyed_histograms.telemetry_invalid_ping_type_submitted,
        (1, 2, 3)
      ),
      (
        'telemetry_send_failure_type_per_ping',
        'parent',
        payload.keyed_histograms.telemetry_send_failure_type_per_ping,
        (1, 50, 51)
      ),
      (
        'thread_wakeup',
        'content',
        payload.processes.content.keyed_histograms.thread_wakeup,
        (1, 60000, 100)
      ),
      ('thread_wakeup', 'parent', payload.keyed_histograms.thread_wakeup, (1, 60000, 100)),
      (
        'translated_pages_by_language',
        'content',
        payload.processes.content.keyed_histograms.translated_pages_by_language,
        (1, 2, 3)
      ),
      (
        'translated_pages_by_language',
        'parent',
        payload.keyed_histograms.translated_pages_by_language,
        (1, 2, 3)
      ),
      (
        'translation_opportunities_by_language',
        'content',
        payload.processes.content.keyed_histograms.translation_opportunities_by_language,
        (1, 2, 3)
      ),
      (
        'translation_opportunities_by_language',
        'parent',
        payload.keyed_histograms.translation_opportunities_by_language,
        (1, 2, 3)
      ),
      (
        'update_check_extended_error_external',
        'content',
        payload.processes.content.keyed_histograms.update_check_extended_error_external,
        (1, 2, 3)
      ),
      (
        'update_check_extended_error_external',
        'parent',
        payload.keyed_histograms.update_check_extended_error_external,
        (1, 2, 3)
      ),
      (
        'update_check_extended_error_notify',
        'content',
        payload.processes.content.keyed_histograms.update_check_extended_error_notify,
        (1, 2, 3)
      ),
      (
        'update_check_extended_error_notify',
        'parent',
        payload.keyed_histograms.update_check_extended_error_notify,
        (1, 2, 3)
      ),
      (
        'uptake_remote_content_result_1',
        'content',
        payload.processes.content.keyed_histograms.uptake_remote_content_result_1,
        (1, 50, 51)
      ),
      (
        'uptake_remote_content_result_1',
        'parent',
        payload.keyed_histograms.uptake_remote_content_result_1,
        (1, 50, 51)
      ),
      (
        'urlclassifier_cl_keyed_update_time',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_cl_keyed_update_time,
        (20, 120000, 30)
      ),
      (
        'urlclassifier_cl_keyed_update_time',
        'parent',
        payload.keyed_histograms.urlclassifier_cl_keyed_update_time,
        (20, 120000, 30)
      ),
      (
        'urlclassifier_complete_remote_status2',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_complete_remote_status2,
        (1, 16, 17)
      ),
      (
        'urlclassifier_complete_remote_status2',
        'parent',
        payload.keyed_histograms.urlclassifier_complete_remote_status2,
        (1, 16, 17)
      ),
      (
        'urlclassifier_complete_server_response_time',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_complete_server_response_time,
        (1, 5000, 15)
      ),
      (
        'urlclassifier_complete_server_response_time',
        'parent',
        payload.keyed_histograms.urlclassifier_complete_server_response_time,
        (1, 5000, 15)
      ),
      (
        'urlclassifier_complete_timeout2',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_complete_timeout2,
        (1, 2, 3)
      ),
      (
        'urlclassifier_complete_timeout2',
        'parent',
        payload.keyed_histograms.urlclassifier_complete_timeout2,
        (1, 2, 3)
      ),
      (
        'urlclassifier_update_error',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_update_error,
        (1, 16, 17)
      ),
      (
        'urlclassifier_update_error',
        'parent',
        payload.keyed_histograms.urlclassifier_update_error,
        (1, 16, 17)
      ),
      (
        'urlclassifier_update_remote_network_error',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_update_remote_network_error,
        (1, 30, 31)
      ),
      (
        'urlclassifier_update_remote_network_error',
        'parent',
        payload.keyed_histograms.urlclassifier_update_remote_network_error,
        (1, 30, 31)
      ),
      (
        'urlclassifier_update_remote_status2',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_update_remote_status2,
        (1, 16, 17)
      ),
      (
        'urlclassifier_update_remote_status2',
        'parent',
        payload.keyed_histograms.urlclassifier_update_remote_status2,
        (1, 16, 17)
      ),
      (
        'urlclassifier_update_server_response_time',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_update_server_response_time,
        (1, 100000, 30)
      ),
      (
        'urlclassifier_update_server_response_time',
        'parent',
        payload.keyed_histograms.urlclassifier_update_server_response_time,
        (1, 100000, 30)
      ),
      (
        'urlclassifier_update_timeout',
        'content',
        payload.processes.content.keyed_histograms.urlclassifier_update_timeout,
        (1, 4, 5)
      ),
      (
        'urlclassifier_update_timeout',
        'parent',
        payload.keyed_histograms.urlclassifier_update_timeout,
        (1, 4, 5)
      ),
      (
        'video_hidden_play_time_percentage',
        'content',
        payload.processes.content.keyed_histograms.video_hidden_play_time_percentage,
        (1, 100, 50)
      ),
      (
        'video_hidden_play_time_percentage',
        'parent',
        payload.keyed_histograms.video_hidden_play_time_percentage,
        (1, 100, 50)
      ),
      (
        'video_inferred_decode_suspend_percentage',
        'content',
        payload.processes.content.keyed_histograms.video_inferred_decode_suspend_percentage,
        (1, 100, 50)
      ),
      (
        'video_inferred_decode_suspend_percentage',
        'parent',
        payload.keyed_histograms.video_inferred_decode_suspend_percentage,
        (1, 100, 50)
      ),
      (
        'video_inter_keyframe_average_ms',
        'content',
        payload.processes.content.keyed_histograms.video_inter_keyframe_average_ms,
        (1, 60000, 100)
      ),
      (
        'video_inter_keyframe_average_ms',
        'parent',
        payload.keyed_histograms.video_inter_keyframe_average_ms,
        (1, 60000, 100)
      ),
      (
        'video_inter_keyframe_max_ms',
        'content',
        payload.processes.content.keyed_histograms.video_inter_keyframe_max_ms,
        (1, 60000, 100)
      ),
      (
        'video_inter_keyframe_max_ms',
        'parent',
        payload.keyed_histograms.video_inter_keyframe_max_ms,
        (1, 60000, 100)
      ),
      (
        'video_suspend_recovery_time_ms',
        'content',
        payload.processes.content.keyed_histograms.video_suspend_recovery_time_ms,
        (1, 10000, 100)
      ),
      (
        'video_suspend_recovery_time_ms',
        'parent',
        payload.keyed_histograms.video_suspend_recovery_time_ms,
        (1, 10000, 100)
      ),
      (
        'video_unblackinglisting_dxva_driver_runtime_status',
        'content',
        payload.processes.content.keyed_histograms.video_unblackinglisting_dxva_driver_runtime_status,
        (1, 10, 11)
      ),
      (
        'weave_engine_sync_errors',
        'content',
        payload.processes.content.keyed_histograms.weave_engine_sync_errors,
        (1, 2, 3)
      ),
      (
        'weave_engine_sync_errors',
        'parent',
        payload.keyed_histograms.weave_engine_sync_errors,
        (1, 2, 3)
      ),
      (
        'web_permission_cleared',
        'content',
        payload.processes.content.keyed_histograms.web_permission_cleared,
        (1, 6, 7)
      ),
      (
        'web_permission_cleared',
        'parent',
        payload.keyed_histograms.web_permission_cleared,
        (1, 6, 7)
      ),
      (
        'webext_background_page_load_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_background_page_load_ms_by_addonid,
        (1, 60000, 100)
      ),
      (
        'webext_browseraction_popup_open_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_browseraction_popup_open_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_browseraction_popup_preload_result_count_by_addonid',
        'parent',
        payload.keyed_histograms.webext_browseraction_popup_preload_result_count_by_addonid,
        (1, 50, 51)
      ),
      (
        'webext_content_script_injection_ms_by_addonid',
        'content',
        payload.processes.content.keyed_histograms.webext_content_script_injection_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_content_script_injection_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_content_script_injection_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_extension_startup_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_extension_startup_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_pageaction_popup_open_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_pageaction_popup_open_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_storage_local_get_ms_by_addonid',
        'content',
        payload.processes.content.keyed_histograms.webext_storage_local_get_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_storage_local_get_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_storage_local_get_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_storage_local_idb_get_ms_by_addonid',
        'content',
        payload.processes.content.keyed_histograms.webext_storage_local_idb_get_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_storage_local_idb_get_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_storage_local_idb_get_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_storage_local_idb_set_ms_by_addonid',
        'content',
        payload.processes.content.keyed_histograms.webext_storage_local_idb_set_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_storage_local_idb_set_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_storage_local_idb_set_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_storage_local_set_ms_by_addonid',
        'content',
        payload.processes.content.keyed_histograms.webext_storage_local_set_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_storage_local_set_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_storage_local_set_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_user_script_injection_ms_by_addonid',
        'content',
        payload.processes.content.keyed_histograms.webext_user_script_injection_ms_by_addonid,
        (1, 50000, 100)
      ),
      (
        'webext_user_script_injection_ms_by_addonid',
        'parent',
        payload.keyed_histograms.webext_user_script_injection_ms_by_addonid,
        (1, 50000, 100)
      )
    ] AS metrics
  FROM
    sampled_data
),
flattened_metrics AS (
  SELECT
    submission_date,
    sample_id,
    client_id,
    os,
    app_version,
    app_build_id,
    channel,
    process,
    metrics.name AS metric,
    bucket_range,
    value.key AS key,
    value.value AS value
  FROM
    grouped_metrics
  CROSS JOIN
    UNNEST(metrics) AS metrics
  CROSS JOIN
    UNNEST(metrics.value) AS value
),
aggregated AS (
  SELECT
    submission_date,
    sample_id,
    client_id,
    os,
    app_version,
    app_build_id,
    channel,
    process,
    metric,
    key,
    ARRAY_AGG(bucket_range) AS bucket_range,
    ARRAY_AGG(value) AS value
  FROM
    flattened_metrics
  GROUP BY
    sample_id,
    client_id,
    submission_date,
    os,
    app_version,
    app_build_id,
    channel,
    process,
    metric,
    key
)
SELECT
  submission_date,
  sample_id,
  client_id,
  os,
  app_version,
  app_build_id,
  channel,
  ARRAY_AGG(
    STRUCT<
      metric STRING,
      metric_type STRING,
      key STRING,
      process STRING,
      agg_type STRING,
      bucket_range STRUCT<first_bucket INT64, last_bucket INT64, num_buckets INT64>,
      value ARRAY<STRUCT<key STRING, value INT64>>
    >(
      metric,
      udf_get_histogram_type(value),
      key,
      process,
      'summed_histogram',
      bucket_range[OFFSET(0)],
      udf_aggregate_json_sum(value)
    )
  ) AS histogram_aggregates
FROM
  aggregated
GROUP BY
  sample_id,
  client_id,
  submission_date,
  os,
  app_version,
  app_build_id,
  channel
