-- Generated by bqetl generate firefox_crashes
CREATE OR REPLACE VIEW
  `{{ project_id }}.{{ dataset }}.crash_live`
AS
{% for source in sources %}
  SELECT
    {% if source.normalized_app_id %}
      "{{ source.normalized_app_id }}" AS normalized_app_id,
    {% endif %}
    {{ source.channel_expression }}
    {{ source.fields }},
  FROM
    `{{ source.table }}`
  {% if not loop.last %}
    UNION ALL
  {% endif %}
{% endfor %}
