-- Query generated by: templates/unnest_parquet_view.sql.py telemetry_core_parquet_v3 telemetry_derived.telemetry_core_parquet_v3
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.telemetry.telemetry_core_parquet_v3` AS
SELECT
  submission_date AS submission_date_s3,
  * REPLACE (
    ARRAY(SELECT * FROM UNNEST(accessibility_services.list)) AS accessibility_services,
    ARRAY(SELECT * FROM UNNEST(experiments.list)) AS experiments,
    searches.key_value AS searches
  )
FROM
  `moz-fx-data-derived-datasets.telemetry_derived.telemetry_core_parquet_v3`
