#!/bin/bash

export DATASET=${DATASET:-glam_etl_dev}
dir="$(dirname "$0")"

logical_app_ids=(
    "org_mozilla_fenix_glam_nightly"
    "org_mozilla_fenix_glam_beta"
    "org_mozilla_fenix_glam_release"
)

for logical_app_id in "${logical_app_ids[@]}"; do
    EXPORT_ONLY=true PRODUCT=$logical_app_id STAGE=incremental $dir/run_glam_sql
done