#!/bin/bash
# To be run in glam via:
#    docker-compose run server ./manage.py import_glean_aggs

set -e

src_project=${SRC_PROJECT:-glam-fenix-dev}
# TODO: glam-dev-bespoke-nonprod-dataops-mozgcp-net
dst_project=${DST_PROJECT:-$src_project}
dataset=${DATASET:-glam_etl_dev}
product=${PRODUCT?PRODUCT must be defined}
bucket_name=${BUCKET:-$dst_project}

bucket="gs://${bucket_name}"
gsutil ls "$bucket" > /dev/null

bq extract --destination_format CSV --noprint_header \
    "${src_project}:${dataset}.${product}__extract_probe_counts_v1" \
    "$bucket/glam-extract-${product}-*.csv"

bq extract --destination_format CSV --noprint_header \
    "${src_project}:${dataset}.${product}__extract_user_counts_v1" \
    "$bucket/glam-extract-${product}-counts.csv"
