#!/bin/bash

set -e

cd "$(dirname "$0")/../.."

project=moz-fx-data-shared-prod
dataset=org_mozilla_fenix_stable
# e.g. baseline_v1
tables=$(bq ls --format=json $project:$dataset | \
        jq -r '.[] | .tableReference.tableId')

function write_sql {
    local table=$1
    local type=$2
    local directory="sql/glam_etl/fenix_clients_daily_${type}_aggregates_${table}"
    mkdir -p "$directory"
    python3 -m bigquery_etl.glam.glean_scalar_aggregates \
        --agg-type "$type" \
        --table-id "$dataset.$table" \
        > "$directory/query.sql"
    echo "generated $directory/query.sql"
}

for table in $tables; do
    write_sql "$table" scalars
    write_sql "$table" keyed_scalars
done

directory="sql/glam_etl/fenix_latest_versions_v1"
mkdir -p "$directory"
python -m bigquery_etl.glam.latest_versions \
    --source "${dataset}.baseline_v1" \
    > $directory/query.sql
echo "generated $directory/query.sql"

directory="sql/glam_etl/fenix_clients_scalar_aggregates_v1"
mkdir -p "$directory"
python -m bigquery_etl.glam.scalar_aggregates_incremental \
    --init \
    --ping-type glean \
    --destination glam_etl.fenix_clients_scalar_aggregates_v1 \
    > $directory/init.sql
echo "generated $directory/init.sql"

python -m bigquery_etl.glam.scalar_aggregates_incremental \
    --ping-type glean \
    --source glam_etl.fenix_clients_daily_scalar_aggregates_v1 \
    --destination glam_etl.fenix_clients_scalar_aggregates_v1 \
    > $directory/query.sql
echo "generated $directory/query.sql"
