#!/bin/bash
# Run the scalars sql job against all Glean pings in a product

set -x
set -e

cd "$(dirname "$0")/../.."

original_project=$(gcloud config get-value project)
function cleanup {
    gcloud config set project $original_project
}
trap cleanup EXIT

project=glam-fenix-dev
dataset=fenix_scalar_test

gcloud config set project $project
# force delete the dataset
bq rm -r -f $dataset
bq mk $dataset

tables=$(bq ls --format=json moz-fx-data-shared-prod:org_mozilla_fenix \
| jq -r '.[] | .tableReference.tableId')

for table in $tables; do
    tempfile=test.sql
    python3 -m bigquery_etl.glam.glean_scalar_aggregates \
        --table-id "org_mozilla_fenix.${table}" \
        --agg-type "scalars" \
        --no-parameterize > $tempfile
    bq query \
        --use_legacy_sql=false \
        --destination_table "$project:$dataset.$table" \
        < $tempfile
    rm $tempfile
done
