#!/bin/bash

set -e

cd "$(dirname "$0")/../.."

project=moz-fx-data-shared-prod
dataset=org_mozilla_fenix_stable
# e.g. baseline_v1
tables=$(bq ls --format=json $project:$dataset | \
        jq -r '.[] | .tableReference.tableId')

function write_scalars {
    local table=$1
    local directory="sql/glam_etl/${dataset/_stable/}__clients_daily_scalar_aggregates_${table}"
    mkdir -p "$directory"
    if ! python3 -m bigquery_etl.glam.clients_daily_scalar_aggregates \
        --source-table "$dataset.$table" \
        > "$directory/query.sql"; then
            echo "skipping $directory/query.sql: no probes found"
            rm -r "$directory"
    else
        echo "generated $directory/query.sql"
    fi
}

function write_histograms {
    local table=$1
    local directory="sql/glam_etl/${dataset/_stable/}__clients_daily_histogram_aggregates_${table}"
    mkdir -p "$directory"
    if ! python3 -m bigquery_etl.glam.clients_daily_histogram_aggregates \
        --source-table "$dataset.$table" \
        > "$directory/query.sql"; then
            echo "skipping $directory/query.sql: no probes found"
            rm -r "$directory"
    else
        echo "generated $directory/query.sql"
    fi
}

function write_clients_daily_aggregates {
    for table in $tables; do
        write_scalars "$table"
        write_histograms "$table"
    done
}

start_stage=${START_STAGE:-0}
if ((start_stage <= 0)); then
    write_clients_daily_aggregates;
fi
if ((start_stage <= 1)); then
    python3 -m bigquery_etl.glam.generate --prefix "${dataset/_stable/}"
fi
