CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.activity_stream.impression_stats`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.activity_stream_stable.impression_stats_v1`
