CREATE OR REPLACE FUNCTION norm.funnel_derived(
  channel STRING,
  os STRING,
  first_seen_date DATE,
  build_id STRING,
  attribution_source STRING,
  attribution_ua STRING,
  startup_profile_selection_reason STRING,
  distribution_id STRING
)
RETURNS STRING AS (
  CASE
    WHEN channel = 'release'
      AND LOWER(os) LIKE '%windows%'
      AND DATE_DIFF(-- Only use builds from the last month
        DATE(first_seen_date),
        SAFE.PARSE_DATE('%Y%m%d', SUBSTR(build_id, 0, 8)),
        WEEK
      ) <= 6
      AND attribution_source IS NOT NULL
      AND attribution_ua != 'firefox'
      AND attribution_ua IS NOT NULL
      AND startup_profile_selection_reason IN ('firstrun-created-default')
      AND (
        distribution_id IS NULL
        OR (
          distribution_id IN (
            'mozilla-win-eol-esr115',
            'mozilla-mac-eol-esr1',
            'mozilla-mac-eol-esr115'
          ) -- exclude ESR migrations
          OR distribution_id IN (
            'mozilla101',
            'mozilla102',
            'mozilla139',
            'mozilla138',
            'mozilla86',
            'mozilla116',
            'mozilla63',
            'mozilla88',
            'mozilla118',
            'mozilla134',
            'mozilla105',
            'mozilla94',
            'mozilla117',
            'mozilla14',
            'mozilla93',
            'mozilla15',
            'mozilla114',
            'mozilla104',
            'mozilla103',
            'mozilla111',
            'mozilla81',
            'mozilla50',
            'mozilla76',
            'mozilla113',
            'mozilla90',
            'mozilla80',
            'mozilla87',
            'mozilla97',
            'mozilla100',
            'mozilla77',
            'mozilla75',
            'mozilla78',
            'mozilla110',
            'mozilla52',
            'mozilla79',
            'mozilla106',
            'mozilla85',
            'mozilla53',
            'mozilla115',
            'mozilla112',
            'mozilla98',
            'mozilla99',
            'mozilla28',
            'mozilla12',
            'mozilla84',
            'mozilla11',
            'mozilla26',
            'mozilla68',
            'mozilla83',
            'mozilla91',
            'mozilla94-default',
            'mozilla121',
            'mozilla41',
            'mozilla92',
            'mozilla82',
            'mozilla96',
            'mozilla132',
            'mozilla67',
            'mozilla61',
            'mozilla13',
            'mozilla51',
            'mozilla19',
            'mozilla66',
            'mozilla131',
            'mozilla89',
            'mozilla104-utility-existing',
            'mozilla35',
            'mozilla130',
            'mozilla32',
            'mozilla120',
            'mozilla34',
            'mozilla38',
            'mozilla119',
            'mozilla36',
            'mozilla43',
            'mozilla21',
            'mozilla45',
            'mozilla95',
            'mozilla-cliqz-001',
            'mozilla60',
            'mozilla122',
            'mozilla25',
            'mozilla135',
            'mozilla102-no-thanks',
            'mozilla22',
            'mozilla-cliqz-008',
            'mozilla86-utility-existing',
            'mozilla-cliqz-005',
            'mozilla18',
            'mozilla40',
            'mozilla-cliqz-006'
          ) -- exclude known funnelcakes
        )
      )
      THEN 'mozorg windows funnel'
    WHEN distribution_id IS NOT NULL
      AND (
        distribution_id NOT IN (
          'mozilla-win-eol-esr115',
          'mozilla-mac-eol-esr1',
          'mozilla-mac-eol-esr115'
        ) -- exclude ESR migrations
        AND distribution_id NOT IN (
          'mozilla101',
          'mozilla102',
          'mozilla139',
          'mozilla138',
          'mozilla86',
          'mozilla116',
          'mozilla63',
          'mozilla88',
          'mozilla118',
          'mozilla134',
          'mozilla105',
          'mozilla94',
          'mozilla117',
          'mozilla14',
          'mozilla93',
          'mozilla15',
          'mozilla114',
          'mozilla104',
          'mozilla103',
          'mozilla111',
          'mozilla81',
          'mozilla50',
          'mozilla76',
          'mozilla113',
          'mozilla90',
          'mozilla80',
          'mozilla87',
          'mozilla97',
          'mozilla100',
          'mozilla77',
          'mozilla75',
          'mozilla78',
          'mozilla110',
          'mozilla52',
          'mozilla79',
          'mozilla106',
          'mozilla85',
          'mozilla53',
          'mozilla115',
          'mozilla112',
          'mozilla98',
          'mozilla99',
          'mozilla28',
          'mozilla12',
          'mozilla84',
          'mozilla11',
          'mozilla26',
          'mozilla68',
          'mozilla83',
          'mozilla91',
          'mozilla94-default',
          'mozilla121',
          'mozilla41',
          'mozilla92',
          'mozilla82',
          'mozilla96',
          'mozilla132',
          'mozilla67',
          'mozilla61',
          'mozilla13',
          'mozilla51',
          'mozilla19',
          'mozilla66',
          'mozilla131',
          'mozilla89',
          'mozilla104-utility-existing',
          'mozilla35',
          'mozilla130',
          'mozilla32',
          'mozilla120',
          'mozilla34',
          'mozilla38',
          'mozilla119',
          'mozilla36',
          'mozilla43',
          'mozilla21',
          'mozilla45',
          'mozilla95',
          'mozilla-cliqz-001',
          'mozilla60',
          'mozilla122',
          'mozilla25',
          'mozilla135',
          'mozilla102-no-thanks',
          'mozilla22',
          'mozilla-cliqz-008',
          'mozilla86-utility-existing',
          'mozilla-cliqz-005',
          'mozilla18',
          'mozilla40',
          'mozilla-cliqz-006'
        ) -- exclude known funnelcakes
      )
      THEN 'partner'
    ELSE 'other'
);
