fields:
- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: first_seen_date
- mode: NULLABLE
  name: installer_type
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: installer_type
- mode: NULLABLE
  name: nbr_rows
  type: INTEGER
  description: Count of Rows in Clients Last Seen for These New Profiles for First 7 Days
- mode: NULLABLE
  name: new_profiles
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: new_profiles
- mode: NULLABLE
  name: sum_active_days_bit_count_for_new_profiles
  type: INTEGER
  description: The sum of the "days active bits" in the next 7 days for these new profiles
- mode: NULLABLE
  name: ratio_of_np_days_active_bits_vs_np_first_7_days
  type: FLOAT
  description: Calculated as sum_active_days_bit_count_for_new_profiles divided by new_profiles
