#!/usr/bin/env python3

"""Format SQL."""

from argparse import ArgumentParser
import os
import os.path
import sys

# sys.path needs to be modified to enable package imports from parent
# and sibling directories. Also see:
# https://stackoverflow.com/questions/6323860/sibling-package-imports/23542795#23542795
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from bigquery_etl.format_sql.formatter import reformat  # noqa E402

parser = ArgumentParser(description=__doc__)
parser.add_argument(
    "paths",
    metavar="PATH",
    nargs="*",
    help="file or directory to format;"
    " directories will be recursively searched for .sql files",
)


def main():
    paths = parser.parse_args().paths
    if not paths:
        if sys.stdin.isatty():
            print(
                "Error: must pipe to stdin or provide a list of files"
                " and directories as arguments",
                file=sys.stderr,
            )
            sys.exit(1)
        print(reformat(sys.stdin.read()))
    else:
        sql_files = []
        for path in paths:
            if os.path.isdir(path):
                sql_files.extend(
                    os.path.join(dirpath, filename)
                    for dirpath, _, filenames in os.walk(path)
                    for filename in filenames
                    if filename.endswith(".sql")
                )
            else:
                sql_files.append(path)
        modified = 0
        for path in sql_files:
            with open(path) as fp:
                query = fp.read()
            formatted = reformat(query)
            if query != formatted:
                print(f"modified {path}")
                with open(path, "w") as fp:
                    fp.write(formatted)
                    fp.write("\n")
                modified += 1
        print(f"{modified} file(s) modified")
        if modified:
            sys.exit(1)


if __name__ == "__main__":
    main()
