#!/usr/bin/env python3

"""Format SQL."""

from argparse import ArgumentParser
import os
import os.path
import sys

# sys.path needs to be modified to enable package imports from parent
# and sibling directories. Also see:
# https://stackoverflow.com/questions/6323860/sibling-package-imports/23542795#23542795
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from bigquery_etl.format_sql.formatter import reformat  # noqa E402


SKIP = {
    # files that existed before we started to enforce this script
    "udf/active_n_weeks_ago.sql",
    "udf/add_monthly_engine_searches.sql",
    "udf/add_monthly_searches.sql",
    "udf/aggregate_search_map.sql",
    "udf/array_11_zeroes_then.sql",
    "udf/array_drop_first_and_append.sql",
    "udf/array_of_12_zeroes.sql",
    "udf/bitcount_lowest_7.sql",
    "udf/bitmask_365.sql",
    "udf/bitmask_lowest_28.sql",
    "udf/bitmask_lowest_7.sql",
    "udf/bitmask_range.sql",
    "udf/bits_to_days_seen.sql",
    "udf/bits_to_days_since_first_seen.sql",
    "udf/bits_to_days_since_seen.sql",
    "udf/bool_to_365_bits.sql",
    "udf/coalesce_adjacent_days_28_bits.sql",
    "udf/coalesce_adjacent_days_365_bits.sql",
    "udf/combine_adjacent_days_28_bits.sql",
    "udf/combine_adjacent_days_365_bits.sql",
    "udf/combine_experiment_days.sql",
    "udf/country_code_to_flag.sql",
    "udf/days_seen_bytes_to_rfm.sql",
    "udf/days_since_created_profile_as_28_bits.sql",
    "udf/deanonymize_event.sql",
    "udf/decode_int64.sql",
    "udf/dedupe_array.sql",
    "udf/extract_count_histogram_value.sql",
    "udf/extract_document_type.sql",
    "udf/extract_document_version.sql",
    "udf/get_key_with_null.sql",
    "udf/glean_timespan_nanos.sql",
    "udf/glean_timespan_seconds.sql",
    "udf/int_to_365_bits.sql",
    "udf/int_to_hex_string.sql",
    "udf/json_extract_histogram.sql",
    "udf/keyed_histogram_get_sum.sql",
    "udf/kv_array_to_json_string.sql",
    "udf/mode_last.sql",
    "udf/new_monthly_engine_searches_struct.sql",
    "udf/normalize_glean_ping_info.sql",
    "udf/normalize_metadata.sql",
    "udf/normalize_search_engine.sql",
    "udf/one_as_365_bits.sql",
    "udf/parse_desktop_telemetry_uri.sql",
    "udf/parse_iso8601_date.sql",
    "udf/pos_of_leading_set_bit.sql",
    "udf/pos_of_trailing_set_bit.sql",
    "udf/round_timestamp_to_minute.sql",
    "udf/shift_28_bits_one_day.sql",
    "udf/shift_365_bits_one_day.sql",
    "udf/shift_one_day.sql",
    "udf/smoot_usage_from_28_bits.sql",
    "udf/vector_add.sql",
    "udf/zero_as_365_bits.sql",
    "udf/zeroed_array.sql",
    "udf_js/crc32.sql",
    "udf_js/gunzip.sql",
    "udf_js/jackknife_mean_ci.sql",
    "udf_js/jackknife_ratio_ci.sql",
    "udf_js/jackknife_sum_ci.sql",
    "udf_js/json_extract_events.sql",
    "udf_js/json_extract_histogram.sql",
    "udf_js/json_extract_keyed_histogram.sql",
    "udf_js/json_extract_missing_cols.sql",
    "udf_js/sample_id.sql",
    "udf_legacy/contains.sql",
    "udf_legacy/date_format.sql",
    "udf_legacy/date_trunc.sql",
    "udf_legacy/to_iso8601.sql",
    "stored_procedures/safe_crc32_uuid.sql",
}

parser = ArgumentParser(description=__doc__)
parser.add_argument(
    "paths",
    metavar="PATH",
    nargs="*",
    help="file or directory to format;"
    " if not specified read from stdin and write to stdout;"
    " recursively search directories for .sql files",
)
parser.add_argument(
    "--check",
    action="store_true",
    help="do not write changes, just return status;"
    " return code 0 indicates nothing would change;"
    " return code 1 indicates some files would be reformatted",
)


def main():
    args = parser.parse_args()
    if not args.paths:
        if sys.stdin.isatty():
            parser.print_help()
            print("Error: must specify PATH or provide input via stdin")
            sys.exit(255)
        query = sys.stdin.read()
        formatted = reformat(query) + "\n"
        if not args.check:
            print(formatted, end="")
        if args.check and query != formatted:
            sys.exit(1)
    else:
        sql_files = []
        for path in args.paths:
            if os.path.isdir(path):
                sql_files.extend(
                    filepath
                    for dirpath, _, filenames in os.walk(path)
                    for filename in filenames
                    if filename.endswith(".sql")
                    # skip tests/**/input.sql
                    and not (path.startswith("tests") and filename == "input.sql")
                    for filepath in [os.path.join(dirpath, filename)]
                    if filepath not in SKIP
                )
            elif path:
                sql_files.append(path)
        if not sql_files:
            print("Error: no files were found to format")
            sys.exit(255)
        sql_files.sort()
        reformatted = unchanged = 0
        for path in sql_files:
            with open(path) as fp:
                query = fp.read()
            formatted = reformat(query) + "\n"
            if query != formatted:
                if args.check:
                    print(f"would reformat {path}")
                else:
                    with open(path, "w") as fp:
                        fp.write(formatted)
                    print(f"reformatted {path}")
                reformatted += 1
            else:
                unchanged += 1
        print(
            ", ".join(
                f"{number} file{'s' if number > 1 else ''}"
                f"{' would be' if args.check else ''} {msg}"
                for number, msg in [
                    (reformatted, "reformatted"),
                    (unchanged, "left unchanged"),
                ]
                if number > 0
            )
            + "."
        )
        if args.check and reformatted:
            sys.exit(1)


if __name__ == "__main__":
    main()
