#!/bin/bash

# DEPRECATED

# Jenkins calls generate_all_views as part of its view publishing logic.
# This script has been renamed to generate_sql since it also generates
# some table queries. We maintain this script as an alias to generate_sql.

cd "$(dirname "$0")/.."

exec ./script/generate_sql "$@"
