#!/bin/bash

# This script should call all routines that generate SQL, and is used
# as the source of truth for what ends up in the published generated-sql branch.
# Jenkins also calls this script as part of publishing views;
# eventually Jenkins will use the generated-sql branch directly.

set -e

: "${TARGET_PROJECT:=moz-fx-data-shar-nonprod-efed}"
: "${SQL_DIR:=sql}"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --target-project)
    TARGET_PROJECT="$2"
    shift # past argument
    shift # past value
    ;;
    --sql-dir)
    SQL_DIR="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    echo "ERROR: Unknown option: $1" >&2
    exit 1
    ;;
esac
done

set -x

# Fill in any missing view definitions in the target project folder
python -m bigquery_etl.view.generate_stable_views \
    --target-project "${TARGET_PROJECT}" \
    --sql-dir "${SQL_DIR}" \
    --parallelism=20

# Fill in definitions for generated Glean ETL
PLACEHOLDER_DATE="2000-01-01"
./script/run_glean_baseline_clients_daily \
    --project-id "${TARGET_PROJECT}" \
    --output-dir "${SQL_DIR}/${TARGET_PROJECT}" \
    --output-only \
    --date="${PLACEHOLDER_DATE}"
./script/run_glean_baseline_clients_last_seen \
    --project-id "${TARGET_PROJECT}" \
    --output-dir "${SQL_DIR}/${TARGET_PROJECT}" \
    --output-only \
    --date="${PLACEHOLDER_DATE}"

# Record dependencies in yaml files
./script/bqetl dependency record "${SQL_DIR}"
