#!/bin/sh

# DEPRECATED in favor of generate_stable_views. This module will be removed
# once ops logic transitions to use the new module.
#
# Generate one view definition file per document type in '_stable' tables.
#
# If there are existing view definitions in the destination directory then those will be
# kept instead.
#
# Run as:
#   ./script/generate_views 'moz-fx-data-shared-prod:*_stable.*'

cd "$(dirname "$0")/.."

exec python3 -m bigquery_etl.view.generate_views "$@"
