#!/bin/sh

# Generate documentation for projects.
#
# Currently only supports generating documentation for the mozfun project.


cd "$(dirname "$0")/.."

exec python3 -m bigquery_etl.docs.generate_docs "$@"
