#!/usr/bin/env python3

"""Update metadata of BigQuery tables and views."""

from argparse import ArgumentParser
import logging
import os
import yaml
import re

from google.cloud import bigquery


METADATA_FILE = "metadata.yaml"


def is_valid_label(label):
    """
    Check if a label has the right format:
    Only hyphens (-), underscores (_), lowercase characters, and numbers are allowed.
    International characters are allowed.
    """
    return re.match(r"[\w\d_-]+", label)


def publish_metadata(client, dataset, table, metadata_file):
    with open(metadata_file, "r") as yaml_stream:
        try:
            metadata = yaml.safe_load(yaml_stream)
            table_ref = client.dataset(dataset).table(table)
            table = client.get_table(table_ref)

            if "friendly_name" in metadata:
                table.friendly_name = metadata["friendly_name"]

            if "description" in metadata:
                table.description = metadata["description"]

            if "labels" in metadata:
                table.labels = {}

                for key, label in metadata["labels"].items():
                    if isinstance(label, bool) and is_valid_label(str(key)):
                        # key-value pair with boolean value should get published as tag
                        if label:
                            table.labels[str(key)] = ""
                    elif is_valid_label(str(key)) and is_valid_label(str(label)):
                        # all other pairs get published as key-value pair label
                        table.labels[str(key)] = str(label)
                    else:
                        print(
                            """
                            Invalid label format: {}: {}. Only hyphens (-),
                            underscores (_), lowercase characters, and numbers
                            are allowed. International characters are allowed.
                            """.format(
                                key, label
                            )
                        )

            client.update_table(table, ["friendly_name", "description", "labels"])
        except yaml.YAMLError as e:
            print(e)


def main():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--project-id", help="Default project")
    parser.add_argument(
        "--target", nargs="+", help="File or directory containing metadata files"
    )

    parser.add_argument("--log-level", default="INFO", help="Defaults to INFO")

    args = parser.parse_args()
    client = bigquery.Client(args.project_id)

    # set log level
    try:
        logging.basicConfig(level=args.log_level, format="%(levelname)s %(message)s")
    except ValueError as e:
        parser.error(f"argument --log-level: {e}")

    for target in args.target:
        if os.path.isdir(target):
            for root, dirs, files in os.walk(target):
                if METADATA_FILE in files:
                    path = os.path.normpath(root)
                    dataset = path.split(os.sep)[-2]
                    table = path.split(os.sep)[-1]
                    metadata_file = os.path.join(root, METADATA_FILE)

                    publish_metadata(client, dataset, table, metadata_file)
        else:
            print(
                """
                Invalid target: {}, target must be a directory with
                structure /<dataset>/<table>/metadata.yaml.
                """.format(
                    args.target
                )
            )


if __name__ == "__main__":
    main()
