#!/bin/sh

# Publish UDFs to the public mozfun project.

cd "$(dirname "$0")/.."

exec python3 -m bigquery_etl.routine.publish_routines --project_id=mozfun \
    --dependency_dir=lib/ --gcs-bucket=mozfun --target=sql/mozfun --public=True "$@"
