#!/bin/sh

# Publish UDFs to the public mozfun project.

cd "$(dirname "$0")/.."

exec python3 -m bigquery_etl.udf.publish_udfs --project_id=mozfun --udf-dirs=mozfun \
    --dependency_dir=lib/ --gcs-bucket=mozfun --public=True "$@"
