#!/bin/bash

## Runs or writes out generated baseline_clients_last_seen queries for all Glean applications.
## Example:
##   ./script/run_glean_baseline_clients_last_seen --project-id moz-fx-data-shared-prod --date 2020-03-01 --only 'org_mozilla_firefox_stable.baseline_v1' --output-dir sql/moz-fx-data-shared-prod/ --dry-run

exec python3 -m bigquery_etl.glean_usage.baseline_clients_last_seen "$@"
