#!/bin/sh

# Writes multiple queries to temporary tables and then joins the results.

# This is useful for queries that BigQuery deems too complex to run, usually due
# to using a large number of subqueries; this pattern allows you to materialize
# subsets of columns in multiple different queries so that they stay under the
# complexity limit, and then join those results to generate a final wide result.

# The query files must be in the same directory and all be prefixed with `part`.

exec python3 -m bigquery_etl.run_multipart_query "$@"
