#!/bin/bash

## Updates example queries that are checked into the default branch for testing.

cd "$(dirname "$0")/.."

./script/run_glean_baseline_clients_first_seen \
    --project-id moz-fx-data-shared-prod \
    --date 2021-03-01 \
    --only 'org_mozilla_fenix_stable.baseline_v1' \
    --output-dir sql/moz-fx-data-shared-prod/ \
    --dry-run

./script/run_glean_baseline_clients_first_seen \
    --project-id moz-fx-data-shared-prod \
    --date 2021-03-01 \
    --only 'org_mozilla_ios_firefox_stable.baseline_v1' \
    --output-dir sql/moz-fx-data-shared-prod/ \
    --dry-run

# remove some views that can't be tested and are useless checked in
rm -r sql/moz-fx-data-shared-prod/org_mozilla_fenix/baseline_clients_first_seen
rm -r sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox/baseline_clients_first_seen
