#!/bin/bash

## Updates example queries that are checked into the default branch for testing.

set -e

cd "$(dirname "$0")/.."

./bqetl bootstrap
./bqetl generate glean_usage --only 'org_mozilla_fenix_stable.baseline_v1' \
    --project-id moz-fx-data-shared-prod

./bqetl generate glean_usage --only 'org_mozilla_ios_firefox_stable.baseline_v1' \
    --project-id moz-fx-data-shared-prod

wait
trap - EXIT
