type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Marketing Metrics
    notification_channels:
    - slack: '#marketing-data-alerts'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefoxdotcom_derived.fbclid_desktop_conversion_events_v1.submission_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefoxdotcom_derived.fbclid_desktop_conversion_events_v1.activity_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefoxdotcom_derived.fbclid_desktop_conversion_events_v1.fbclid
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefoxdotcom_derived.fbclid_desktop_conversion_events_v1.ga_country
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefoxdotcom_derived.fbclid_desktop_conversion_events_v1.conversion_name
    metrics:
    - saved_metric_id: is_not_null
      lookback:
        lookback_window:
          interval_type: DAYS
          interval_value: 4
        lookback_type: DATA_TIME
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefoxdotcom_derived.fbclid_desktop_conversion_events_v1.*
    metrics:
    - saved_metric_id: composite_key_uniqueness_2_column
      metric_name: composite_key_uniqueness_2_column
      parameters:
      - key: col_1
        column_name: fbclid
      - key: col_1_string
        string_value: fbclid
      - key: col_2
        column_name: conversion_name
      - key: col_2_string
        string_value: conversion_name
      - key: table
        string_value: moz-fx-data-shared-prod.firefoxdotcom_derived.fbclid_desktop_conversion_events_v1
      lookback:
        lookback_window:
          interval_type: DAYS
          interval_value: 28
        lookback_type: DATA_TIME
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefoxdotcom_derived.fbclid_desktop_conversion_events_v1.*
    metrics:
    - saved_metric_id: volume
    - saved_metric_id: freshness
