-- UDF to map SUMO product slug to canonical product name
-- Single source of truth for product mapping across all SUMO queries
-- Used by: SSSR queries, GA4 analytics, content quality metrics
CREATE OR REPLACE FUNCTION sumo.map_product_slug(product_slug STRING) AS (
  CASE
    product_slug
    WHEN '/firefox/'
      THEN 'firefox'
    WHEN '/thunderbird/'
      THEN 'thunderbird'
    WHEN '/mobile/'
      THEN 'firefox-android'
    WHEN '/pocket/'
      THEN 'pocket'
    WHEN '/ios/'
      THEN 'firefox-ios'
    WHEN '/firefox/mozilla-account/'
      THEN 'mozilla-account'
    WHEN '/firefox/mobile/'
      THEN 'firefox-android'
    WHEN '/mozilla-account/'
      THEN 'mozilla-account'
    WHEN '/firefox-enterprise/'
      THEN 'firefox-enterprise'
    WHEN '/focus-firefox/'
      THEN 'focus'
    WHEN '/mozilla-vpn/'
      THEN 'mozilla-vpn'
    WHEN '/firefox/ios/mobile/mozilla-account/'
      THEN 'mozilla-account'
    WHEN '/monitor/'
      THEN 'monitor'
    WHEN '/relay/'
      THEN 'relay'
    WHEN '/firefox/ios/mobile/'
      THEN 'firefox'
    WHEN '/firefox-lockwise/mobile/mozilla-account/'
      THEN 'mozilla-account'
    WHEN '/firefox-private-network-vpn/'
      THEN 'mozilla-vpn'
    WHEN '/ios/mobile/'
      THEN 'firefox-android'
    WHEN '/thunderbird-android/'
      THEN 'thunderbird-android'
    WHEN '/firefox-reality/'
      THEN 'firefox-reality'
    WHEN '/mozilla-account/privacy-and-security/'
      THEN 'mozilla-account'
    WHEN '/firefox/focus-firefox/ios/mobile/'
      THEN 'firefox'
    WHEN '/firefox/monitor/'
      THEN 'monitor'
    WHEN '/hubs/'
      THEN 'hubs'
    WHEN '/firefox/pocket/'
      THEN 'pocket'
    WHEN '/firefox-preview/'
      THEN 'firefox-preview'
    WHEN '/firefox/relay/'
      THEN 'relay'
    WHEN '/ios/mozilla-account/'
      THEN 'mozilla-account'
    WHEN '/firefox-lite/'
      THEN 'firefox-lite'
    WHEN '/thunderbird/thunderbird-android/'
      THEN 'thunderbird'
    WHEN '/firefox/privacy-and-security/'
      THEN 'firefox'
    WHEN '/mdn-plus/'
      THEN 'mdn-plus'
    WHEN '/firefox/firefox-enterprise/'
      THEN 'firefox-enterprise'
    WHEN '/firefox-android-esr/'
      THEN 'firefox-android-esr'
    WHEN '/firefox/thunderbird/'
      THEN 'thunderbird'
    WHEN '/firefox/firefox-private-network-vpn/'
      THEN 'mozilla-vpn'
    WHEN '/mozilla-account/mozilla-vpn/'
      THEN 'mozilla-account'
    WHEN '/firefox/mozilla-vpn/'
      THEN 'mozilla-vpn'
    WHEN '/firefox-lockwise/'
      THEN 'lockwise'
    WHEN '/klar/'
      THEN 'klar'
    ELSE 'other'
  END
);

-- Tests
SELECT
  assert.equals('firefox', sumo.map_product_slug('/firefox/')),
  assert.equals('mozilla-vpn', sumo.map_product_slug('/mozilla-vpn/')),
  assert.equals('lockwise', sumo.map_product_slug('/firefox-lockwise/')),
  assert.equals('other', sumo.map_product_slug('/unknown-product/'))
