fields:
- name: active_date
  type: DATE
  mode: NULLABLE
- name: plan_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: plan_id
- name: country
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: country
- name: country_name
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_country_name
- name: provider
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_provider
- name: plan_amount
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_plan_amount
- name: plan_currency
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_plan_currency
- name: plan_interval
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_plan_interval
- name: plan_interval_count
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_plan_interval_count
- name: product_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_last_transaction_product_id
- name: product_name
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: subscription_product_name
- name: pricing_plan
  type: STRING
  mode: NULLABLE
- name: promotion_codes
  type: STRING
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: promotion_codes
- name: promotion_discounts_amount
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/subscription_platform_derived/subscription_platform_derived.yaml
    field: promotion_discounts_amount
- name: count
  type: INTEGER
  mode: NULLABLE
