-- Query generated by: templates/clients_daily_histogram_aggregates.sql.py

CREATE TEMPORARY FUNCTION get_keyval_pairs(y STRING)
RETURNS ARRAY<STRING>
LANGUAGE js AS
'''
  var z = new Array();
  node = JSON.parse(y);
  Object.keys(node).map(function(key) {
    value = node[key].toString();
    z.push(key + ":" + value);
  });
  return z
''';



-- convert a string like '[5, 6, 7]' to an array struct
CREATE TEMPORARY FUNCTION string_to_arr(y STRING)
RETURNS ARRAY<STRING>
LANGUAGE js AS
'''
  return JSON.parse(y);
''';


CREATE TEMP FUNCTION udf_get_bucket_range(histograms ARRAY<STRING>) AS ((
  WITH buckets AS (
    SELECT
      string_to_arr(JSON_EXTRACT(histogram, "$.range")) AS bucket_range,
      CAST(JSON_EXTRACT(histogram, "$.bucket_count") AS INT64) AS num_buckets
    FROM UNNEST(histograms) AS histogram
    WHERE histogram IS NOT NULL
    LIMIT 1
  )

  SELECT AS STRUCT
    CAST(bucket_range[OFFSET(0)] AS INT64) AS first_bucket,
    CAST(bucket_range[OFFSET(1)] AS INT64) AS last_bucket,
    num_buckets
  FROM
    buckets));


CREATE TEMP FUNCTION udf_get_histogram_type(histograms ARRAY<STRING>) AS ((
    SELECT
      CASE CAST(JSON_EXTRACT(histogram, "$.histogram_type") AS INT64)
        WHEN 0 THEN 'histogram-exponential'
        WHEN 1 THEN 'histogram-linear'
        WHEN 2 THEN 'histogram-boolean'
        WHEN 3 THEN 'histogram-flag'
        WHEN 4 THEN 'histogram-count'
        WHEN 5 THEN 'histogram-categorical'
      END AS histogram_type
    FROM UNNEST(histograms) AS histogram
    WHERE histogram IS NOT NULL
    LIMIT 1
));

CREATE TEMP FUNCTION
  udf_aggregate_json_sum(histograms ARRAY<STRING>) AS (ARRAY(
      SELECT
        AS STRUCT SPLIT(keyval, ':')[OFFSET(0)] AS key,
        SUM(CAST(SPLIT(keyval, ':')[OFFSET(1)] AS INT64)) AS value
      FROM
        UNNEST(histograms) AS histogram,
        UNNEST(get_keyval_pairs(JSON_EXTRACT(histogram, "$.values"))) AS keyval
      WHERE histogram IS NOT NULL
      GROUP BY key));

WITH
  -- normalize client_id and rank by document_id
  numbered_duplicates AS (
    SELECT
        ROW_NUMBER() OVER (
            PARTITION BY
                client_id,
                submission_timestamp,
                document_id
            ORDER BY submission_timestamp
            ASC
        ) AS _n,
        * REPLACE(LOWER(client_id) AS client_id)
    FROM `moz-fx-data-shar-nonprod-efed.telemetry_live.main_v4`
    WHERE DATE(submission_timestamp) = @submission_date
    AND application.channel in (
        "release", "esr", "beta", "aurora", "default", "nightly"
    )
    AND client_id IS NOT NULL
  ),


-- Deduplicating on document_id is necessary to get valid SUM values.
deduplicated AS (
    SELECT * EXCEPT (_n)
    FROM numbered_duplicates
    WHERE _n = 1
),


grouped_metrics AS
  (select
    submission_timestamp,
    DATE(submission_timestamp) as submission_date,
    client_id,
    normalized_os as os,
    SPLIT(application.version, '.')[OFFSET(0)] AS app_version,
    application.build_id AS app_build_id,
    normalized_channel AS channel,
    ARRAY<STRUCT<
        name STRING,
        value ARRAY<STRUCT<key STRING, value STRING>>
    >>[
      ('search_counts', payload.keyed_histograms.search_counts),
      ('fx_migration_bookmarks_quantity', payload.keyed_histograms.fx_migration_bookmarks_quantity),
      ('fx_migration_logins_import_ms', payload.keyed_histograms.fx_migration_logins_import_ms),
      ('js_telemetry_addon_exceptions', payload.keyed_histograms.js_telemetry_addon_exceptions),
      ('devtools_webide_connected_runtime_app_type', payload.keyed_histograms.devtools_webide_connected_runtime_app_type),
      ('blocked_on_plugin_module_init_ms', payload.keyed_histograms.blocked_on_plugin_module_init_ms),
      ('addon_forbidden_cpow_usage', payload.keyed_histograms.addon_forbidden_cpow_usage),
      ('content_signature_verification_errors', payload.keyed_histograms.content_signature_verification_errors),
      ('webext_content_script_injection_ms_by_addonid', payload.keyed_histograms.webext_content_script_injection_ms_by_addonid),
      ('fx_startup_migration_undo_logins_errorcount', payload.keyed_histograms.fx_startup_migration_undo_logins_errorcount),
      ('fx_migration_bookmarks_import_ms', payload.keyed_histograms.fx_migration_bookmarks_import_ms),
      ('webext_extension_startup_ms_by_addonid', payload.keyed_histograms.webext_extension_startup_ms_by_addonid),
      ('blocked_on_plugin_instance_init_ms', payload.keyed_histograms.blocked_on_plugin_instance_init_ms),
      ('hsts_priming_request_duration', payload.keyed_histograms.hsts_priming_request_duration),
      ('update_check_extended_error_external', payload.keyed_histograms.update_check_extended_error_external),
      ('memory_distribution_among_content', payload.keyed_histograms.memory_distribution_among_content),
      ('sandbox_rejected_syscalls', payload.keyed_histograms.sandbox_rejected_syscalls),
      ('webext_pageaction_popup_open_ms_by_addonid', payload.keyed_histograms.webext_pageaction_popup_open_ms_by_addonid),
      ('webext_storage_local_get_ms_by_addonid', payload.keyed_histograms.webext_storage_local_get_ms_by_addonid),
      ('video_inter_keyframe_max_ms', payload.keyed_histograms.video_inter_keyframe_max_ms),
      ('sandbox_failed_launch_keyed', payload.keyed_histograms.sandbox_failed_launch_keyed),
      ('fx_startup_migration_undo_total_ms', payload.keyed_histograms.fx_startup_migration_undo_total_ms),
      ('fx_migration_logins_jank_ms', payload.keyed_histograms.fx_migration_logins_jank_ms),
      ('blocked_on_plugin_stream_init_ms', payload.keyed_histograms.blocked_on_plugin_stream_init_ms),
      ('presshell_reqs_per_layout_flush', payload.keyed_histograms.presshell_reqs_per_layout_flush),
      ('service_worker_fetch_event_finish_synthesized_response_ms', payload.keyed_histograms.service_worker_fetch_event_finish_synthesized_response_ms),
      ('main_thread_runnable_ms', payload.keyed_histograms.main_thread_runnable_ms),
      ('dom_script_src_encoding', payload.keyed_histograms.dom_script_src_encoding),
      ('devtools_webide_connected_runtime_os', payload.keyed_histograms.devtools_webide_connected_runtime_os),
      ('refresh_driver_tick_phase_weight', payload.keyed_histograms.refresh_driver_tick_phase_weight),
      ('fx_migration_bookmarks_jank_ms', payload.keyed_histograms.fx_migration_bookmarks_jank_ms),
      ('ipc_write_main_thread_latency_ms', payload.keyed_histograms.ipc_write_main_thread_latency_ms),
      ('content_js_background_tick_delay_events_ms', payload.keyed_histograms.content_js_background_tick_delay_events_ms),
      ('service_worker_fetch_event_dispatch_ms', payload.keyed_histograms.service_worker_fetch_event_dispatch_ms),
      ('fx_tab_remote_navigation_delay_ms', payload.keyed_histograms.fx_tab_remote_navigation_delay_ms),
      ('opengl_compositing_failure_id', payload.keyed_histograms.opengl_compositing_failure_id),
      ('webext_storage_local_idb_get_ms_by_addonid', payload.keyed_histograms.webext_storage_local_idb_get_ms_by_addonid),
      ('blocked_on_pluginasyncsurrogate_waitforinit_ms', payload.keyed_histograms.blocked_on_pluginasyncsurrogate_waitforinit_ms),
      ('qm_init_telemetry_error', payload.keyed_histograms.qm_init_telemetry_error),
      ('ipc_read_main_thread_latency_ms', payload.keyed_histograms.ipc_read_main_thread_latency_ms),
      ('video_inferred_decode_suspend_percentage', payload.keyed_histograms.video_inferred_decode_suspend_percentage),
      ('fx_urlbar_selected_result_index_by_type', payload.keyed_histograms.fx_urlbar_selected_result_index_by_type),
      ('popup_notification_stats', payload.keyed_histograms.popup_notification_stats),
      ('http_traffic_analysis_3', payload.keyed_histograms.http_traffic_analysis_3),
      ('devtools_webide_connected_runtime_id', payload.keyed_histograms.devtools_webide_connected_runtime_id),
      ('permission_request_handling_user_input', payload.keyed_histograms.permission_request_handling_user_input),
      ('devtools_perftools_selected_view_ms', payload.keyed_histograms.devtools_perftools_selected_view_ms),
      ('fx_session_restore_content_collect_data_ms', payload.keyed_histograms.fx_session_restore_content_collect_data_ms),
      ('media_codec_used', payload.keyed_histograms.media_codec_used),
      ('web_permission_cleared', payload.keyed_histograms.web_permission_cleared),
      ('urlclassifier_update_remote_status2', payload.keyed_histograms.urlclassifier_update_remote_status2),
      ('decoder_doctor_infobar_stats', payload.keyed_histograms.decoder_doctor_infobar_stats),
      ('subprocess_kill_hard', payload.keyed_histograms.subprocess_kill_hard),
      ('devtools_webide_connected_runtime_type', payload.keyed_histograms.devtools_webide_connected_runtime_type),
      ('devtools_memory_breakdown_census_count', payload.keyed_histograms.devtools_memory_breakdown_census_count),
      ('process_crash_submit_attempt', payload.keyed_histograms.process_crash_submit_attempt),
      ('storage_sync_set_ops_size', payload.keyed_histograms.storage_sync_set_ops_size),
      ('urlclassifier_complete_timeout2', payload.keyed_histograms.urlclassifier_complete_timeout2),
      ('fx_startup_migration_undo_bookmarks_ms', payload.keyed_histograms.fx_startup_migration_undo_bookmarks_ms),
      ('network_cache_size', payload.keyed_histograms.network_cache_size),
      ('application_reputation_server_verdict_2', payload.keyed_histograms.application_reputation_server_verdict_2),
      ('devtools_webide_connected_runtime_platform_version', payload.keyed_histograms.devtools_webide_connected_runtime_platform_version),
      ('addon_content_policy_shim_blocking_loading_ms', payload.keyed_histograms.addon_content_policy_shim_blocking_loading_ms),
      ('pwmgr_manage_sorted', payload.keyed_histograms.pwmgr_manage_sorted),
      ('preferences_file_load_time_us', payload.keyed_histograms.preferences_file_load_time_us),
      ('d3d11_compositing_failure_id', payload.keyed_histograms.d3d11_compositing_failure_id),
      ('process_crash_submit_success', payload.keyed_histograms.process_crash_submit_success),
      ('webext_browseraction_popup_open_ms_by_addonid', payload.keyed_histograms.webext_browseraction_popup_open_ms_by_addonid),
      ('fx_migration_usage', payload.keyed_histograms.fx_migration_usage),
      ('ipc_sync_message_manager_latency_ms', payload.keyed_histograms.ipc_sync_message_manager_latency_ms),
      ('subprocess_abnormal_abort', payload.keyed_histograms.subprocess_abnormal_abort),
      ('urlclassifier_update_timeout', payload.keyed_histograms.urlclassifier_update_timeout),
      ('fx_migration_imported_homepage', payload.keyed_histograms.fx_migration_imported_homepage),
      ('translation_opportunities_by_language', payload.keyed_histograms.translation_opportunities_by_language),
      ('print_dialog_opened_count', payload.keyed_histograms.print_dialog_opened_count),
      ('devtools_webide_connected_runtime_processor', payload.keyed_histograms.devtools_webide_connected_runtime_processor),
      ('telemetry_invalid_ping_type_submitted', payload.keyed_histograms.telemetry_invalid_ping_type_submitted),
      ('permission_request_third_party_origin', payload.keyed_histograms.permission_request_third_party_origin),
      ('devtools_webide_connected_runtime_version', payload.keyed_histograms.devtools_webide_connected_runtime_version),
      ('fx_startup_migration_data_recency', payload.keyed_histograms.fx_startup_migration_data_recency),
      ('http_channel_disposition_upgrade', payload.keyed_histograms.http_channel_disposition_upgrade),
      ('d3d9_compositing_failure_id', payload.keyed_histograms.d3d9_compositing_failure_id),
      ('update_check_extended_error_notify', payload.keyed_histograms.update_check_extended_error_notify),
      ('subprocess_crashes_with_dump', payload.keyed_histograms.subprocess_crashes_with_dump),
      ('sync_worker_operation', payload.keyed_histograms.sync_worker_operation),
      ('network_cache_entry_count', payload.keyed_histograms.network_cache_entry_count),
      ('storage_sync_get_ops_size', payload.keyed_histograms.storage_sync_get_ops_size),
      ('fx_migration_history_import_ms', payload.keyed_histograms.fx_migration_history_import_ms),
      ('fx_startup_migration_undo_bookmarks_errorcount', payload.keyed_histograms.fx_startup_migration_undo_bookmarks_errorcount),
      ('service_worker_fetch_interception_duration_ms', payload.keyed_histograms.service_worker_fetch_interception_duration_ms),
      ('content_js_foreground_tick_delay_events_ms', payload.keyed_histograms.content_js_foreground_tick_delay_events_ms),
      ('video_suspend_recovery_time_ms', payload.keyed_histograms.video_suspend_recovery_time_ms),
      ('weave_engine_sync_errors', payload.keyed_histograms.weave_engine_sync_errors),
      ('content_large_paint_phase_weight', payload.keyed_histograms.content_large_paint_phase_weight),
      ('form_filling_required_time_ms', payload.keyed_histograms.form_filling_required_time_ms),
      ('service_worker_fetch_event_channel_reset_ms', payload.keyed_histograms.service_worker_fetch_event_channel_reset_ms),
      ('urlclassifier_cl_keyed_update_time', payload.keyed_histograms.urlclassifier_cl_keyed_update_time),
      ('network_cache_size_share', payload.keyed_histograms.network_cache_size_share),
      ('devtools_javascript_error_displayed', payload.keyed_histograms.devtools_javascript_error_displayed),
      ('permission_request_origin_scheme', payload.keyed_histograms.permission_request_origin_scheme),
      ('webext_storage_local_idb_set_ms_by_addonid', payload.keyed_histograms.webext_storage_local_idb_set_ms_by_addonid),
      ('addon_content_policy_shim_blocking_loaded_ms', payload.keyed_histograms.addon_content_policy_shim_blocking_loaded_ms),
      ('webext_storage_local_set_ms_by_addonid', payload.keyed_histograms.webext_storage_local_set_ms_by_addonid),
      ('fx_migration_logins_quantity', payload.keyed_histograms.fx_migration_logins_quantity),
      ('presshell_flushes_per_tick', payload.keyed_histograms.presshell_flushes_per_tick),
      ('ipc_reply_size', payload.keyed_histograms.ipc_reply_size),
      ('blocked_on_plugin_instance_destroy_ms', payload.keyed_histograms.blocked_on_plugin_instance_destroy_ms),
      ('fx_startup_migration_undo_reason', payload.keyed_histograms.fx_startup_migration_undo_reason),
      ('addon_shim_usage', payload.keyed_histograms.addon_shim_usage),
      ('print_count', payload.keyed_histograms.print_count),
      ('idle_runnable_budget_overuse_ms', payload.keyed_histograms.idle_runnable_budget_overuse_ms),
      ('content_small_paint_phase_weight', payload.keyed_histograms.content_small_paint_phase_weight),
      ('devtools_toolbox_page_reload_delay_ms', payload.keyed_histograms.devtools_toolbox_page_reload_delay_ms),
      ('network_cache_isolation_entry_count_increase', payload.keyed_histograms.network_cache_isolation_entry_count_increase),
      ('popup_notification_dismissal_ms', payload.keyed_histograms.popup_notification_dismissal_ms),
      ('urlclassifier_update_server_response_time', payload.keyed_histograms.urlclassifier_update_server_response_time),
      ('ipc_sync_receive_ms', payload.keyed_histograms.ipc_sync_receive_ms),
      ('notify_observers_latency_ms', payload.keyed_histograms.notify_observers_latency_ms),
      ('devtools_memory_breakdown_dominator_tree_count', payload.keyed_histograms.devtools_memory_breakdown_dominator_tree_count),
      ('webext_background_page_load_ms_by_addonid', payload.keyed_histograms.webext_background_page_load_ms_by_addonid),
      ('webext_browseraction_popup_preload_result_count_by_addonid', payload.keyed_histograms.webext_browseraction_popup_preload_result_count_by_addonid),
      ('network_http_redirect_to_scheme', payload.keyed_histograms.network_http_redirect_to_scheme),
      ('webext_user_script_injection_ms_by_addonid', payload.keyed_histograms.webext_user_script_injection_ms_by_addonid),
      ('network_cache_isolation_size_increase', payload.keyed_histograms.network_cache_isolation_size_increase),
      ('network_cache_entry_count_share', payload.keyed_histograms.network_cache_entry_count_share),
      ('urlclassifier_complete_server_response_time', payload.keyed_histograms.urlclassifier_complete_server_response_time),
      ('urlclassifier_complete_remote_status2', payload.keyed_histograms.urlclassifier_complete_remote_status2),
      ('fx_startup_migration_used_recent_browser', payload.keyed_histograms.fx_startup_migration_used_recent_browser),
      ('preferences_file_load_size_b', payload.keyed_histograms.preferences_file_load_size_b),
      ('network_cache_isolation_unique_site_access_count', payload.keyed_histograms.network_cache_isolation_unique_site_access_count),
      ('urlclassifier_update_remote_network_error', payload.keyed_histograms.urlclassifier_update_remote_network_error),
      ('telemetry_send_failure_type_per_ping', payload.keyed_histograms.telemetry_send_failure_type_per_ping),
      ('preferences_file_load_num_prefs', payload.keyed_histograms.preferences_file_load_num_prefs),
      ('ipc_sync_main_latency_ms', payload.keyed_histograms.ipc_sync_main_latency_ms),
      ('popup_notification_main_action_ms', payload.keyed_histograms.popup_notification_main_action_ms),
      ('translated_pages_by_language', payload.keyed_histograms.translated_pages_by_language),
      ('fx_migration_errors', payload.keyed_histograms.fx_migration_errors),
      ('urlclassifier_update_error', payload.keyed_histograms.urlclassifier_update_error),
      ('rejected_message_manager_message', payload.keyed_histograms.rejected_message_manager_message),
      ('http_traffic_analysis_2', payload.keyed_histograms.http_traffic_analysis_2),
      ('fx_migration_history_jank_ms', payload.keyed_histograms.fx_migration_history_jank_ms),
      ('devtools_gcli_commands_keyed', payload.keyed_histograms.devtools_gcli_commands_keyed),
      ('devtools_cold_toolbox_open_delay_ms', payload.keyed_histograms.devtools_cold_toolbox_open_delay_ms),
      ('fx_migration_history_quantity', payload.keyed_histograms.fx_migration_history_quantity),
      ('storage_sync_remove_ops', payload.keyed_histograms.storage_sync_remove_ops),
      ('thread_wakeup', payload.keyed_histograms.thread_wakeup),
      ('devtools_warm_toolbox_open_delay_ms', payload.keyed_histograms.devtools_warm_toolbox_open_delay_ms),
      ('fx_startup_migration_undo_visits_ms', payload.keyed_histograms.fx_startup_migration_undo_visits_ms),
      ('fx_startup_migration_undo_logins_ms', payload.keyed_histograms.fx_startup_migration_undo_logins_ms),
      ('devtools_perftools_recording_features_used', payload.keyed_histograms.devtools_perftools_recording_features_used),
      ('subprocess_launch_failure', payload.keyed_histograms.subprocess_launch_failure),
      ('narrate_content_by_language_2', payload.keyed_histograms.narrate_content_by_language_2),
      ('video_inter_keyframe_average_ms', payload.keyed_histograms.video_inter_keyframe_average_ms),
      ('canvas_webgl_accl_failure_id', payload.keyed_histograms.canvas_webgl_accl_failure_id),
      ('fx_tabletmode_page_load', payload.keyed_histograms.fx_tabletmode_page_load),
      ('ssl_time_until_handshake_finished_keyed_by_ka', payload.keyed_histograms.ssl_time_until_handshake_finished_keyed_by_ka),
      ('fx_startup_migration_undo_visits_errorcount', payload.keyed_histograms.fx_startup_migration_undo_visits_errorcount),
      ('video_hidden_play_time_percentage', payload.keyed_histograms.video_hidden_play_time_percentage),
      ('canvas_webgl_failure_id', payload.keyed_histograms.canvas_webgl_failure_id)
    ] as metrics
  FROM deduplicated),

  flattened_metrics AS
    (SELECT
      submission_timestamp,
      submission_date,
      client_id,
      os,
      app_version,
      app_build_id,
      channel,
      metrics.name AS metric,
      value.key AS key,
      value.value AS value
    FROM grouped_metrics
    CROSS JOIN UNNEST(metrics) AS metrics
    CROSS JOIN unnest(metrics.value) AS value),


-- Aggregate by client_id using windows
windowed AS (

SELECT
    ROW_NUMBER() OVER w1_unframed AS _n,
    submission_date,
    client_id,
    os,
    app_version,
    app_build_id,
    channel,

metric,
key,
ARRAY_AGG(value) OVER w1 as bucket_range,
ARRAY_AGG(value) OVER w1 as value

    FROM flattened_metrics
    WINDOW
        -- Aggregations require a framed window
        w1 AS (
            PARTITION BY
                client_id,
                submission_date,
                os,
                app_version,
                app_build_id,
                channel,
                metric,
                key
            ORDER BY `submission_timestamp` ASC ROWS BETWEEN UNBOUNDED PRECEDING
            AND UNBOUNDED FOLLOWING
        ),

        -- ROW_NUMBER does not work on a framed window
        w1_unframed AS (
            PARTITION BY
                client_id,
                submission_date,
                os,
                app_version,
                app_build_id,
                channel,
                metric,
                key
            ORDER BY `submission_timestamp` ASC)

)

select
    client_id,
    submission_date,
    os,
    app_version,
    app_build_id,
    channel,
    ARRAY_AGG(STRUCT<
        metric STRING,
        metric_type STRING,
        key STRING,
        agg_type STRING,
        bucket_range STRUCT<
            first_bucket INT64,
            last_bucket INT64,
            num_buckets INT64
        >,
        value ARRAY<STRUCT<key STRING, value INT64>>
    >(
        metric,
        udf_get_histogram_type(bucket_range),
        key,
        '',
        udf_get_bucket_range(bucket_range),
        udf_aggregate_json_sum(value)
    )) AS histogram_aggregates
from windowed
where _n = 1
group by 1,2,3,4,5,6
