fields:
- mode: NULLABLE
  name: date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: date
- mode: NULLABLE
  name: country_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: country_name
- mode: NULLABLE
  name: channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel
- mode: NULLABLE
  name: build_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: build_id
- mode: NULLABLE
  name: os
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: os
- mode: NULLABLE
  name: attribution_source
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_source
- mode: NULLABLE
  name: distribution_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: distribution_id
- mode: NULLABLE
  name: attribution_ua
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_ua
- mode: NULLABLE
  name: new_profiles
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: new_profiles
