CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.org_mozilla_firefox.installation`
AS -- Generated by bigquery_etl.view.generate_stable_views

SELECT
  * REPLACE(
    mozfun.norm.metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shared-prod.org_mozilla_firefox_stable.installation_v1`
