#!/bin/bash
# generate sql for checking into the repository and for testing the workflow

set -e

skip_generate=${SKIP_GENERATE:-false}
# NOTE: there are three app_ids that we must look at for historical context. For
# the purpose of this script, it is sufficient to look only at what is currently
# "fenix nightly".
app_id="org_mozilla_fenix"
logical_app_id="org_mozilla_fenix_glam_nightly"

dir="$(dirname "$0")/.."

if [[ $skip_generate == false ]]; then
    PRODUCT=$app_id STAGE=daily $dir/generate_glean_sql
    PRODUCT=$logical_app_id STAGE=incremental $dir/generate_glean_sql
fi

PRODUCT=$app_id STAGE=daily $dir/run_glam_sql
PRODUCT=$logical_app_id STAGE=incremental $dir/run_glam_sql
