CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.focus_android.composite_active_users_aggregates`
AS
SELECT
  submission_date,
  first_seen_year,
  channel,
  app_name,
  app_version,
  app_version_major,
  app_version_minor,
  app_version_patch_revision,
  app_version_is_major_release,
  country,
  os,
  os_version,
  os_version_major,
  os_version_minor,
  segment AS activity_segment,
  distribution_id,
  is_default_browser,
  SUM(dau) AS dau,
  SUM(wau) AS wau,
  SUM(mau) AS mau,
  SUM(daily_users) AS daily_users,
  SUM(weekly_users) AS weekly_users,
  SUM(monthly_users) AS monthly_users,
FROM
  `moz-fx-data-shared-prod.focus_android.active_users_aggregates`
WHERE
  app_version_major < 136
GROUP BY
  submission_date,
  first_seen_year,
  channel,
  app_name,
  app_version,
  app_version_major,
  app_version_minor,
  app_version_patch_revision,
  app_version_is_major_release,
  country,
  os,
  os_version,
  os_version_major,
  os_version_minor,
  activity_segment,
  distribution_id,
  is_default_browser
UNION ALL
SELECT
  submission_date,
  first_seen_year,
  channel,
  app_name,
  app_version,
  app_version_major,
  app_version_minor,
  app_version_patch_revision,
  app_version_is_major_release,
  country,
  os,
  os_version,
  os_version_major,
  os_version_minor,
  activity_segment,
  distribution_id,
  is_default_browser,
  SUM(dau) AS dau,
  SUM(wau) AS wau,
  SUM(mau) AS mau,
  SUM(daily_users) AS daily_users,
  SUM(weekly_users) AS weekly_users,
  SUM(monthly_users) AS monthly_users,
FROM
  `moz-fx-data-shared-prod.focus_android.usage_reporting_active_users_aggregates`
WHERE
  app_version_major >= 136
GROUP BY
  submission_date,
  first_seen_year,
  channel,
  app_name,
  app_version,
  app_version_major,
  app_version_minor,
  app_version_patch_revision,
  app_version_is_major_release,
  country,
  os,
  os_version,
  os_version_major,
  os_version_minor,
  activity_segment,
  distribution_id,
  is_default_browser
