-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.fenix.startup_timeline`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.org_mozilla_firefox.startup_timeline`
