SELECT
  mozilla_account_id AS external_id,
  provider AS provider,
  payment_provider AS payment_provider,
  product_name AS product_name,
  services.name AS service_name,
  provider_plan_id AS subscription_plan_id,
  provider_product_id AS subscription_product_id,
  started_at AS subscription_started_at,
  ended_at AS subscription_ended_at,
  plan_summary AS subscription_summary,
  plan_interval_type AS subscription_billing_interval,
  plan_interval_count AS subscription_interval_count,
  plan_currency AS subscription_currency,
  plan_amount AS subscription_amount,
  is_bundle AS is_bundle,
  is_trial AS is_trial,
  is_active AS is_active,
  provider_status AS subscription_status,
  LOWER(country_code) AS subscription_country_code,
  country_name AS subscription_country_name,
  current_period_started_at AS current_period_started_at,
  current_period_ends_at AS current_period_ends_at,
  auto_renew AS is_auto_renew,
  auto_renew_disabled_at AS auto_renew_disabled_at,
  has_refunds AS has_refunds,
  has_fraudulent_charges AS has_fraudulent_charges,
  CAST(NULL AS TIMESTAMP) AS first_touch_impression_at,
  CAST(NULL AS STRING) AS first_touch_entrypoint,
  CAST(NULL AS STRING) AS first_touch_entrypoint_experiment,
  CAST(NULL AS STRING) AS first_touch_entrypoint_variation,
  CAST(NULL AS STRING) AS first_touch_utm_campaign,
  CAST(NULL AS STRING) AS first_touch_utm_content,
  CAST(NULL AS STRING) AS first_touch_utm_medium,
  CAST(NULL AS STRING) AS first_touch_utm_source,
  CAST(NULL AS STRING) AS first_touch_utm_term,
  last_touch_attribution.impression_at AS last_touch_impression_at,
  last_touch_attribution.entrypoint AS last_touch_entrypoint,
  last_touch_attribution.entrypoint_experiment AS last_touch_entrypoint_experiment,
  last_touch_attribution.entrypoint_variation AS last_touch_entrypoint_variation,
  last_touch_attribution.utm_campaign AS last_touch_utm_campaign,
  last_touch_attribution.utm_content AS last_touch_utm_content,
  last_touch_attribution.utm_medium AS last_touch_utm_medium,
  last_touch_attribution.utm_source AS last_touch_utm_source,
  last_touch_attribution.utm_term AS last_touch_utm_term,
  provider_subscription_created_at AS subscription_created_at,
  provider_subscription_updated_at AS subscription_updated_at
FROM
  `moz-fx-data-shared-prod.subscription_platform.logical_subscriptions`
CROSS JOIN
  UNNEST(services) AS services
