#!/usr/bin/env python3
"""clients_daily_scalar_aggregates query generator."""
import sys
import json
import argparse
import textwrap
import subprocess
import urllib.request


PROBE_INFO_SERVICE = (
    "https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes"
)

p = argparse.ArgumentParser()
p.add_argument(
    "--agg-type",
    type=str,
    help="One of scalar/keyed-scalar/keyed-boolean",
    required=True,
)


def generate_sql(
    agg_type,
    aggregates,
    additional_queries,
    additional_partitions,
    select_clause,
    querying_table,
):
    """Create a SQL query for the clients_daily_scalar_aggregates dataset."""
    return textwrap.dedent(
        f"""-- Query generated by:
            -- templates/clients_daily_scalar_aggregates.sql.py --agg-type {agg_type}
        WITH
            -- normalize client_id and rank by document_id
            numbered_duplicates AS (
                SELECT
                    ROW_NUMBER() OVER (
                        PARTITION BY
                            client_id,
                            submission_date,
                            document_id
                        ORDER BY `timestamp`
                        ASC
                    ) AS _n,
                    * REPLACE(LOWER(client_id) AS client_id)
                FROM main_summary_v4
                WHERE submission_date = @submission_date
                AND channel in (
                    "release", "esr", "beta", "aurora", "default", "nightly"
                )
                AND client_id IS NOT NULL
            ),


            -- Deduplicating on document_id is necessary to get valid SUM values.
            deduplicated AS (
                SELECT * EXCEPT (_n)
                FROM numbered_duplicates
                WHERE _n = 1
            ),

            {additional_queries}

            -- Aggregate by client_id using windows
            windowed AS (
                SELECT
                    ROW_NUMBER() OVER w1_unframed AS _n,
                    submission_date,
                    client_id,
                    os,
                    SPLIT(app_version, '.')[OFFSET(0)] AS app_version,
                    app_build_id,
                    channel,
                    {aggregates}
                FROM {querying_table}
                WINDOW
                    -- Aggregations require a framed window
                    w1 AS (
                        PARTITION BY
                            client_id,
                            submission_date,
                            os,
                            app_version,
                            app_build_id,
                            channel
                            {additional_partitions}
                        ORDER BY `timestamp` ASC ROWS BETWEEN UNBOUNDED PRECEDING
                        AND UNBOUNDED FOLLOWING
                    ),

                    -- ROW_NUMBER does not work on a framed window
                    w1_unframed AS (
                        PARTITION BY
                            client_id,
                            submission_date,
                            os,
                            app_version,
                            app_build_id,
                            channel
                            {additional_partitions}
                        ORDER BY `timestamp` ASC
                    )
            )
            {select_clause}
        """
    )


def get_histogram_type(keyval_fields):
    """Return the type of histogram given its schema."""
    if (
        len(keyval_fields) == 2
        and keyval_fields[0].get("type", None) == "INTEGER"
        and keyval_fields[1].get("type", None) == "INTEGER"
    ):
        return "histogram"

    if (
        len(keyval_fields) == 2
        and keyval_fields[0].get("type", None) == "STRING"
        and keyval_fields[1].get("type", None) == "INTEGER"
    ):
        return "string-histogram"

    if (
        len(keyval_fields) == 2
        and keyval_fields[0].get("type", None) == "STRING"
        and keyval_fields[1].get("type", None) == "RECORD"
        and keyval_fields[1]["fields"][0]["type"] == "INTEGER"
    ):
        return "keyed-histogram"


def _get_generic_keyed_scalar_sql(probes, value_type):
    probes_struct = []
    for probe in probes:
        probes_struct.append(f"('{probe}', {probe})")

    probes_arr = ",\n\t\t\t".join(probes_struct)

    additional_queries = f"""
        grouped_metrics AS
          (select
            timestamp,
            client_id,
            submission_date,
            os,
            app_version,
            app_build_id,
            channel,
            ARRAY<STRUCT<
                name STRING,
                value ARRAY<STRUCT<key STRING, value {value_type}>>
            >>[
              {probes_arr}
            ] as metrics
          FROM deduplicated),

          flattened_metrics AS
            (SELECT
              timestamp,
              client_id,
              submission_date,
              os,
              app_version,
              app_build_id,
              channel,
              metrics.name AS metric,
              value.key AS key,
              value.value AS value
            FROM grouped_metrics
            CROSS JOIN unnest(metrics) AS metrics,
            unnest(metrics.value) AS value),
    """

    querying_table = "flattened_metrics"

    additional_partitions = """,
                            metric,
                            key
    """

    return {
        "additional_queries": additional_queries,
        "additional_partitions": additional_partitions,
        "querying_table": querying_table,
    }


def get_keyed_boolean_probes_sql_string(probes):
    """Put together the subsets of SQL required to query keyed booleans."""
    sql_strings = _get_generic_keyed_scalar_sql(probes, "BOOLEAN")
    sql_strings[
        "probes_string"
    ] = """
        metric,
        key,
        SUM(CASE WHEN value = True THEN 1 ELSE 0 END) OVER w1 AS true_col,
        SUM(CASE WHEN value = False THEN 1 ELSE 0 END) OVER w1 AS false_col
    """

    sql_strings[
        "select_clause"
    ] = """
        select
              client_id,
              submission_date,
              os,
              app_version,
              app_build_id,
              channel,
              ARRAY_CONCAT_AGG(ARRAY<STRUCT<
                    metric STRING,
                    metric_type STRING,
                    key STRING,
                    agg_type STRING,
                    value FLOAT64
                >>
                [
                    (metric, 'keyed-scalar-boolean', key, 'true', true_col),
                    (metric, 'keyed-scalar-boolean', key, 'false', false_col)
                ]
            ) AS scalar_aggregates
        from windowed
        where _n = 1
        group by 1,2,3,4,5,6
    """
    return sql_strings


def get_keyed_scalar_probes_sql_string(probes):
    """Put together the subsets of SQL required to query keyed scalars."""
    sql_strings = _get_generic_keyed_scalar_sql(probes, "INT64")
    sql_strings[
        "probes_string"
    ] = """
        metric,
        key,
        MAX(value) OVER w1 as max,
        MIN(value) OVER w1 as min,
        AVG(value) OVER w1 as avg,
        SUM(value) OVER w1 as sum
    """

    sql_strings[
        "select_clause"
    ] = """
        select
            client_id,
            submission_date,
            os,
            app_version,
            app_build_id,
            channel,
            ARRAY_CONCAT_AGG(ARRAY<STRUCT<
                metric STRING,
                metric_type STRING,
                key STRING,
                agg_type STRING,
                value FLOAT64
            >>
                [
                    (metric, 'keyed-scalar', key, 'max', max),
                    (metric, 'keyed-scalar', key, 'min', min),
                    (metric, 'keyed-scalar', key, 'avg', avg),
                    (metric, 'keyed-scalar', key, 'sum', sum)
                ]
        ) AS scalar_aggregates
        from windowed
        where _n = 1
        group by 1,2,3,4,5,6
    """
    return sql_strings


def get_scalar_probes_sql_strings(probes, scalar_type):
    """Put together the subsets of SQL required to query scalars or booleans."""
    if scalar_type == "keyed-scalar":
        return get_keyed_scalar_probes_sql_string(probes["keyed"])

    if scalar_type == "keyed-boolean":
        return get_keyed_boolean_probes_sql_string(probes["keyed_boolean"])

    probe_structs = []
    for probe in probes["scalars"]:
        probe_structs.append(
            f"('{probe}', 'scalar', '', 'max', max(CAST({probe} AS INT64)) OVER w1)"
        )
        probe_structs.append(
            f"('{probe}', 'scalar', '', 'avg', avg(CAST({probe} AS INT64)) OVER w1)"
        )
        probe_structs.append(
            f"('{probe}', 'scalar', '', 'min', min(CAST({probe} AS INT64)) OVER w1)"
        )
        probe_structs.append(
            f"('{probe}', 'scalar', '', 'sum', sum(CAST({probe} AS INT64)) OVER w1)"
        )

    for probe in probes["booleans"]:
        probe_structs.append(
            (
                f"('{probe}', 'boolean', '', 'false', sum(case when {probe} = False "
                "then 1 else 0 end) OVER w1)"
            )
        )
        probe_structs.append(
            (
                f"('{probe}', 'boolean', '', 'true', sum(case when {probe} = True "
                "then 1 else 0 end) OVER w1)"
            )
        )

    probes_arr = ",\n\t\t\t".join(probe_structs)
    probes_string = f"""
            ARRAY<STRUCT<
                metric STRING,
                metric_type STRING,
                key STRING,
                agg_type STRING,
                value FLOAT64
            >> [
                {probes_arr}
            ] AS scalar_aggregates
    """

    select_clause = f"""
        SELECT
            * EXCEPT(_n)
        FROM
            windowed
        WHERE
            _n = 1
    """

    return {"probes_string": probes_string, "select_clause": select_clause}


def get_scalar_probes():
    """Find all scalar probes in main summary.

    Note: that non-integer scalar probes are not included.
    """
    project = "moz-fx-data-derived-datasets"
    main_summary_scalars = set()
    main_summary_record_scalars = set()
    main_summary_boolean_record_scalars = set()
    main_summary_boolean_scalars = set()

    process = subprocess.Popen(
        [
            "bq",
            "show",
            "--schema",
            "--format=json",
            f"{project}:telemetry.main_summary_v4",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    stdout, stderr = process.communicate()
    if process.returncode > 0:
        raise Exception(
            f"Call to bq exited non-zero: {process.returncode}", stdout, stderr
        )
    main_summary_schema = json.loads(stdout)

    for field in main_summary_schema:
        if field["name"].startswith("scalar_parent") and field["type"] == "INTEGER":
            main_summary_scalars.add(field["name"])
        elif field["name"].startswith("scalar_parent") and field["type"] == "BOOLEAN":
            main_summary_boolean_scalars.add(field["name"])
        elif field["name"].startswith("scalar_parent") and field["type"] == "RECORD":
            if field["fields"][1]["type"] == "BOOLEAN":
                main_summary_boolean_record_scalars.add(field["name"])
            else:
                main_summary_record_scalars.add(field["name"])

    # Find the intersection between relevant scalar probes
    # and those that exist in main summary
    with urllib.request.urlopen(PROBE_INFO_SERVICE) as url:
        data = json.loads(url.read().decode())
        scalar_probes = set(
            [
                x.replace("scalar/", "scalar_parent_").replace(".", "_")
                for x in data.keys()
                if x.startswith("scalar/")
            ]
        )
        return {
            "scalars": scalar_probes.intersection(main_summary_scalars),
            "booleans": scalar_probes.intersection(main_summary_boolean_scalars),
            "keyed": scalar_probes.intersection(main_summary_record_scalars),
            "keyed_boolean": scalar_probes.intersection(
                main_summary_boolean_record_scalars
            ),
        }


def main(argv, out=print):
    """Print a clients_daily_scalar_aggregates query to stdout."""
    opts = vars(p.parse_args(argv[1:]))
    sql_string = ""

    if opts["agg_type"] in ("scalar", "keyed-scalar", "keyed-boolean"):
        scalar_probes = get_scalar_probes()
        sql_string = get_scalar_probes_sql_strings(scalar_probes, opts["agg_type"])
    else:
        raise ValueError("agg-type must be one of scalar, keyed-scalar, keyed-boolean")

    out(
        generate_sql(
            opts["agg_type"],
            sql_string["probes_string"],
            sql_string.get("additional_queries", ""),
            sql_string.get("additional_partitions", ""),
            sql_string["select_clause"],
            sql_string.get("querying_table", "deduplicated"),
        )
    )


if __name__ == "__main__":
    main(sys.argv)
