-- Query generated by: templates/unnest_parquet_view.sql.py eng_workflow_build_parquet_v1 telemetry_derived.eng_workflow_build_parquet_v1
CREATE OR REPLACE VIEW
  `moz-fx-data-derived-datasets.telemetry.eng_workflow_build_parquet_v1` AS
SELECT
  submission_date_s3 AS submission_date,
  * REPLACE (
    ARRAY(SELECT * FROM UNNEST(argv.list)) AS argv,
    ARRAY(SELECT * FROM UNNEST(file_types_changed.list)) AS file_types_changed
  )
FROM
  `moz-fx-data-derived-datasets.telemetry_derived.eng_workflow_build_parquet_v1`
