fields:
- name: task_id
  type: STRING
  mode: NULLABLE
- name: run_id
  type: INTEGER
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: run_cost
  type: FLOAT
  mode: NULLABLE
- name: cloud_provider
  type: STRING
  mode: NULLABLE
- name: worker_project
  type: STRING
  mode: NULLABLE
- name: worker_zone
  type: STRING
  mode: NULLABLE
- name: worker_instance_id
  type: STRING
  mode: NULLABLE
- name: attribution_worker_cost
  type: FLOAT
  mode: NULLABLE
- name: attribution_worker_uptime
  type: FLOAT
  mode: NULLABLE
- name: run_duration
  type: INTEGER
  mode: NULLABLE
- name: attribution_method
  type: STRING
  mode: NULLABLE
