-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.firefox_desktop.baseline`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.firefox_desktop.baseline`

