fields:
- name: application
  type: STRING
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: engine_name
  type: STRING
  mode: NULLABLE
- name: count_total
  type: INTEGER
  mode: NULLABLE
- name: count_success
  type: INTEGER
  mode: NULLABLE
- name: count_errors
  type: INTEGER
  mode: NULLABLE
- name: applied_count
  type: INTEGER
  mode: NULLABLE
- name: reconciled_count
  type: INTEGER
  mode: NULLABLE
- name: failed_to_apply_count
  type: INTEGER
  mode: NULLABLE
- name: uploaded_count
  type: INTEGER
  mode: NULLABLE
- name: failed_to_upload_count
  type: INTEGER
  mode: NULLABLE
- name: success_rate
  type: FLOAT
  mode: NULLABLE
- name: non_error_rate
  type: FLOAT
  mode: NULLABLE
- name: total_count_moving_avg
  type: FLOAT
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
