-- Query generated by: templates/unnest_parquet_view.sql.py sync_flat_summary_v1 telemetry_derived.sync_flat_summary_v1
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.telemetry.sync_flat_summary_v1` AS
SELECT
  submission_date_s3 AS submission_date,
  * REPLACE (
    ARRAY(SELECT * FROM UNNEST(devices.list)) AS devices
  )
FROM
  `moz-fx-data-derived-datasets.telemetry_derived.sync_flat_summary_v1`
