SELECT
  *
FROM
  EXTERNAL_QUERY(
    "moz-fx-fxa-nonprod.us.fxa-rds-nonprod-stage-fxa",
    """SELECT
         uid,
         normalizedEmail,
         email,
         emailVerified,
         verifierVersion,
         verifierSetAt,
         createdAt,
         locale,
         lockedAt,
         profileChangedAt,
         keysChangedAt,
         ecosystemAnonId,
         disabledAt,
         metricsOptOutAt
       FROM
         accounts
    """
  )
