-- keywords
* except;
* replace;
all;
and;
any;
array;
as;
asc;
assert_rows_modified;
at;
between;
by;
cast;
collate;
contains;
create;
cross;
cube;
current;
current row;
day;
dayofweek;
dayofyear;
default;
define;
desc;
distinct;
enum;
escape;
except;
exclude;
exists;
extract;
false;
fetch;
following;
for;
for system_time as of;
from;
full;
group;
grouping;
groups;
hash;
having;
having max;
having min;
hour;
if();
ignore;
in;
inner;
inout;
intersect;
interval;
into;
is;
isoweek;
isoyear;
join;
lateral;
left;
like;
limit;
lookup;
merge;
microsecond;
millisecond;
minute;
month;
natural;
new;
no;
not;
null;
nulls;
nulls first;
nulls last;
of;
on;
or;
order;
out;
outer;
over;
partition;
preceding;
proto;
quarter;
range;
recursive;
replace;
respect;
right;
rollup;
rows;
second;
select;
set;
some;
struct;
tablesample;
to;
treat;
true;
unbounded;
union;
unnest;
using;
week;
where;
window;
with;
within;
year;
-- newline keywords
pivot;
unpivot;
unpivot include nulls;
unpivot exclude nulls;
with offset;
create or replace function;
create or replace aggregate function;
create or replace table function;
create function if not exists;
create aggregate function if not exists;
create table function if not exists;
create function;
create temp function;
create aggregate function;
create temp aggregate function;
create table function;
returns;
language;
and;
between;
or;
declare;
raise;
raise using message;
-- scripting keywords
create or replace procedure
begin
end;
create procedure if not exists
begin
end;
create procedure
begin
exception when error then
end;
if
then
elseif
then
else
end if;
while
do
end while;
loop
end loop;
repeat
until
end repeat;
for _ in ()
do
end for;
case
when
then
else
end;
begin transaction;
break;
call;
commit transaction;
commit;
continue;
execute immediate '...' into result using parameter;
iterate;
leave;
return;
rollback transaction;
rollback;
-- top level keywords
alter table if exists;
alter table;
cluster by;
create or replace table;
create or replace view;
create or replace materialized view;
create table if not exists;
create view if not exists;
create materialized view if not exists;
create temp table;
create table;
create view;
create materialized view;
drop table;
drop table if exists;
drop view;
drop view if exists;
drop materialized view;
drop materialized view if exists;
options;
delete from;
delete;
insert into;
insert;
merge into;
merge;
update;
aggregate;
cross join;
drop;
except distinct;
except distinct by name;
except distinct by name on (a, b, c);
inner except distinct by name on (a, b, c);
outer except distinct by name on (a, b, c);
full except distinct by name on (a, b, c);
full outer except distinct by name on (a, b, c);
left except distinct by name on (a, b, c);
left outer except distinct by name on (a, b, c);
except distinct corresponding;
except distinct strict corresponding;
except distinct strict corresponding by (a, b, c);
inner except distinct strict corresponding by (a, b, c);
outer except distinct strict corresponding by (a, b, c);
full except distinct strict corresponding by (a, b, c);
full outer except distinct strict corresponding by (a, b, c);
left except distinct strict corresponding by (a, b, c);
left outer except distinct strict corresponding by (a, b, c);
extend;
from;
full join;
full outer join;
group and order by;
group by;
group by all;
group by cube ();
group by grouping sets ();
group by rollup ();
having;
inner join;
intersect distinct;
intersect distinct by name;
intersect distinct by name on (a, b, c);
inner intersect distinct by name on (a, b, c);
outer intersect distinct by name on (a, b, c);
full intersect distinct by name on (a, b, c);
full outer intersect distinct by name on (a, b, c);
left intersect distinct by name on (a, b, c);
left outer intersect distinct by name on (a, b, c);
intersect distinct corresponding;
intersect distinct strict corresponding;
intersect distinct strict corresponding by (a, b, c);
inner intersect distinct strict corresponding by (a, b, c);
outer intersect distinct strict corresponding by (a, b, c);
full intersect distinct strict corresponding by (a, b, c);
full outer intersect distinct strict corresponding by (a, b, c);
left intersect distinct strict corresponding by (a, b, c);
left outer intersect distinct strict corresponding by (a, b, c);
join;
left join;
left outer join;
limit;
order by;
partition by;
rename;
right join;
right outer join;
rows between;
rows;
select;
select all;
select distinct;
select as struct;
select as value;
union all;
union all by name;
union all by name on (a, b, c);
inner union all by name on (a, b, c);
outer union all by name on (a, b, c);
full union all by name on (a, b, c);
full outer union all by name on (a, b, c);
left union all by name on (a, b, c);
left outer union all by name on (a, b, c);
union all corresponding;
union all strict corresponding;
union all strict corresponding by (a, b, c);
inner union all strict corresponding by (a, b, c);
outer union all strict corresponding by (a, b, c);
full union all strict corresponding by (a, b, c);
full outer union all strict corresponding by (a, b, c);
left union all strict corresponding by (a, b, c);
left outer union all strict corresponding by (a, b, c);
union distinct;
union distinct by name;
union distinct by name on (a, b, c);
inner union distinct by name on (a, b, c);
outer union distinct by name on (a, b, c);
full union distinct by name on (a, b, c);
full outer union distinct by name on (a, b, c);
left union distinct by name on (a, b, c);
left outer union distinct by name on (a, b, c);
union distinct corresponding;
union distinct strict corresponding;
union distinct strict corresponding by (a, b, c);
inner union distinct strict corresponding by (a, b, c);
outer union distinct strict corresponding by (a, b, c);
full union distinct strict corresponding by (a, b, c);
full outer union distinct strict corresponding by (a, b, c);
left union distinct strict corresponding by (a, b, c);
left outer union distinct strict corresponding by (a, b, c);
values;
when matched;
when not matched;
when not matched by source;
when not matched by target;
where;
with;
window;
-- operator keywords
not between;
not in;
is distinct from;
is not distinct from;
is null;
is not null;
is true;
is false;
is not true;
is not false;
like any;
like some;
like all;
not like;
not like any;
not like some;
not like all;
-- data type keywords
bignumeric;
bignumeric(10, 2);
bigdecimal;
bigdecimal(10, 2);
bool;
boolean;
bytes;
bytes(100);
date;
datetime;
float64;
geography;
int64;
int;
smallint;
integer;
bigint;
tinyint;
byteint;
json;
numeric;
numeric(10, 2);
decimal;
decimal(10, 2);
range<date>;
range<datetime>;
range<timestamp>;
string;
string(100);
time;
timestamp;
