-- Generated by Generated via bigquery_etl.glean_usage.GleanAppPingViews
CREATE OR REPLACE VIEW
  `moz-fx-data-shared-prod.mozregression.deletion_request`
AS
SELECT
  *
FROM
  `moz-fx-data-shared-prod.org_mozilla_mozregression.deletion_request`
