fields:
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: client_id
  name: client_id
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sample_id
  name: sample_id
  type: INTEGER
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: first_seen_date
  name: first_seen_date
  type: DATE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: second_seen_date
  name: second_seen_date
  type: DATE
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: architecture
  name: architecture
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_build_id
  name: app_build_id
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_name
  name: app_name
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: locale
  name: locale
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: platform_version
  name: platform_version
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: vendor
  name: vendor
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_version
  name: app_version
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: xpcom_abi
  name: xpcom_abi
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: document_id
  name: document_id
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: distribution_id
  name: distribution_id
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_distribution_version
  name: partner_distribution_version
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_distributor
  name: partner_distributor
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_distributor_channel
  name: partner_distributor_channel
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_id
  name: partner_id
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_campaign
  name: attribution_campaign
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_content
  name: attribution_content
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_experiment
  name: attribution_experiment
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_medium
  name: attribution_medium
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_source
  name: attribution_source
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_ua
  name: attribution_ua
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: engine_data_load_path
  name: engine_data_load_path
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: engine_data_name
  name: engine_data_name
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: engine_data_origin
  name: engine_data_origin
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: engine_data_submission_url
  name: engine_data_submission_url
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: apple_model_id
  name: apple_model_id
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: city
  name: city
  type: STRING
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: db_version
  name: db_version
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: subdivision1
  name: subdivision1
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_channel
  name: normalized_channel
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: country
  name: country
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_os
  name: normalized_os
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_os_version
  name: normalized_os_version
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: startup_profile_selection_reason
  name: startup_profile_selection_reason
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_dltoken
  name: attribution_dltoken
  type: STRING
  mode: NULLABLE
- description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_dlsource
  name: attribution_dlsource
  type: STRING
  mode: NULLABLE
- description: null
  name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - description: Ping that reported the first seen date (main, first_shutdown or new_profile).
    name: first_seen_date_source_ping
    type: STRING
    mode: NULLABLE
  - description: Indicates wether the client ever reported a main ping.
    name: reported_main_ping
    type: BOOLEAN
    mode: NULLABLE
  - description: Indicates wether the client ever reported a new profile ping.
    name: reported_new_profile_ping
    type: BOOLEAN
    mode: NULLABLE
  - description: Indicates wether the client ever reported a first shutdown ping.
    name: reported_shutdown_ping
    type: BOOLEAN
    mode: NULLABLE
- name: profile_group_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: profile_group_id
- name: browser_backup_scheduler_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: browser_backup_scheduler_enabled
- name: browser_backup_archive_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: browser_backup_archive_enabled
