r"""Metric counting.

```bash
python3 -m bigquery_etl.glam.glean_metric_counts

diff \
    <(cat sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql) \
    <(python3 -m bigquery_etl.glam.glean_metric_counts)
```
"""
from argparse import ArgumentParser
from itertools import combinations
from typing import List

from jinja2 import Environment, PackageLoader

from bigquery_etl.format_sql.formatter import reformat


def render_query(attributes: List[str], **kwargs) -> str:
    """Render the main query."""
    env = Environment(loader=PackageLoader("bigquery_etl", "glam/templates"))
    sql = env.get_template("metric_counts_v1.sql")

    # include attributes included and excluded from grouping set
    attribute_combinations = []
    for subset_size in reversed(range(len(attributes) + 1)):
        for grouping in combinations(attributes, subset_size):
            hidden = list(sorted(set(attributes) - set(grouping)))
            attribute_combinations.append((grouping, hidden))

    return reformat(sql.render(attribute_combinations=attribute_combinations, **kwargs))


def telemetry_variables():
    """Variables for metric_counts."""
    return dict(
        source_table="clients_scalar_bucket_counts_v1",
        attributes=["os", "app_version", "app_build_id", "channel"],
        aggregate_attributes="""
            metric,
            metric_type,
            key,
            process
        """,
        aggregate_grouping="""
            client_agg_type,
            first_bucket,
            last_bucket,
            num_buckets
        """,
        scalar_metric_types="""
            "scalars",
            "keyed-scalars"
        """,
    )


def glean_variables():
    """Variables for metric_bucketing."""
    return dict(
        source_table="fenix_clients_scalar_bucket_counts_v1",
        attributes=["ping_type", "os", "app_version", "app_build_id", "channel"],
        aggregate_attributes="""
            metric,
            metric_type,
            key
        """,
        aggregate_grouping="""
            client_agg_type,
            first_bucket,
            last_bucket,
            num_buckets
        """,
        # not boolean
        scalar_metric_types="""
            "counter",
            "quantity",
            "labeled_counter"
        """,
    )


def main():
    """Generate query for counting."""
    parser = ArgumentParser(description=main.__doc__)
    parser.add_argument(
        "--ping-type",
        default="telemetry",
        choices=["glean", "telemetry"],
        help="determine attributes and user data types to aggregate",
    )
    args = parser.parse_args()
    module_name = "bigquery_etl.glam.glean_metric_counts"
    header = f"-- generated by: python3 -m {module_name}"
    header += " " + " ".join(
        [f"--{k} {v}" for k, v in vars(args).items() if k != "init"]
    )
    variables = (
        telemetry_variables() if args.ping_type == "telemetry" else glean_variables()
    )
    print(render_query(header=header, **variables))


if __name__ == "__main__":
    main()
