"""Calculate percentiles for distributions."""
from jinja2 import Environment, PackageLoader

from bigquery_etl.format_sql.formatter import reformat


def render_main(**kwargs,) -> str:
    """Render the main query."""
    env = Environment(loader=PackageLoader("bigquery_etl", "glam/templates"))
    main_sql = env.get_template("histogram_percentiles_v1.sql")
    return reformat(main_sql.render(**kwargs))


def main():
    """Generate a query to standard out."""
    module_name = "bigquery_etl.glam.histogram_percentiles"
    header = f"-- generated by: python3 -m {module_name}"
    rendered = render_main(header=header)
    print(rendered)


if __name__ == "__main__":
    main()
