"""Find the latest version of a glean ping."""
from argparse import ArgumentParser
from jinja2 import Environment, PackageLoader

from bigquery_etl.format_sql.formatter import reformat


def render_main(**kwargs,) -> str:
    """Render the main query."""
    env = Environment(loader=PackageLoader("bigquery_etl", "glam/templates"))
    main_sql = env.get_template("latest_versions_v1.sql")
    return reformat(main_sql.render(**kwargs))


def main():
    """Generate a table with latest version per channel."""
    parser = ArgumentParser(description=main.__doc__)
    parser.add_argument(
        "--source",
        default="org_mozilla_fenix_stable.baseline_v1",
        help="Source baseline table",
    )
    args = parser.parse_args()

    module_name = "bigquery_etl.glam.latest_versions"
    header = f"-- generated by: python3 -m {module_name}"
    header += " " + " ".join(
        [f"--{k} {v}" for k, v in vars(args).items() if k != "init"]
    )
    rendered = render_main(header=header, source_table=args.source)
    print(rendered)


if __name__ == "__main__":
    main()
