"""Calculate percentiles for scalars."""
from argparse import ArgumentParser
from itertools import combinations
from typing import List

from jinja2 import Environment, PackageLoader

from bigquery_etl.format_sql.formatter import reformat


def render_query(attributes: List[str], **kwargs) -> str:
    """Render the main query."""
    env = Environment(loader=PackageLoader("bigquery_etl", "glam/templates"))
    sql = env.get_template("scalar_percentiles_v1.sql")

    max_combinations = len(attributes) + 1
    attribute_combinations = []
    for subset_size in reversed(range(max_combinations)):
        for grouping in combinations(attributes, subset_size):
            select_expr = []
            for attribute in attributes:
                select_expr.append((attribute, attribute in grouping))
            attribute_combinations.append(select_expr)

    return reformat(sql.render(attribute_combinations=attribute_combinations, **kwargs))


def telemetry_variables():
    """Variables for bucket_counts."""
    return dict(
        source_table="telemetry_derived.clients_scalar_aggregates_v1",
        attributes=["os", "app_version", "app_build_id", "channel"],
        aggregate_attributes="""
            metric,
            metric_type,
            key,
            process
        """,
    )


def glean_variables():
    """Variables for bucket_counts."""
    return dict(
        source_table="glam_etl.fenix_clients_scalar_aggregates_v1",
        attributes=["ping_type", "os", "app_version", "app_build_id", "channel"],
        aggregate_attributes="""
            metric,
            metric_type,
            key
        """,
    )


def main():
    """Generate query."""
    parser = ArgumentParser(description=main.__doc__)
    parser.add_argument(
        "--ping-type",
        default="telemetry",
        choices=["glean", "telemetry"],
        help="determine attributes and user data types to aggregate",
    )
    args = parser.parse_args()
    module_name = "bigquery_etl.glam.scalar_percentiles"
    header = f"-- generated by: python3 -m {module_name}"
    header += " " + " ".join(
        [f"--{k} {v}" for k, v in vars(args).items() if k != "init"]
    )
    variables = (
        telemetry_variables() if args.ping_type == "telemetry" else glean_variables()
    )
    print(render_query(header=header, **variables))


if __name__ == "__main__":
    main()
