from jinja2 import Environment, PackageLoader
from pathlib import Path
from bigquery_etl.format_sql.formatter import reformat

ATTRIBUTES = ["client_id", "os", "app_version", "app_build_id", "channel"]

USER_DATA_TYPE = """
ARRAY<
    STRUCT<
      metric STRING,
      metric_type STRING,
      key STRING,
      process STRING,
      agg_type STRING,
      value FLOAT64
    >
  >
"""

USER_DATA_ATTRIBUTES = [
    "metric",
    "metric_type",
    "key",
    "process",
    # [agg_type, value] are shared between telemetry and glean
]


def main():
    env = Environment(loader=PackageLoader("bigquery_etl", "glam/templates"))
    main_sql = env.get_template("clients_scalar_aggregates_v1.sql")
    rendered = main_sql.render(
        header="-- generated by: python3 -m bigquery_etl.glam.scalar_aggregates_incremental",
        user_data_type=USER_DATA_TYPE,
        user_data_attributes=",".join(USER_DATA_ATTRIBUTES),
        attributes=",".join(ATTRIBUTES),
    )
    print(reformat(rendered))


if __name__ == "__main__":
    main()
