fields:
- name: experimenter_slug
  type: STRING
  mode: NULLABLE
- name: normandy_slug
  type: STRING
  mode: NULLABLE
- name: type
  type: STRING
  mode: NULLABLE
- name: status
  type: STRING
  mode: NULLABLE
- name: start_date
  type: DATE
  mode: NULLABLE
- name: end_date
  type: DATE
  mode: NULLABLE
- name: enrollment_end_date
  type: DATE
  mode: NULLABLE
- name: proposed_enrollment
  type: INTEGER
  mode: NULLABLE
- name: reference_branch
  type: STRING
  mode: NULLABLE
- name: is_high_population
  type: BOOL
  mode: NULLABLE
- name: branches
  type: RECORD
  mode: REPEATED
  fields:
  - name: slug
    type: STRING
    mode: NULLABLE
  - name: ratio
    type: INTEGER
    mode: NULLABLE
  - name: features
    type: JSON
    mode: NULLABLE
- name: app_id
  type: STRING
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: channels
  type: STRING
  mode: REPEATED
- name: targeting
  type: STRING
  mode: NULLABLE
- name: targeted_percent
  type: FLOAT
  mode: NULLABLE
- name: namespace
  type: STRING
  mode: NULLABLE
- name: feature_ids
  type: STRING
  mode: REPEATED
- name: is_rollout
  type: BOOL
  mode: NULLABLE
- name: outcomes
  type: STRING
  mode: REPEATED
- name: segments
  type: STRING
  mode: REPEATED
- name: randomization_unit
  type: STRING
  mode: NULLABLE
- name: is_firefox_labs_opt_in
  type: BOOL
  mode: NULLABLE
- name: is_enrollment_paused
  type: BOOL
  mode: NULLABLE
