fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client.
- name: os
  type: STRING
  mode: NULLABLE
  description: The operating system on which the client is running (e.g., 'Windows_NT', 'Darwin', 'Linux'). An asterisk ('*') indicates the value has
    been aggregated across all operating systems.
- name: app_version
  type: INTEGER
  mode: NULLABLE
  description: User visible version string (e.g. "1.0.3") for the browser.
- name: app_build_id
  type: STRING
  mode: NULLABLE
  description: The build ID of the Firefox application (e.g., '20240509170740'). An asterisk ('*') indicates the value has been aggregated across all
    build IDs.
- name: channel
  type: STRING
  mode: NULLABLE
  description: The Firefox release channel from which the client is reporting (e.g., 'release', 'beta', 'nightly').
- name: scalar_aggregates
  type: RECORD
  mode: REPEATED
  fields:
  - name: metric
    type: STRING
    mode: NULLABLE
  - name: metric_type
    type: STRING
    mode: NULLABLE
  - name: key
    type: STRING
    mode: NULLABLE
  - name: process
    type: STRING
    mode: NULLABLE
  - name: agg_type
    type: STRING
    mode: NULLABLE
  - name: value
    type: FLOAT
    mode: NULLABLE
