
--
-- Query generated by: templates/unnest_parquet_view.sql.py sync_summary_v2 telemetry_raw.sync_summary_v2
CREATE OR REPLACE VIEW
  `moz-fx-data-derived-datasets.telemetry.sync_summary_v2` AS
SELECT
  submission_date_s3 AS submission_date,
  * REPLACE (
    ARRAY(SELECT * FROM UNNEST(devices.list)) AS devices,
    ARRAY(SELECT AS STRUCT _0.element.* REPLACE (ARRAY(SELECT * FROM UNNEST(_0.element.outgoing.list)) AS outgoing, (SELECT AS STRUCT _0.element.validation.* REPLACE (ARRAY(SELECT * FROM UNNEST(_0.element.validation.problems.list)) AS problems)) AS validation) FROM UNNEST(engines.list) AS _0) AS engines
  )
FROM
  `moz-fx-data-derived-datasets.telemetry_raw.sync_summary_v2`
