fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: event_object
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: event_object
- mode: NULLABLE
  name: nbr_events
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: nbr_events
- name: nbr_distinct_users
  type: INTEGER
  mode: NULLABLE
  description: Number of distinct users
