fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The UTC calendar date on which a ping or record was received by Mozilla's
    ingestion pipeline. Used as the primary partitioning and filtering dimension for
    date-based analysis.
- name: os_version_bucket
  type: STRING
  mode: NULLABLE
  description: A bucket for OS versions - for example, Win10, Win11, etc.
- name: new_profiles
  type: INTEGER
  mode: NULLABLE
  description: The number of newly created Firefox profiles observed within the aggregation
    period. A value of 0 indicates no new profiles were created for that record's
    segment.
