fields:
  - name: submission_date
    type: DATE
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: submission_date
  - name: recommendation_id
    type: STRING
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: recommendation_id
  - name: tile_id
    type: INTEGER
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: tile_id
  - name: position
    type: INTEGER
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: position
  - name: product
    type: STRING
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: product
  - name: placement
    type: STRING
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: placement
  - name: os
    type: STRING
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: os
  - name: form_factor
    type: STRING
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: form_factor
  - name: impression_count
    type: INTEGER
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: impression_count
  - name: click_count
    type: INTEGER
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: click_count
  - name: save_count
    type: INTEGER
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: save_count
  - name: dismiss_count
    type: INTEGER
    mode: NULLABLE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: dismiss_count
