fields:
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: user_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    field: user_id
    file: bigquery_etl/schema/firefox_accounts_derived.yaml
- name: hmac_user_id
  type: STRING
  mode: NULLABLE
